### ISSUE TITLE
codec does not support config priority

### ISSUE THREAD

**Issue by AhmedEzio47** [ryanheise/just_audio#377] opened 2021-04-14 15:11 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
I'm using just_audio and audio_service to play (network and local audio files), it was working fine until I upgraded my code to flutter 2, now it gives the following codec error,
I/OMXClient(15107): IOmx service obtained
I/ACodec  (15107): codec does not support config priority (err -2147483648)
I/ACodec  (15107): codec does not support config priority (err -2147483648)
I/ACodec  (15107): codec does not support config operating rate (err -2147483648)
W/ExtendedACodec(15107): Failed to get extension for extradata parameter

and the notification controls are not working any more, when I click any of them more than once the app crashes with the following error,
 Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{306c50d
u0 com.devyat.alhani/com.dooboolab.TauEngine.FlautoBackgroundAudioService}
E/AndroidRuntime(15107):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1978)
E/AndroidRuntime(15107):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15107):        at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(15107):        at android.app.ActivityThread.main(ActivityThread.java:7565)
E/AndroidRuntime(15107):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15107):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(15107):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Minimal reproduction project**
1. Fork this repository https://github.com/AhmedEzio47/Alhany.git
2.git checkout flutter_2 
3. Then use the following command to run it: flutter run --no-sound-null-safety

**To Reproduce (i.e. user steps, not code)**
1. Click on any singer
2. Click on any song
3. Click play
5. Click on notification pause button 2 times, the app crashes with error stated above

**Error messages**

```
I/OMXClient(15107): IOmx service obtained
I/ACodec  (15107): codec does not support config priority (err -2147483648)
I/ACodec  (15107): codec does not support config priority (err -2147483648)
I/ACodec  (15107): codec does not support config operating rate (err -2147483648)
W/ExtendedACodec(15107): Failed to get extension for extradata parameter
-------------------------------------
 Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{306c50d
u0 com.devyat.alhani/com.dooboolab.TauEngine.FlautoBackgroundAudioService}
E/AndroidRuntime(15107):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1978)
E/AndroidRuntime(15107):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15107):        at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(15107):        at android.app.ActivityThread.main(ActivityThread.java:7565)
E/AndroidRuntime(15107):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15107):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(15107):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Expected behavior**
No codec errors and the notification controls works and causes no crashes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 pro+ 10.0.17763 Build 17763]
 - Browser [e.g. chrome + 89.0.4389.128]

**Smartphone (please complete the following information):**
 - Device: [POCO X3 NFC]
 - OS: [Android 10]

**Flutter SDK version**
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.17763.1577], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

```

**Additional context**

**Comment by ryanheise** [comment] 2021-04-14 15:32
Your error message is coming from flutter_sound. That is neither a just_audio error nor an audio_service error. Maybe the minimal reproduction project you provided is not the same as the project you used to generate this error.

**Comment by AhmedEzio47** [comment] 2021-04-14 15:50
Sorry I forgot to say you need to checkout flutter_2 branch

**Comment by ryanheise** [comment] 2021-04-14 15:56
Still, your error message is coming from flutter_sound.

Nothing in what you said indicates an error in just_audio. However, since the error happens once you try starting a service, (audio_service), you should look into the issue with that rather than just_audio.

Also, as mentioned in the audio_service README, that plugin does not work with other plugins that overlap in responsibilities. flutter_sound definitely overlaps in responsibilities - it tries to start its own service. The error message specifically is about flutter_sound trying to create a service, which won't work because you are using audio_service instead to create the service.

I'll close this as not related to just_audio.

**Closed by ryanheise** 2021-04-14 15:56 UTC
Labels: 1 backlog, bug
