### ISSUE TITLE
Re: Cannot Clip item of Playlist #471

### ISSUE THREAD

**Issue by marcqtan** [ryanheise/just_audio#474] opened 2021-08-03 06:02 UTC
#471 
This was answered before but I have a new reply and closed_issue might not get new reply notifications.

@ryanheise 
What if I only want to clip it at a later time? (e.g. using the player.setClip() api)
or i want to modify the clip values during runtime like in my case, thru a click of a button

The one in example_playlist will only apply during init.

**Which API doesn't behave as documented, and how does it misbehave?**
The setClip() api is showing an error. I'm using a ConcatenatingAudioSource() since i'm creating a playlist. I want to clip the mp3's of the playlist but when I use setClip() it's showing error below:

`type 'ConcatenatingAudioSource' is not a subtype of type 'UriAudioSource' in type cast
`

**Minimal reproduction project**
You can check the code here: 
[https://github.com/marcqtan/just_audio/blob/master/just_audio/example/lib/main.dart
](https://github.com/marcqtan/just_audio/blob/master/just_audio/example/lib/main.dart
)
**To Reproduce (i.e. user steps, not code)**
1. Run the sample app in the given link
2. Click play button
3. Put a value to "Start" textbox (e.g. 2)
4. Put a value to "End" textbox (e.g. 5)
5. Click "Apply AB"
6. Check logs

**Error messages**

```
type 'ConcatenatingAudioSource' is not a subtype of type 'UriAudioSource' in type cast
```

**Expected behavior**
I should be able to clip mp3 items of a playlist

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac catalina 10.15.17
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Samsung A31
 - OS: Android 10

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment] 2021-08-03 07:33
Duplicate of #471

**Closed by ryanheise** 2021-08-03 07:33 UTC
Labels: 1 backlog, bug

**Comment by ryanheise** [comment] 2021-08-03 07:42
Please stop creating invalid and duplicate bug reports. #471 is the actual issue. #473 and #474 are duplicates, and #473 also did not follow the instructions for bug submission.
