### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods))

### ISSUE THREAD

**Issue by SeanningTatum** [ryanheise/just_audio#44] opened 2020-02-17 01:32 UTC
During initialization the app crashes and throws this error

<img width="705" alt="Screen Shot 2020-02-17 at 9 31 13 AM" src="https://user-images.githubusercontent.com/26712061/74617501-5273f080-5168-11ea-9a17-c456534478b4.png">

**Comment by YaarPatandarAA** [comment] 2020-02-27 22:29
Same

**Comment by ryanheise** [comment] 2020-03-04 12:43
This could be related to some changes to the plugin architecture since Flutter 1.12. Have you updated your project to the Flutter 1.12 structure, and have all plugins that you use been updated to the Flutter 1.12 plugin architecture?

**Comment by YaarPatandarAA** [comment] 2020-03-05 02:43
Yeah it was something to do with updating. I just made sure all the plugins where updated. Also made sure the android side had all updated done.

**Comment by wemiprog** [comment] 2020-04-08 20:00
Have this Issue too. Flutter is on V 1.12.13+hotfix.9, seems to be the latest on stable channel, I updated all plugins, still doesn't work. Version of this plugin is 0.1.4.

What can I do to fix this? Or is there a fix planned?

**Comment by ryanheise** [comment] 2020-04-09 13:58
Have you updated your project to the Flutter 1.12 structure, and have all plugins that you use been updated to the Flutter 1.12 plugin architecture?

**Comment by Tizoner** [comment] 2020-04-23 16:25
I was having this Issue too. Flutter is on V 1.12.13+hotfix.9. I've tried everything - checked that all plugins at the latest version, used flutter clean command, and was even comparing java files and manifests between my app and example app of this package. Strange things started when I've tried to run flutter clean command - it failed and vscode started to send bunch of notifcation that Dart Analyzer is terminated. Unfortunately, I didn't save logs because at that moment I didn't know whether I'll even be able to solve this problem. But in logs I saw something about android builder tasks that couldn't finish - that's why Dart Analyzer has terminated and I couldn't delete build folder using flutter clean command. When I tried second time after restarting Dart Analyzer I was able to delete build folder using flutter clean command. However, new build failed again but with another errors - the only one that I remembered from them was something about Androidx incompatibilities in a plugin. And no matter how many times I tried to build it was throwing the same errors. So I've started to compare all files in android folder between my app and example app of this plugin. All was the same except one thing - my minSdkVersion was 16 while minSdkVersion of example app is 21. When I've updated mindSdkVersion build succeeded and bug disappeared. I've tried to set minSdkVersion back to 16 and build also was successfull and bug didn't appear. However, when I was trying to build again after running flutter clean command build failed two times in a row with this kind of an error:
"Execution failed for task ':app:mergeDebugNativeLibs'". On the third time build was successfull and bug didn't appear.
So yeah, there are really might be some bugs underhood.

**Comment by ryanheise** [comment] 2020-04-23 16:29
Have you updated your project to the Flutter 1.12 structure, and have all plugins that you use been updated to the Flutter 1.12 plugin architecture?

**Comment by Tizoner** [comment] 2020-04-23 16:38
@ryanheise As I've said in my previous message, Flutter is on V 1.12.13+hotfix.9 and I've checked that all plugins are up to date.
I've just switched from audioplayers plugin to just_audio because it gives better performance and better control over streams.

**Comment by ryanheise** [comment] 2020-04-23 16:41
Even if your Flutter is on 1.12+ and your plugins are up to date, that does not answer my question regarding whether your project is updated to the 1.12 project structure and whether all of the plugins you use have been updated to the 1.12 plugin architecture.

**Comment by Tizoner** [comment] 2020-04-23 16:58
Project structure is updated to the 1.12 but I'm not sure how to check if these plugins are updated to the 1.12 plugin architecture:
```
cupertino_icons: ^0.1.2
youtube_explode_dart: ^0.0.15
path_provider: ^1.6.5
http: 0.12.0+4
cached_network_image: ^2.1.0+1
flutter_reorderable_list: ^0.1.3
just_audio: ^0.1.7
audio_service:
  git:
    url: https://github.com/ryanheise/audio_service.git
```

**Comment by YaarPatandarAA** [comment] 2020-04-23 17:30
@Tizoner By project structure @ryanheise is referring to you having done the following: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

I was having this same error last night in an Old App in which I swapped out AudioPlayers for Just_Audio. By following the instructions set out by the flutter team and a little google research on `MissingPluginException flutter 1.12` I was able to get it working. There is no problem in just_audio in regards to MissingPluginException.

**Comment by wemiprog** [comment] 2020-04-25 15:42
Thx for the help :) It worked for me now after following the link of @YaarPatandarAA .

**Comment by emaddoma** [comment] 2020-07-07 16:29
I've been banging my head for 4 days trying to solve for this error.  Everything in my app works fantastic on iOS but I'm getting these errors on Android.

`E/flutter (18855): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
E/flutter (18855): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (18855): <asynchronous suspension>
E/flutter (18855): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (18855): #2      AudioPlayer._init (package:just_audio/just_audio.dart:50:24)
E/flutter (18855): #3      new AudioPlayer._internal (package:just_audio/just_audio.dart:132:48)
E/flutter (18855): #4      new AudioPlayer (package:just_audio/just_audio.dart:130:19)
E/flutter (18855): #5      new AudioPlayerBackgroundTask (package:louisiana/app/audio_player/audio_player_task.dart:37:34)
E/flutter (18855): #6      _audioPlayerTaskEntrypoint.<anonymous closure> (package:louisiana/app/home/home_widget.dart:33:36)
E/flutter (18855): #7      AudioServiceBackground.run (package:audio_service/audio_service.dart:940:29)
E/flutter (18855): #8      _audioPlayerTaskEntrypoint (package:louisiana/app/home/home_widget.dart:33:26)
E/flutter (18855): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (18855): #10     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (18855): #11     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (18855): #12     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (18855): #13     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (18855): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (18855): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (18855): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (18855): 
I/flutter (18855): AUDIO: Media: null, playing: false, processing: AudioProcessingState.none
I/flutter (18855): 2020-07-07 12:23:07.227656 - LOCATION EVENT: [Location {mock: true, is_moving: false, event: motionchange, extras: {}, activity: {confidence: 100, type: still}, odometer: 7743388.0, uuid: 81a35f62-275d-4a61-bfd7-c242cdf7a91a, timestamp: 2020-07-07T16:23:07.023Z, battery: {is_charging: true, level: 0.99}, coords: {altitude: 46.0, heading: -1.0, latitude: 29.953582863449785, speed: 0.51, accuracy: 2.7, longitude: -90.06422964245105}}]
I/flutter (18855): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (18855): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter (18855): com.ryanheise.just_audio.events.1594138986687824:
I/flutter (18855): MissingPluginException(No implementation found for method listen on channel
I/flutter (18855): com.ryanheise.just_audio.events.1594138986687824)
I/flutter (18855): When the exception was thrown, this was the stack:
I/flutter (18855): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (18855): <asynchronous suspension>
I/flutter (18855): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (18855): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
I/flutter (18855): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
I/flutter (18855): #11     new AudioPlayer._internal (package:just_audio/just_audio.dart:162:59)
I/flutter (18855): #12     new AudioPlayer (package:just_audio/just_audio.dart:130:19)
I/flutter (18855): #13     new AudioPlayerBackgroundTask (package:louisiana/app/audio_player/audio_player_task.dart:37:34)
I/flutter (18855): #14     _audioPlayerTaskEntrypoint.<anonymous closure> (package:louisiana/app/home/home_widget.dart:33:36)
I/flutter (18855): #15     AudioServiceBackground.run (package:audio_service/audio_service.dart:940:29)
I/flutter (18855): #16     _audioPlayerTaskEntrypoint (package:louisiana/app/home/home_widget.dart:33:26)
I/flutter (18855): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
I/flutter (18855): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
I/flutter (18855): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter (18855): (elided 12 frames from class _RawReceivePortImpl and dart:async)
I/flutter (18855): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (18855): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (18855): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (18855): <asynchronous suspension>
E/flutter (18855): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (18855): #2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
E/flutter (18855): #3      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)
E/flutter (18855): #4      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:44:27)
E/flutter (18855): #5      BaseCacheManager._createFileDir (package:flutter_cache_manager/src/cache_manager.dart:254:41)
E/flutter (18855): #6      BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:23)
E/flutter (18855): #7      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
E/flutter (18855): #8      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
E/flutter (18855): #9      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
E/flutter (18855): #10     new BackgroundAudioTask (package:audio_service/audio_service.dart:1258:45)
E/flutter (18855): #11     new AudioPlayerBackgroundTask (package:louisiana/app/audio_player/audio_player_task.dart)
E/flutter (18855): #12     _audioPlayerTaskEntrypoint.<anonymous closure> (package:louisiana/app/home/home_widget.dart:33:36)
E/flutter (18855): #13     AudioServiceBackground.run (package:audio_service/audio_service.dart:940:29)
E/flutter (18855): #14     _audioPlayerTaskEntrypoint (package:louisiana/app/home/home_widget.dart:33:26)
E/flutter (18855): #15     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (18855): #16     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (18855): #17     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (18855): #18     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (18855): #19     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (18855): #20     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (18855): #21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (18855): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (18855): 
E/flutter (18855): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter (18855): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (18855): <asynchronous suspension>
E/flutter (18855): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (18855): #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter (18855): #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
E/flutter (18855): #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
E/flutter (18855): #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter (18855): #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter (18855): #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
E/flutter (18855): #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
E/flutter (18855): #9      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
E/flutter (18855): #10     CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:43:33)
E/flutter (18855): #11     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:39:49)
E/flutter (18855): #12     BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:12)
E/flutter (18855): #13     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
E/flutter (18855): #14     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
E/flutter (18855): #15     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
E/flutter (18855): #16     new BackgroundAudioTask (package:audio_service/audio_service.dart:1258:45)
E/flutter (18855): #17     new AudioPlayerBackgroundTask (package:louisiana/app/audio_player/audio_player_task.dart)
E/flutter (18855): #18     _audioPlayerTaskEntrypoint.<anonymous closure> (package:louisiana/app/home/home_widget.dart:33:36)
E/flutter (18855): #19     AudioServiceBackground.run (package:audio_service/audio_service.dart:940:29)
E/flutter (18855): #20     _audioPlayerTaskEntrypoint (package:louisiana/app/home/home_widget.dart:33:26)
E/flutter (18855): #21     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (18855): #22     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (18855): #23     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (18855): #24     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (18855): #25     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (18855): #26     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (18855): #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (18855): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

I've quadruple-checked the project structure and ensured the plugins are up to date.

**Comment by ryanheise** [comment] 2020-07-07 16:38
This error (while difficult to read without link breaks) is most likely due to outside factors other than just_audio, particularly other plugins you use in your project that create `FlutterEngine`s or the way that you may be loading plugins. From your error message, it appears you're using audio_service which does create `FlutterEngine`s, so you could try posting a bug report on that project.

**Comment by stonega** [comment] 2020-07-07 17:44
@emaddoma  Looks like you want to run plugins in isolate, but origin isolate in dart don't support plugins. Just my thought.

**Comment by emaddoma** [comment] 2020-07-07 17:52
@stonega Interesting.  As I said, I don't have any issues on iOS so I'm skeptical that this is rooted in Flutter isolate

**Comment by stonega** [comment] 2020-07-07 18:02
@emaddoma You can try this isolate plugin if you want to run plugins in isolate https://github.com/rmawatson/flutter_isolate

**Comment by ryanheise** [comment] 2020-07-07 18:18
It's difficult to read without the line breaks, but it looks like the error is occurring from within a background audio task created by audio_service which uses the same techniques as flutter_isolate, so I don't think flutter_isolate would help here.

See my previous reply for next steps. You can verify that just_audio is not the cause of the bug by trying to use any other random plugin of your choice on the line above where you do `new AudioPlayer()`. No matter what plugin you pick, it will crash with the same error, and you could try to blame that plugin, but of course since it would happen with any plugin, it's not that plugin's fault, the problem lies elsewhere. I would suggest you fill in a bug report on audio_service supplying all required information, and then I can at least investigate whether it is a bug in audio_service (it may turn out to be yet another plugin in your project, but when you submit the bug report, you will be asked to provide a project that reproduces the bug so that I can investigate such things).

**Comment by emaddoma** [comment] 2020-07-07 19:41
@ryanheise Thank you for the thoughtful response.  There are a few other plugins that may be involved here, but I'm still not entirely clear on why there would be a problem on Android and not iOS.  I'll see if I can come up with a stripped-down version of the app to demonstrate.

**Comment by emaddoma** [comment] 2020-07-08 21:10
@ryanheise Is there any chance I could invite you to our private repo to have a quick look?  I could provide notes on the structure and expected behavior.

**Comment by ryanheise** [comment] 2020-07-09 03:06
@emaddoma I used to offer to do that when I had a small number of users, but unfortunately I'm just too busy to offer that service anymore. In most cases when people ask me to take a look at their project, it turns out that it's not really a bug in my plugin and really had nothing whatsoever to do with me, and I ended up essentially spending all of my weekend helping to debug someone else's project. The plugin began to stagnate because I didn't have any time left over to actually fix legitimate bugs or build new features.

That is not to say that you haven't legitimately found a bug in my plugin, but I'd like you to put in the extra effort to narrow it down yourself first. Creating a minimal reproduction project is an exercise that forces you to remove everything from your project that doesn't relate to the bug, down to the absolute minimum that is needed, and it is through that process that you might realise on your own whether the bug lies elsewhere and might not be something you should ask me to investigate. Ideally, in narrowing it down, you can be confident that the bug lies with a particular project before you submit a bug report to that project.

**Comment by emaddoma** [comment] 2020-07-17 01:02
@ryanheise I found the problem.  I can't explain why, but the plugin gallery_saver was not compatible

**Comment by ryanheise** [comment] 2020-07-17 02:05
I used to have a section in the README about how you can approach the developers of other plugins and ask them to adapt their plugin to function correctly in the background, although it seems I have deleted it. Still, my recommendation would be to submit a feature request on that project, supplying all information necessary to help the developer understand the issue.

**Comment by ryanheise** [comment] 2020-08-01 05:07
I will close this issue, although if anyone else has this issue, note that it most commonly happens when plugins are loaded in the background. Not all plugins work well in the background (this one does), and to make matters worse, the error message typically does not identify the plugin that is causing the issue. As @emaddoma noticed above, you may be able to find which plugin is causing the problem by process of elimination, removing plugins one by one until the error goes away. If you identify which plugin it is, it could be helpful to report a bug with that plugin. Additionally, if you are using audio_service to manage the background dart code, it will be helpful to let me know via the audio_service issues page so that I am aware of plugins that are known to cause issues in the background.

**Closed by ryanheise** 2020-08-01 05:07 UTC
Labels: 1 backlog, bug

**Comment by deep1931** [comment] 2020-12-21 10:54
I am facing the same issue, I have tried to diagnose and found there are two plugins which are not compatible with just_audio. When I remove flutter_facebook_login and intent plugin from pubspec.yaml file then it is not showing Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)  works as expected.

**Comment by ryanheise** [comment] 2020-12-21 12:35
@deep1931 FYI it is probably best to stick to plugins that have been updated recently. flutter_facebook_login hasn't been updated in more than a year and in particular still uses the old v1 plugin architecture on Android which is now deprecated (and can cause errors of this sort). If you search on the flutter_facebook_login issues page, you will see people have suggested alternatives including just using a web view.

**Comment by deep1931** [comment] 2020-12-22 07:24
Hi, thanks for your response. I have figured out that this issue does not belong to just_audio, it is related to audio_service. I have changed the Facebook login plugin but still, have an issue, and that issue is because of intent plugin. I am using a recent update of intent but somehow it is not working with audio_service. 

When I play music using just_audio it is working fine, but when I user AudioServiceWidget (Using example given, not modified) and press on the play button that time it shows errors as follows. 



[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (23493): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (23493): <asynchronous suspension>
E/flutter (23493): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23493): #2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
E/flutter (23493): #3      getTemporaryDirectory (package:path_provider/path_provider.dart:55:39)
E/flutter (23493): #4      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:44:27)
E/flutter (23493): #5      BaseCacheManager._createFileDir (package:flutter_cache_manager/src/cache_manager.dart:254:41)
E/flutter (23493): #6      BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:23)
E/flutter (23493): #7      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
E/flutter (23493): #8      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
E/flutter (23493): #9      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
E/flutter (23493): #10     new BackgroundAudioTask (package:audio_service/audio_service.dart:1605:45)
E/flutter (23493): #11     new AudioTask (package:just_audio_service/background/audio-task.dart)
E/flutter (23493): #12     new PositionedAudioTask.standard (package:just_audio_service/position-manager/positioned-audio-task.dart:43:25)
E/flutter (23493): #13     _audioPlayerTaskEntrypoint.<anonymous closure> (package:radio/src/player/new_player.dart:177:66)
E/flutter (23493): #14     AudioServiceBackground.run (package:audio_service/audio_service.dart:1196:24)
E/flutter (23493): #15     _audioPlayerTaskEntrypoint (package:radio/src/player/new_player.dart:176:26)
E/flutter (23493): #16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (23493): #17     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23493): #18     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23493): #19     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (23493): #20     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (23493): #21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (23493): #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (23493): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23493): 

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter (23493): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (23493): <asynchronous suspension>
E/flutter (23493): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23493): #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter (23493): #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
E/flutter (23493): #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
E/flutter (23493): #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter (23493): #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter (23493): #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
E/flutter (23493): #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
E/flutter (23493): #9      getDatabasesPath (package:sqflite/sqflite.dart:161:54)
E/flutter (23493): #10     CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:43:33)
E/flutter (23493): #11     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:39:49)
E/flutter (23493): #12     BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:12)
E/flutter (23493): #13     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
E/flutter (23493): #14     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
E/flutter (23493): #15     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
E/flutter (23493): #16     new BackgroundAudioTask (package:audio_service/audio_service.dart:1605:45)
E/flutter (23493): #17     new AudioTask (package:just_audio_service/background/audio-task.dart)
E/flutter (23493): #18     new PositionedAudioTask.standard (package:just_audio_service/position-manager/positioned-audio-task.dart:43:25)
E/flutter (23493): #19     _audioPlayerTaskEntrypoint.<anonymous closure> (package:radio/src/player/new_player.dart:177:66)
E/flutter (23493): #20     AudioServiceBackground.run (package:audio_service/audio_service.dart:1196:24)
E/flutter (23493): #21     _audioPlayerTaskEntrypoint (package:radio/src/player/new_player.dart:176:26)
E/flutter (23493): #22     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (23493): #23     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23493): #24     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23493): #25     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (23493): #26     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (23493): #27     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (23493): #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (23493): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (23493): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (23493): <asynchronous suspension>
E/flutter (23493): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23493): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (23493): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
E/flutter (23493): #4      HivePositionDataManager.init (package:just_audio_service/position-manager/position-data-manager.dart:84:30)
E/flutter (23493): #5      HivePositionDataManager.getPositions (package:just_audio_service/position-manager/position-data-manager.dart:113:31)
E/flutter (23493): #6      HivePositionDataManager.getPosition (package:just_audio_service/position-manager/position-data-manager.dart:110:14)
E/flutter (23493): #7      PositionedAudioTask.onPlayFromMediaId (package:just_audio_service/position-manager/positioned-audio-task.dart:90:27)
E/flutter (23493): #8      AudioTaskDecorater.onPlayFromMediaId (package:just_audio_service/background/audio-task-decorator.dart:31:16)
E/flutter (23493): #9      DownloadAudioTask.onPlayFromMediaId (package:just_audio_service/download-manager/download-audio-task.dart:91:11)
E/flutter (23493): #10     AudioServiceBackground.run.<anonymous closure> (package:audio_service/audio_service.dart:1234:25)
E/flutter (23493): #11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (23493): #12     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (23493): #13     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (23493): #14     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (23493): #15     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23493): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23493): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23493): #18     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (23493): #19     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)

**Comment by ryanheise** [comment] 2020-12-22 07:57
I have updated your comment so that the hash+number references are wrapped in a code block

```
like this
```

A bare hash+number is a reference to another GitHub issue, and if you create a reference, it creates a false link between this issue and 30 other issues.

(Hmm, it seems the issue references are permanent. Editing your post did not successfully remove your issue reference from the 30 other issue pages.)

In any case, please contact the author of the intent plugin and file a bug report. Even though that plugin has been recently updated, it is still using the deprecated v1 plugin architecture for Android.

**Comment by deep1931** [comment] 2020-12-24 03:46
> I have updated your comment so that the hash+number references are wrapped in a code block
> 
> ```
> like this
> ```
> 
> A bare hash+number is a reference to another GitHub issue, and if you create a reference, it creates a false link between this issue and 30 other issues.
> 
> (Hmm, it seems the issue references are permanent. Editing your post did not successfully remove your issue reference from the 30 other issue pages.)
> 
> In any case, please contact the author of the intent plugin and file a bug report. Even though that plugin has been recently updated, it is still using the deprecated v1 plugin architecture for Android.

Thanks, for the support, I had removed defected plugin for now, and it started working now. Thanks.

**Comment by sadikul1500** [comment] 2021-11-02 14:02
I am trying to play audio files in windows desktop software. But I am facing this issue and can't solve this.  My flutter version is 2.7.0-3.0.pre , Channel beta. The error I am getting:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)

#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
\<asynchronous suspension\>

#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
\<asynchronous suspension\>

#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1255:13)
\<asynchronous suspension\>

#3      AudioPlayer.load (package:just_audio/just_audio.dart:708:26)  
\<asynchronous suspension\>

#4      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:683:18)

\<asynchronous suspension\>`
