### ISSUE TITLE
Android Duration is null when setUrl audio from appwrite server 

### ISSUE THREAD

**Issue by kalizhome** [ryanheise/just_audio#955] opened 2023-03-13 16:57 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Using ConcatenatingAudioSource and AudioSource.uri for set playlist

**Minimal reproduction project**

**To Reproduce**
Call Play and listen durationStream is return null when setUrl audio from appwrite server
Example link from appwrite server:
https://sound.kalizhome.com/v1/storage/buckets/640f50b8f1d2809109e9/files/640f50c7035ea1be6977/view?project=640f50b26605ff058324

**Error messages**

```
 _audioPlayer.durationStream.listen((totalDuration) {
      print(
        "total: $totalDuration",
      );
      progressBarState = ProgressBarState(
          current: progressBarState.current,
          buffered: progressBarState.buffered,
          total: totalDuration ?? Duration.zero);
      notifyListeners();
    });
durationStream is null
```

**Expected behavior**
If I use url from soundhelix example song or the same file upload to firebase it work fine. But if upload file to appwrite server it will return duration null

**Screenshots**

**Smartphone (please complete the following information):**
 - Android 

**Flutter SDK version**
```

```

**Additional context**

**Comment by ryanheise** [comment] 2023-03-14 01:04
> **Which API doesn't behave as documented, and how does it misbehave?**
> Using ConcatenatingAudioSource and AudioSource.uri for set playlist

I consider the README as part of the documentation, and it already mentions that null can be returned in certain situations. Can you clarify in what way the behaviour you observed is not expected even in light of the documentation, and how the actual behaviour is different from that documentation?

**Comment by kalizhome** [comment] 2023-03-14 03:09
I can see different response from appwrite vs firebase or other server in response headers. Appwrite not return content-length in status code 200 because they use transfer encode chunk. Is key difference I can see

**Comment by ryanheise** [comment] 2023-03-14 05:19
Do you want to keep this open as a bug or close?

**Comment by kalizhome** [comment] 2023-03-14 05:25
Found this issue but can't find any solution to fix

**Comment by ryanheise** [comment] 2023-03-14 05:31
Yes but this page is for submitting but reports that I need to fix. There is nothing here for me to fix. You also claimed it was a bug without referencing the documentation which says that null is expected under certain conditions such as when your server is not configured correctly.

If it is not a bug that I need to fix, please close. If you need help configuring your server, whether that be firebase or other, I can't help you with that.

**Comment by stnguyen90** [comment] 2023-03-14 14:21
> null is expected under certain conditions such as when your server is not configured correctly.

@ryanheise would you be able to advise on what is required in order to determine the duration? That way, we can see what is configured incorrectly.

My understanding is the content length header should be omitted if the transfer encoding is chunked. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding).

**Comment by ryanheise** [comment] 2023-03-14 14:45
I'm closing this bug, because it is not a bug.

**Closed as completed by ryanheise** 2023-03-14 14:45 UTC
Labels: bug, 1 backlog

**Comment by stnguyen90** [comment] 2023-03-15 00:07
@ryanheise would you be able to provide some insight based on [my last comment](https://github.com/ryanheise/just_audio/issues/955#issuecomment-1468194007)?

**Comment by ryanheise** [comment] 2023-03-15 00:19
I have already told you I don't provide advice on how to configure your server. I am locking this discussion, and based on just_audio's documented requirements, please research on your own how you can configure your own server to satisfy those requirements.
