### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by slimyTextBox** [ryanheise/just_audio#228] opened 2020-10-28 20:06 UTC
**Which API doesn't behave as documented, and how does it misbehave?**

Build failed with exception when the package is included in the project: just_audio 0.5.5

 posted the bug on flutter page also
flutter/flutter#69236

This exception is reported on the link below, I tried most solutions on that page to no av
flutter/flutter#49938
Failed solutions:

1- deleting build folder

2-
flutter channel stable
flutter upgrade --force
flutter pub cache repair
flutter clean

3- Through android studio: File > Invalidate Caches/Restart...

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. add just_audio 0.5.5 package to yaml and save
2. Click on debug/run
3. See error

**Error messages**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


```

**Expected behavior**

build successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [wondows 10]
 - Browser [vscode]

**Smartphone (please complete the following information):**
 - Device: [samsung s8]
 - OS: [android 9]

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-CA)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment] 2020-10-29 01:25
Hi @slimyTextBox it seems you forgot to fill in the most important section of the bug report which is the "minimal reproduction project". I'm not sure if you actually "forgot" because you were reminded of it very recently. Here is the reply you got from the previous time you opened this issue:

> Oops, it appears that your issue did not follow the template and is missing one or more required sections. Please open a new issue, and provide all required sections and information.
> 
> FAQ:
> 
> 1. Do I really need to submit a minimal reproduction project for a bug? A: Yes. I prioritise bugs _secondarily_ on how many people are affected, and _primarily_ on whether the bug report is complete, in the sense that it enables me to immediately reproduce it and start working on a fix. If a bug is important to you, the best thing you can do is to provide all requested information ASAP so that I can start looking into it ASAP.

Did you read that? The sooner you provide that the sooner I can help you.

It also mentions it at the top of the bug report template that you need to fill in this section. Thanks.

**Comment by slimyTextBox** [comment] 2020-10-31 03:25
After some trial and error it seemed like there is a conflict between the package and some Firebase packages, but then when I upgraded JDK 14=>15 the issue was resolved.

**Comment by ryanheise** [comment] 2020-10-31 05:19
I'll close this issue then, although there is still something here that I would have liked to investigate had you provided a minimal reproduction project.

**Closed by ryanheise** 2020-10-31 05:19 UTC
Labels: 1 backlog, bug
