### ISSUE TITLE
CLOSED AGAIN

### ISSUE THREAD

**Issue by ghost** [ryanheise/just_audio#744] opened 2022-05-29 07:38 UTC

**Comment by altrepo2022** [comment] 2022-05-29 07:42
`transforms-3/22fc58c1aba25a38624b19fcaec4a163/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.`

**Comment by ryanheise** [comment] 2022-05-29 07:46
> **Minimal reproduction project** Provide a link here using one of two options:
> 
>     1. no need since it's not related to project.

I'm sorry, but it is needed. Please edit your issue and supply the requested information (this is the third time you have submitted this issue and each time you have decided on your own to not provide what I have asked for in the instructions - if you don't provide this information, I will have to close the issue again.)

**Comment by altrepo2022** [comment] 2022-05-29 07:48
> > **Minimal reproduction project** Provide a link here using one of two options:
> > ```
> > 1. no need since it's not related to project.
> > ```
> 
> I'm sorry, but it is needed. Please edit your issue and supply the requested information (this is the third time you have submitted this issue and each time you have decided on your own to not provide what I have asked for in the instructions - if you don't provide this information, I will have to close the issue again.)

how can i reproduce problem when problem comes with just upgrading plugin. do you want to create empty flutter project where is just installed just_audio latest version and link it?

**Comment by ryanheise** [comment] 2022-05-29 07:51
Since you have deleted the instructions, you probably won't be able to follow them now. So I'll close this issue as invalid. Please open a new issue, but only if you can follow the instructions properly.

> how can i reproduce problem when problem comes with just upgrading plugin

As the instructions say, if the provided example project already illustrates the error, you can state that under this section. But note that if the official example works for you, that would suggest that you're actually doing something wrong and you should study the differences between your own project and the example project to see how to do it correctly.

You also didn't fill in the last section correctly on copying the output of flutter doctor. Hence, open a new issue and see the original instructions. If you decide not to follow the instructions on the 4th attempt, I'm afraid that I'll have to end it there as I can't keep repeatedly asking you to follow the instructions, where I think are clear enough.

**Closed as completed by ryanheise** 2022-05-29 07:51 UTC
Labels: bug, 1 backlog

**Comment by altrepo2022** [comment] 2022-05-29 07:53
> Since you have deleted the instructions, you probably won't be able to follow them now. So I'll close this issue as invalid. Please open a new issue, but only if you can follow the instructions properly.
> 
> > how can i reproduce problem when problem comes with just upgrading plugin
> 
> As the instructions say, if the provided example project already illustrates the error, you can state that under this section. But note that if the official example works for you, that would suggest that you're actually doing something wrong and you should study the differences between your own project and the example project to see how to do it correctly.
> 
> You also didn't fill in the last section correctly on copying the output of flutter doctor. Hence, open a new issue and see the original instructions. If you decide not to follow the instructions on the 4th attempt, I'm afraid that I'll have to end it there as I can't keep repeatedly asking you to follow the instructions, where I think are clear enough.

i tried several time but you are just closing all issues so i prefer to wait someone else, if old versions was working perfectly and changing version caused error, i don't think that's my fault

**Comment by ryanheise** [comment] 2022-05-29 07:56
Yes, you can either contribute a valid issue or wait for someone else to contribute one.
