### ISSUE TITLE
Using `ClippingAudioSource` with proxy caused the full audio to be loaded

### ISSUE THREAD

**Issue by snipd-min** [ryanheise/just_audio#804] opened 2022-08-26 13:20 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Using `ClippingAudioSource` with the proxy (e.g. configure userAgent) would buffer the whole media file (on the proxy request) instead of just the clip.

**Minimal reproduction project**
Use the example project modified [here](https://github.com/snipd-min/just_audio/tree/fix/clipping-with-proxy). Basically I set an user-agent to enable to proxy and use a clipping audio source.

I also added some `print()`s and modify the way to pipe the response on the proxy just to illustrate the issue... 

**Note: I'm not sure if there is a better way to illustrate without touching this code other than monitoring the network of the device. If this is wrong, please let me know.** 
```
var size = 0;
final completer = Completer<void>();
originResponse.listen((event) {
  size += event.length;
  request.response.add(event);
}, onDone: () {
  completer.complete();
});
await completer.future;
```
instead of 
```
await originResponse.pipe(request.response);
```

**To Reproduce (i.e. user steps, not code)**
1. Click "Play"
2. The audio stops after 5 seconds as expected
3. However, checking the log, the full audio file is downloaded -> see the logs below

**Error messages**

```
X> handler [originResponse] = statusCode:200, contentLength: 91924300, headers: k: last-modified, v: [Thu, 22 Nov 2018 16:46:59 GMT]; k: date, v: [Fri, 26 Aug 2022 12:59:29 GMT]; k: accept-ranges, v: [bytes]; k: content-length, v: [91924300]; k: etag, v: ["3070f5cf7516aca788c71f69d5b0d245-11"]; k: x-amz-request-id, v: [QSZV081C6GG8FZ9N]; k: content-type, v: [audio/mp3]; k: x-amz-id-2, v: [ifHS5xPVqlDee+3C/7sVIzK9ceOk8/frklZFjBUahZle0yLaT2z1BronZ47nL/osTzEeSszHmRc=]; k: server, v: [AmazonS3]; 
...
I/flutter (28612): X> size final https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3 = 91924300
```

**Expected behavior**
Would expect with the proxy that not the full audio file is loaded when using a clip audio source.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Browser Chrome Version 104.0.5112.79

**Smartphone (please complete the following information):**
 - Device: Android/iOS

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-arm, locale en-CH)
    • Flutter version 3.0.1 at /Users/minzhao/fvm/versions/3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/minzhao/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/minzhao/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/minzhao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • R58MB1MD8KT • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Additional context**
Related to the discussion in https://github.com/ryanheise/just_audio/pull/797

**Comment by snipd-min** [comment] 2022-08-26 13:33
Also when trying to clip in the middle, for instance, [1s, 5s]. In the original request only the `bytes=start-` was sent:
```
I/flutter ( 4966): X> handler [request] = url:/scifri-episodes/scifri20181123-episode.mp3, method: GET, headers: k: user-agent, v: [just_audio/1.0 (Linux;Android 12) ExoPlayerLib/2.17.1]; k: connection, v: [Keep-Alive]; k: accept-encoding, v: [identity]; k: range, v: [bytes=103138-]; k: icy-metadata, v: [1]; k: host, v: [127.0.0.1:46729]; 

I/flutter ( 4966): X> handler [originRequest] = url:https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3, method: GET, headers: k: user-agent, v: [just_audio/1.0 (Linux;Android 12) ExoPlayerLib/2.17.1]; k: connection, v: [Keep-Alive]; k: accept-encoding, v: [identity]; k: range, v: [bytes=103138-]; k: icy-metadata, v: [1]; k: host, v: [127.0.0.1:46729]; 

I/flutter ( 4966): X> handler [originResponse] = statusCode:200, contentLength: 91924300, headers: k: last-modified, v: [Thu, 22 Nov 2018 16:46:59 GMT]; k: date, v: [Fri, 26 Aug 2022 13:29:54 GMT]; k: accept-ranges, v: [bytes]; k: content-length, v: [91924300]; k: etag, v: ["3070f5cf7516aca788c71f69d5b0d245-11"]; k: x-amz-request-id, v: [588MZADE88Y4PPFP]; k: content-type, v: [audio/mp3]; k: x-amz-id-2, v: [PG/3ool8aazMNqVHzSNAIjctPeV454+f40pOTAiwYjYI1wbUydL7syoj5xoeA7bC733TlPiOMI0=]; k: server, v: [AmazonS3]; 

I/flutter ( 4966): X> size final https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3 = 91924300
```

Could it be that the remainder of the response is not really used but the proxy still completes the full GET request? 

PS: the logs here are done in Android, but the same results also happen in iOS.

**Comment by ryanheise** [comment] 2022-08-28 12:43
I am guessing that if this is working correctly without the proxy, it is because ExoPlayer is making a `GET` request all the way to the end of the file, but is disconnecting after it gets as much as it needs. However, `pipe` is not able to detect that ExoPlayer is no longer reading the data. That seems to be a flaw in Dart's HTTP library. I don't see any API to actually detect a disconnection. In the native socket libraries, I believe this would be detected by the write call returning -1, but I se nowhere in the HTTP or Socket implementations where that is exposed...

An alternate theory is that ExoPlayer is never actually disconnecting from the socket and is just throttling its consumption like it does for normal media to keep the lookahead buffer within specified limits. But for a `ClippingMediaSource` I would have expected it to disconnect once it knows it's done.

**Comment by ryanheise** [comment] 2022-08-28 14:11
Can you try this?

```dart
        // await originResponse.pipe(request.response);
        var done = false;
        request.response.done.then((dynamic _) => done = true);
        await for (var chunk in originResponse) {
          if (done) break;
          request.response.add(chunk);
        }
```

**Comment by ryanheise** [comment] 2022-08-28 17:29
Just tested the above and it looks like ExoPlayer isn't closing the connection, so `done = true` isn't triggered. Instead, I suspect ExoPlayer is just blocking while leaving open the connection.

Out of curiosity, when you said it works without the proxy, did you verify this by monitoring the server side behaviour? If so, do your observations confirm that the client holds open the connection without reading data?

**Comment by snipd-mikel** [comment] 2022-08-29 08:24
@ryanheise What you have found out seems in line with what we have noticed as well. We haven't yet monitored the server side behavior, but I also believe that ExoPlayer is not closing the connection and it just keeps it idle (I have noticed that ExoPlayer does some initial connections as well to get the file information, and those get closed correctly). I'll try to verify this by monitoring the actual requests going out.

Regarding detecting this on the Dart side, I was also not able to find any API on the HttpServer or HttpRequest classes to detect this.

**Comment by ryanheise** [comment] 2022-08-29 08:38
It may be that I'll need to make a feature request on the dart sdk GitHub.

But in the meantime, you should be able to use a shorter term workaround in your app by implementing your own custom subclass of `StreamAudioSource` that disconnects from the origin server once enough data has been buffered (by monitoring `bufferedPosition`).

**Comment by ryanheise** [comment] 2022-08-29 09:49
I was able to get it to work by disabling the `HttpResponse`'s buffer and by calling `flush` after every write:

```dart
        // In _proxyHandlerForUri...
        request.response.bufferOutput = false;
        var done = false;
        request.response.done.then((dynamic _) => done = true);
        await for (var chunk in originResponse) {
          if (done) break;
          request.response.add(chunk);
          await request.response.flush();
        }
```

Can you let me know if that works for you?

**Comment by snipd-mikel** [comment] 2022-08-29 12:59
I have tried your solution, and it behaves differently on iOS and Android.

### Android
I have added a log inside the loop to check how many bytes are read sent to the response and can see that it's the expected amount (around 5MB / 2min). However, `request.response.done` is never completed so the `originResponse` is not closed. That means that the originalResponse will keep reading data from the upstream.


### iOS
Here the log shows that all the bytes of the range are sent to the `response`. That means that the audio file is read until the end, since no end range is sent.

**Comment by ryanheise** [comment] 2022-08-29 13:11
`response.done` is not expected to fire, since ExoPlayer is holding onto the connection based on its own heuristics (you can probably report an issue to ExoPlayer if that behaviour is not desirable w.r.t. `ClippingMediaSource`.)

On iOS, have you confirmed that it actually works the way you want without the proxy? Note that a range request is not possible here since there is no way for the player to know in advance how many bytes it will need to fetch to cover a certain number of seconds of decoded audio, due to the nature of compression, so it is understandable that it does not make a range request here. However, I suspect what you're seeing here is not the proxy's doing but just the way that Apple's player works. It will buffer as much as possible. I suggest setting some load control parameters in the `AudioPlayer` constructor to limit the size of the forward buffer. In particular, try reducing `DarwinLoadControl.preferredForwardBufferDuration`.

**Comment by snipd-mikel** [comment] 2022-08-29 14:26
I have made some more tests on Android, checking the actual requests being made to the server.  Your solutions seems to improve the previous issue, but doesn't seem to always behave the same way: There are times were the requests stop at 5MB, but sometimes they keep growing until the full episode is downloaded (104MB).

I have checked the behavior with and without the Proxy:

### Without proxy
ExoPlayer always makes 2 requests.

1. **Get the file header:** Usually downloads 1MB and **it's always closed**
2. **Get the data range:** It downloads around 5MB/2min and it's kept open, without downloading any more data

### With proxy
Usually, the proxy makes also 2 requests:

1. **Get the file header:** Also 1MB but this one **is not closed**
2. **Get the data range:** Also 5MB/2min and it's kept open. When this happens, no more data is downloaded.

However, sometimes the proxy gets more than 2 requests, and in this cases, all the open requests keep downloading data until the end of the audio file. None of these requests have a range header. I'm not sure why this is happening.

Regarding iOS, I will check how the requests look with and without the proxy and try to tweak the `preferredForwardBufferDuration` to see if it improves the situation.

**Comment by ryanheise** [comment] 2022-08-29 14:46
Can you edit your issue with instructions on how I can reproduce this? Or does this still happen with your existing reproduction project with the same URL?

**Comment by snipd-mikel** [comment] 2022-08-29 15:38
I'll update the instructions later. I also cannot reproduce it consistently on Android.

Regarding iOS: It seems that the behavior with and without proxy it's the same: AVPlayer will always download a big chunk of the file (around 30MB is what we have seen), no matter the length of the clip or the `preferredForwardBufferDuration` used.

**Comment by snipd-mikel** [comment] 2022-08-31 08:57
I have tried to reproduce the issue I mentioned on Android and was not able to do so with the reproduction project, so I will assume it is something we do on our end that has that weird behavior sometimes.

So I think the fix that you have proposed fixes the situation on both Android and iOS and the requests are not the same with and without the proxy enabled. Should we include this fix on the open PR we have?

Also, thanks for proposing using `StreamAudioSource`, I think that will solve our issue where the iOS player is loading more data than needed :)

**Comment by ryanheise** [comment] 2022-08-31 10:23
Before you go that far, I suggest trying a few iOS options. In addition to `preferredForwardBufferDuration`, try also setting `automaticallyWaitsToMinimizeStalling` to `false`.

**Comment by ryanheise** [comment] 2022-08-31 10:25
Also regarding the fix, I'll make a PR tonight and we can merge them as two separate PRs. If you would rather not deal with rebasing yourself, let me know and I'll just merge your PR first and mine second. But on the other hand, if you do the rebasing yourself, you'll be able to also confirm whether it all works together on your end before the final merge.

**Comment by snipd-mikel** [comment] 2022-08-31 10:28
Regarding the iOS options: I have also tried setting `automaticallyWaitsToMinimizeStalling` to false, but couldn't see a difference. I played with different durations for `preferredForwardBufferDuration` but it seemed to always load the same amount of data.

Regarding rebasing, I have no problem doing it, so I'm happy to rebase my PR after your changes.

**Comment by snipd-mikel** [comment] 2022-08-31 12:26
@ryanheise 
While testing the StreamAudioSource I found one small issue: When the proxy is stopped (by disposing the player it belongs to) or the original response (`request.response`) is done, the subscription to the `StreamAudioSource` stream is not canceled, so it will keep getting data even if there are no consumers.

You can see the fix in this commit: https://github.com/snipd-mikel/just_audio/commit/483d163b57025291be45f6ce0e7327b9e9004260

I think it fits with the other changes that you are planning to merge, so I didn't create a PR. Let me know if I should do so or open a new issue.

**Comment by ryanheise** [comment] 2022-08-31 12:42
That's fine to keep it in the same PR.

The `preferredForwardbufferDuration` behaviour is a bug on the iOS side. I did not notice before, but the load control parameters are not propagated to clipping audio sources, so I expect that once I fix that, you should be able to control the buffer correctly in your use case.

**Comment by ryanheise** [comment] 2022-09-01 11:10
I originally thought it was an issue of propagating the parameters tot he clipping audio source, but after investigating I found it already does that. So this over-eager buffering is just the native behaviour of iOS, and I don't think there is anything I can do to change that behaviour. Therefore you would probably need to use that `StreamAudioSource` workaround.

Anyway, I have pushed the other fix to `fix/clip_buffering` if you want to just check and confirm it works for you. I'll merge after dinner.

**Comment by snipd-mikel** [comment] 2022-09-01 13:44
Thanks for rechecking the issue with the buffering.I have started to use the StreamAudioSource and it works pretty good already. 

The `fix/clip_buffering` branch looks good :) 

Regarding the other fix on the proxy I mentioned on my comment (https://github.com/snipd-mikel/just_audio/commit/483d163b57025291be45f6ce0e7327b9e9004260): Should I include it on the PR I have open?

**Comment by ryanheise** [comment] 2022-09-03 09:53
`fix/clip_buffering` is merged.

Regarding your other fix, yes it's fine to keep that in the same PR (https://github.com/ryanheise/just_audio/issues/804#issuecomment-1232888083)

**Comment by snipd-mikel** [comment] 2022-09-07 10:49
Thanks for clarifying, was not sure if we were talking about a PR you would create or mine :) I'll rebase and add the fix later on the afternoon

**Comment by ryanheise** [comment] 2022-09-15 14:21
I'll close this as resolved by the recent commits. Even though iOS buffers too eagerly, there is nothing I can do about that for the time being since the API that should be able to limit the forward buffer duration does not actually seem to do anything.

**Closed as completed by ryanheise** 2022-09-15 14:21 UTC
Labels: bug, 1 backlog
