### ISSUE TITLE
AndroidEqualizer.parameters method lack of async

### ISSUE THREAD

**Issue by te8uekm12** [ryanheise/just_audio#860] opened 2022-11-02 18:32 UTC
**Which API doesn't behave as documented, and how does it misbehave?**

There is no async keyword in method declaration.
AndroidEqualizer.parameters 

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

class AndroidEqualizer extends AudioEffect with AndroidAudioEffect {
....
  /// The parameter values of this equalizer.
  Future<AndroidEqualizerParameters> get parameters =>
      _parametersCompleter.future;

}

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment] 2022-11-03 01:44
As you should know now, you need to follow the instructions under each section of the bug report. You skipped almost every section, and the sections where you wrote something, you didn't follow the instructions.

Also, this is not a bug. You did not show in the first section that the behaviour is different from the documentation. Closing.

**Closed as not planned** 2022-11-03 01:44 UTC
Labels: bug, 1 backlog
