### ISSUE TITLE
Cache/Download streamed audio file

### ISSUE THREAD

**Issue by ktoosiu** [ryanheise/just_audio#226] opened 2020-10-27 14:20 UTC
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
When i'm playing audio from online source using i.e. HlsAudioSource or AudioSource.uri I'd like to be able to local cache/download this audio file

**Describe alternatives you've considered**
I can play audio and separately download it, but it's not good solution

**Additional context**
n/a

**Comment by ryanheise** [comment] 2020-10-27 14:34
The same feature request only yesterday so I'll close this as a duplicate of #223 which itself was a:

Duplicate of #47

**Closed by ryanheise** 2020-10-27 14:34 UTC
Labels: 1 backlog, enhancement
