### ISSUE TITLE
Can't load files from internal storage and play them

### ISSUE THREAD

**Issue by LacErnest** [ryanheise/just_audio#203] opened 2020-10-08 09:58 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Jus_audio

**Minimal reproduction project**
https://github.com/LacErnest/just_audio/blob/master/just_audio/example/lib/main.dart

**To Reproduce (i.e. user steps, not code)**
1.Launch the app
2.Got to Records tab 
3.Playlist is empty
4.so can't play sound

**Error messages**
No error messages

**Expected behavior**
Should see a playlist of downloaded sounds and should be able to play those.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: [Itel A86]
 - OS: [Android 8]

**Flutter SDK version**
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [version 10.0.15063], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Additional context**
I'm downloading sound files from my API and store them at ```/storage/emulated/0/Download``` and then fill the conatenateAudioSource with those files.
In my command prompt when i print those files location i do see them and in the phone files app i see them also.
I want to know why my playlist doesn't load and how to fix it?

**Comment by ryanheise** [comment] 2020-10-08 10:33
This project doesn't run as the `pubspec.yaml` is incomplete.

**Comment by ryanheise** [comment] 2020-10-08 10:39
> **Which API doesn't behave as documented, and how does it misbehave?**
> Jus_audio

Out of curiosity, why did you not fill in this section? I'd like to know if I need to improve the wording of the instructions. The point is to highlight "how" the actual behaviour of some specific API is different from the documentation of that API.

**Comment by LacErnest** [comment] 2020-10-08 10:47
> This project doesn't run as the `pubspec.yaml` is incomplete.

```
https://github.com/LacErnest/just_audio/blob/master/lib/screens/share.dart
```

**Comment by LacErnest** [comment] 2020-10-08 10:49
> > **Which API doesn't behave as documented, and how does it misbehave?**
> > Jus_audio
> 
> Out of curiosity, why did you not fill in this section? I'd like to know if I need to improve the wording of the instructions. The point is to highlight "how" the actual behaviour of some specific API is different from the documentation of that API.

Oh my bad i was more focused on the "which" part.

**Comment by ryanheise** [comment] 2020-10-08 12:46
> > > **Which API doesn't behave as documented, and how does it misbehave?**
> > > Jus_audio
> > 
> > 
> > Out of curiosity, why did you not fill in this section? I'd like to know if I need to improve the wording of the instructions. The point is to highlight "how" the actual behaviour of some specific API is different from the documentation of that API.
> 
> Oh my bad i was more focused on the "which" part.

With all of said focus, maybe you could have narrowed down the "which" part to something more specific than merely the name of this plugin (and maybe you could have at least spelled the plugin name correctly).

You were asked specifically to "Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.", not just state the name of the plugin you're submitting the bug report to - completely unhelpful to me.

Now onto your "zero" word answer:

> > This project doesn't run as the `pubspec.yaml` is incomplete.
> 
> ```
> https://github.com/LacErnest/just_audio/blob/master/lib/screens/share.dart
> ```

I don't really know what you expect from me here since you didn't really communicate in words. You really should communicate in words if you expect me to do something for you or help you. If you expect me to debug your app, though, I'm sorry not going to do that. A minimal reproduction project is required, and I think that was clearly stated in the instructions and the FAQ.

So I will close this issue, but you are free to open a new issue if you can follow the issue submission instructions in a way that is going to help me to investigate your issue.

**Closed by ryanheise** 2020-10-08 12:46 UTC
Labels: 1 backlog, bug
