### ISSUE TITLE
Error when build app 

### ISSUE THREAD

**Issue by faress123** [ryanheise/just_audio#124] opened 2020-07-03 19:29 UTC
I have an error when I build the flutter app,

the error is : 

```
 FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.2.2\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'just_audio'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.2.2\android\gradle\wrapper\gradle-wrapper.properties to gradle-5
.6.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin just_audio could not be built due to the issue above.

```

can you help me ????

**Comment by ryanheise** [comment] 2020-07-04 03:09
>    > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.2.2\android\gradle\wrapper\gradle-wrapper.properties to gradle-5
.6.4-all.zip

For now you can downgrade your gradle version to 5.6.2 (which just_audio uses) by editing your gradle-wrapper.properties file. This is the version of gradle that is generated by "flutter create" and is the most likely to avoid version conflicts. If that does not resolve the issue for you, I'm afraid I can't help until you fill in a complete bug report.

**Comment by mohammadne** [comment] 2020-08-07 06:13
**recently** , I am also getting this error a lot.

**Comment by ryanheise** [comment] 2020-08-07 15:43
The Flutter project template still sits at gradle 5.6.2 so I'm sticking with that version. As soon as Flutter's own recommendation bumps up to 5.6.4, I will follow suit, so in the meantime the solution is to downgrade your gradle version to 5.6.2 to match.

**Comment by ryanheise** [comment] 2020-08-12 05:13
Closing since it does not appear to be a bug and no minimal reproduction project was provided.

**Closed by ryanheise** 2020-08-12 05:13 UTC
Labels: 1 backlog, bug
