### ISSUE TITLE
Audio Looping

### ISSUE THREAD

**Issue by fuzing** [ryanheise/just_audio#125] opened 2020-07-06 20:25 UTC
I was just wondering if there is any plan to implement audio looping in the (near) future.   This is definitely a feature that I think many would find useful.

My particular use case requires this to be gapless - so if this was made available, that would be awesome.

Cheers, and thanks!

**Comment by ryanheise** [comment] 2020-07-07 01:44
Hi @fuzing what platforms do you need this for?

**Comment by fuzing** [comment] 2020-07-07 11:59
I need it for Android and IOS.  Sorry, I'd forgotten to be more specific.

Thanks for your assistance with this.

**Comment by ryanheise** [comment] 2020-07-07 12:30
Do you need to loop a single track or a whole playlist, or both?

**Comment by fuzing** [comment] 2020-07-07 13:14
For my application it's just a single track - I use looping to provide an endless ambient background track (jungle noises, sounds of a river, etc.), which is why gapless is important for my use case.

**Comment by ryanheise** [comment] 2020-07-27 18:44
Hi @fuzing , looping is now supported in the media-source branch. Please see issue #131 for details and I will close this issue.

**Comment by ryanheise** [comment] 2020-07-27 18:44
Duplicate of #131

**Closed by ryanheise** 2020-07-27 18:44 UTC
Labels: 2 fixing, enhancement

**Comment by fuzing** [comment] 2020-07-27 19:18
Amazing - thank you so very much for your assistance with this!
