### ISSUE TITLE
Hackers Using  just_audio script for hacking my shoutcast server

### ISSUE THREAD

**Issue by naguchennai** [ryanheise/just_audio#118] opened 2020-06-21 08:10 UTC
Hackers Using  just_audio script for hacking my shoutcast server
They sent thousand of connection we got 5 server already  crashed and of data hacked  i already rises this problem but they deleted my post no response ...

**Comment by ryanheise** [comment] 2020-06-21 08:18
Duplicate of #114

**Closed by ryanheise** 2020-06-21 08:18 UTC
Labels: 1 backlog, bug

**Comment by nanthakumarfm** [comment] 2020-06-21 10:12
Yes bro My icecast server recieved 500+ listerner from same ip same time i found that app from play store they using flutter with  just_audio

**Comment by ryanheise** [comment] 2020-06-21 10:28
@nanthakumarfm what was the name of the app? Do you have a link?
