### ISSUE TITLE
[IOS and macOS] slow load time and loaded track duration is 2x original track  

### ISSUE THREAD

**Issue by HosamHasanRamadan** [ryanheise/just_audio#844] opened 2022-10-14 22:07 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
- `AudioPlayer.load` : is relatively slower than Android.
- `AudioPlayer.duration`  : player duration is 2x the original duration. 

**Minimal reproduction project**
- reproducible code for the issue [gist](https://gist.github.com/HosamHasanRamadan/6ccf7ec60ea6dc476f6262b354d99ef8) 

**To Reproduce (i.e. user steps, not code)**
1.  `flutter create error_code` 
2. `cd error_code`
3. `flutter pub add  just_audio youtube_explode_dart`
4. copy [gist](https://gist.github.com/HosamHasanRamadan/6ccf7ec60ea6dc476f6262b354d99ef8) to `lib/main.dart`
5. `flutter run`

**Error messages**

```
No Error Message
```

**Expected behavior**
- loaded and original tracks duration should be equal
- loading track speed should be relatively similar to android  

**Screenshots**
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-14 at 23 43 09](https://user-images.githubusercontent.com/28815699/195949240-68804361-592c-4336-9c69-351c5d623d9d.png)

**Desktop (please complete the following information):**
 - OS: MacOS +  12.4 

**Smartphone (please complete the following information):**
 - Device: iPhone SE 3rd gen - Emulator
 - OS: IOS 15.5

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.4 21F79 darwin-arm, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by ryanheise** [comment] 2022-10-15 01:29
I'm not at my computer right now but I believe these two separate issues have been posted before (as two separate issues). Can you try searching for them in the meantime?

By the way, load speed is not necessarily a bug, it's the behaviour of iOS. You need to pass in load control parameters to change that behaviour.

**Comment by HosamHasanRamadan** [comment] 2022-10-15 12:49
> I'm not at my computer right now but I believe these two separate issues have been posted before (as two separate issues). Can you try searching for them in the meantime?
> 
> By the way, load speed is not necessarily a bug, it's the behaviour of iOS. You need to pass in load control parameters to change that behaviour.

Thank you for clarification.
Yes, this issue was reported before  #828 , #827 
Should I close it as duplicate ?

**Comment by ryanheise** [comment] 2022-10-15 13:23
Duplicate of #828

**Comment by ryanheise** [comment] 2022-10-15 13:24
Duplicate of #827

**Comment by ryanheise** [comment] 2022-10-15 13:24
Done.

(I think there are even more duplicates. People tend not to search for existing issues before posting new ones.)

**Closed as completed by ryanheise** 2022-10-15 13:24 UTC
Labels: bug, 1 backlog
