### ISSUE TITLE
Audio still plays even app state is killed.

### ISSUE THREAD

**Issue by 1041harpreet** [ryanheise/just_audio#1098] opened 2023-10-23 21:12 UTC
Even user has killed the app it still playing the audio and notification still shows . it should be only played till it in background not after killed by user

**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment] 2023-10-24 00:59
Please don't completely ignore the instructions for submitting an issue, and then after receiving a response explaining why your bug was closed, then submit a second issue that also completely ignores the instructions again.

I am closing the issue as promised (please read the previous comment on your previous issue to understand why since you completely ignored what it told you not to do and you did it anyway).

Please do not open a 3rd issue. (Unless you have a legitimate bug to report and you are willing to put in the effort to actually narrow it down to a specific API that does not behave as documented and you can demonstrate this via a reproduction project.)

**Closed as completed by ryanheise** 2023-10-24 00:59 UTC
Labels: bug, 1 backlog
