### ISSUE TITLE
ConcatenatingAudioSource clear and add method throws exception

### ISSUE THREAD

**Issue by ahs441** [ryanheise/just_audio#551] opened 2021-10-13 09:12 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
ConcatenatingAudioSource clear and add method does not work as expected and throws an exception in shuffle mode

**Minimal reproduction project**

**To Reproduce (i.e. user steps, not code)**
1. clearing and adding  some children to ConcatenatingAudioSource instance
2. enabling shuffle mode on the player
3. again clearing and adding  some children to the same instance of ConcatenatingAudioSource
4. toggling shuffle mode
5. See the error

**Error messages**

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.concatenatingRemoveRange (package:just_audio_platform_interface/method_channel_just_audio.dart:174:10)
<asynchronous suspension>
#3      ConcatenatingAudioSource.clear (package:just_audio/just_audio.dart:2417:7)
```

**Expected behavior**
Clearing and adding children to list work without exception

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 14.7.1

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.61.0)
[✓] Connected device (2 available)

• No issues found!

```

**Additional context**

**Comment by priyesh-bit** [comment] 2022-06-20 19:56
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.concatenatingRemoveRange (package:just_audio_platform_interface/method_channel_just_audio.dart:182:10)
<asynchronous suspension>
#3      ConcatenatingAudioSource.clear (package:just_audio/just_audio.dart:2447:7)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.concatenatingInsertAll (package:just_audio_platform_interface/method_channel_just_audio.dart:174:10)
<asynchronous suspension>
#3      ConcatenatingAudioSource.addAll (package:just_audio/just_audio.dart:2366:7)
<asynchronous suspension>
```

Im getting the above error

**Comment by ryanheise** [comment] 2022-06-21 02:31
Can you clarify, is this reproducible from the unmodified official playlist example? The bug report skipped this section.

**Comment by Jora28** [comment] 2022-07-08 08:18
I have similar problem, but when i add 5 songs to playlist, did not get this Error

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
<asynchronous suspension>
#2      MethodChannelAudioPlayer.concatenatingInsertAll
package:just_audio_platform_interface/method_channel_just_audio.dart:174
<asynchronous suspension>
#3      ConcatenatingAudioSource.add
package:just_audio/just_audio.dart:2336
<asynchronous suspension>
```

**Comment by ryanheise** [comment] 2022-07-08 08:28
I don't yet have a way to reproduce this.

@ahs441 left the "Minimal reproduction project" section blank. I have asked in my previous comment whether this can be reproduced using the official playlist example (`example_playlilst.dart`) as the minimal reproduction project and I got no answer.

I appreciate there is some interest for me to investigate, but I can assure you that nothing will happen unless someone can actually provide me with a valid reproduction project and steps as I explained in the original instructions.

**Comment by Jora28** [comment] 2022-07-08 08:44
Please use this and i think you get this Error, in (example_playlilst.dart) minimal reproduction project 
_playlist.clear();
_playList.add(List of AudioSource, list must be big then 10)

**Comment by ryanheise** [comment] 2022-07-08 08:57
The instructions from the beginning have been to provide a link to a minimal reproduction project, not coding instructions for how I can make the project myself.

**Comment by ryanheise** [comment] 2022-07-08 09:45
@Jora28 would you be willing to open a new issue? That way you will be able to see the instructions for what I require, focusing in particular on the reproduction project (not "code snippet" but actual "project"). To do it, you simply fork this repository, edit the example with the code you wanted me to write, then provide the link to me so that it's ready for me to investigate.

**Comment by Jora28** [comment] 2022-07-08 09:49
@ryanheise thanks i solve this issue by myself  
this way....
@ahs441 use this code
  Rx<ConcatenatingAudioSource> _playlist1 = ConcatenatingAudioSource(
    useLazyPreparation: true,
    children: [],
  ).obs;
_playlist.value.clear();
_playlist1.value = ConcatenatingAudioSource(
        useLazyPreparation: true,
        children: listAudioSource1 (this is my list of AudioSource),
      );

**Comment by ryanheise** [comment] 2022-07-08 09:59
That workaround also invalidates all of your old state streams so you'd need to resubscribe to them. Not ideal. (edit: not actually sure what `playlist1.value` is, so not sure exactly, but at the very least you lose your references and you also lose decoder state.)

If you want a proper solution, or indeed if anyone wants a proper solution (although it seems after 9 months nobody has been motivated enough to want to do this), all you need to do is spend a minute to provide the one missing thing in this bug report: the minimal reproduction project.

**Comment by Jora28** [comment] 2022-07-08 10:51
@ryanheise i edit my comment please check

**Comment by ryanheise** [comment] 2022-07-08 11:26
Still no minimal reproduction project then
 So you don't want a proper solution?

**Comment by ryanheise** [comment] 2022-07-08 12:34
Since no reproduction project is forthcoming, I will close this issue.

If anyone would like a workaround, please use the following:

```dart
await _playlist.removeRange(0, _playlist.children.length);
```

My interest is in improving the plugin, and actually fixing things so that they work correctly. Ways to contribute productively to the plugin are to a) contribute a bug fix, or b) contribute a valid bug report. While this issue is now closed, you are welcome to contribute either of these, or else wait for me to get around to it myself (but the first two options will help make it happen sooner.)

**Closed by ryanheise** 2022-07-08 12:34 UTC
Labels: bug, 1 backlog

**Comment by LouisAldorio** [comment] 2022-07-20 05:49
Can we remove all items in queue ?, I got problem on how to clear the playlist and queue and give the player new playlist and queue, like brand new one.

**Comment by ryanheise** [comment] 2022-07-20 07:21
Still no minimal reproduction project then.

As for the actual topic of this issue, I repeat:

> My interest is in improving the plugin, and actually fixing things so that they work correctly. Ways to contribute productively to the plugin are to a) contribute a bug fix, or b) contribute a valid bug report. While this issue is now closed, you are welcome to contribute either of these, or else wait for me to get around to it myself (but the first two options will help make it happen sooner.)

I'll also lock this thread since it weirdly has gone down a path that defies logic. Please open a new issue and please follow and respect the instructions in order to help make progress happen.
