### ISSUE TITLE
No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`

### ISSUE THREAD

**Issue by ajsatam** [ryanheise/just_audio#225] opened 2020-10-27 11:07 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
While compiling it gives the error 
No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`
and the execution stops
**Minimal reproduction project**
Provide a link here using one of two options:
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. Setup the project in Android studio for iOS platform.
2. Include the require libraries and try to run it on a physical device. 

**Error messages**

```
Running pod install...                                              5.1s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `6.26.0`
      > Copying FirebaseFirestore from `/Users/macmini/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/1710a0cb4281a79dcbbb0d48c608d0a8` to `Pods/FirebaseFirestore`
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `audio_service` from `.symlinks/plugins/audio_service/ios`
    -> Fetching podspec for `audio_session` from `.symlinks/plugins/audio_session/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `facebook_app_events` from `.symlinks/plugins/facebook_app_events/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    firebase_analytics: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_analytics_web` from `.symlinks/plugins/firebase_analytics_web/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    firebase_auth: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_auth_web` from `.symlinks/plugins/firebase_auth_web/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    firebase_messaging: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_isolate` from `.symlinks/plugins/flutter_isolate/ios`
    -> Fetching podspec for `flutter_keyboard_visibility` from `.symlinks/plugins/flutter_keyboard_visibility/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `just_audio` from `.symlinks/plugins/just_audio/ios`
    -> Fetching podspec for `just_audio_web` from `.symlinks/plugins/just_audio_web/ios`
    [!] No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:980:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:959:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:957:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
```

**Expected behavior**
Should get compiled and work on the iOS device.

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS:  iOS13.6

**Flutter SDK version**
```
1.7.1
insert output of "flutter doctor" here
```

**Comment by ryanheise** [comment] 2020-10-27 12:22
HI @ajsatam 

Can you please insert the output of `flutter doctor` where indicated?

Also, since you're testing the iOS build, it would be helpful if you could run the build outside of Android Studio. Can you try just running it from the terminal with `flutter run`?

**Comment by ryanheise** [comment] 2020-10-27 12:26
Just tried building on iOS using `flutter run` and it worked for me. So the only way I can understand the difference between our environments is if you can share details such as the output of `flutter doctor`.

**Comment by ajsatam** [comment] 2020-10-27 12:39
sure, please find below.

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.17.1 at /Users/macmini/Developer/flutter_1_17_1
    • Framework revision f7a6a7906b (6 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macmini/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Ajit’s iPad • 9775c6aa2e0fc4a25aebdd1c29fcf99477e6a9b7 • ios • iOS 13.6

• No issues found!

**Comment by ryanheise** [comment] 2020-10-27 12:46
Thanks. Your versions of almost everything are old, so I would first suggest that you upgrade your software to the latest available.

**Comment by ajsatam** [comment] 2020-10-27 12:54
When I run it separately it works i.e. by including only the plugin with audio_service. But when I include it in my project it gives this error. 

Due to a specific plugin I have to use the current dart version as it does not work on the latest.

**Comment by ryanheise** [comment] 2020-10-27 12:56
I'm not understanding you. You told me in your report that the problem was reproducible when running the example project, but now it seems you're telling me that it works when running it separately, which means that the example SHOULD work.

**Comment by ajsatam** [comment] 2020-10-27 13:00
Sorry my bad. I forgot to remove that line from the new github reply template.

**Comment by ryanheise** [comment] 2020-10-27 13:17
Closing since no minimal reproduction project was provided, and you're on outdated software.

If you are able to establish a reproducible bug in just_audio on the latest software, and provide a link to a minimal reproduction project as per the instructions, I will reopen.

**Closed by ryanheise** 2020-10-27 13:17 UTC
Labels: 1 backlog, bug
