### ISSUE TITLE
Playing audio files on iOS that were saved on Android does not work.

### ISSUE THREAD

**Issue by ablbol** [ryanheise/just_audio#1288] opened 2024-07-15 17:17 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

I have a Flutter chat app where users record an audio and save it to Firebase Storage. I am using just_audio: ^0.9.39 to load the audio files from Firebase storage and play them.

When I follow the following path, I don't run into problems:
- Use iOS device to create audio and save it to Firebase Storage (using audio_waveforms: ^1.0.5). [this works]
- Then, use Android device to retrieve and play the audio (using just_audio: ^0.9.39). [this works]

On the other hand, when I follow the following path, I run into exception:
- Use Android device to create audio and save it to Firebase Storage (using audio_waveforms: ^1.0.5) [this works]
- Then, use iOS device to play the audio on iOS device (using just_audio ^0.9.39) **[this doesn't work]**

This is the exception that I am getting:
```
Cannot Open
AudioPlayer._load (package:just_audio/just_audio.dart:875:9)
<asynchronous suspension>
  AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1501:28)
<asynchronous suspension>
```

When I replaced just_audio with audioplayers: ^6.0.0 using iOS device, the device was able to load and play the audio from Firebase Storage.  Which means that the problem is in just_audio.  I also tried older version of just_audio but still ran into the same problem.

Here is how I get player
```
      final player = AudioPlayer();
      final audioSource = LockCachingAudioSource(Uri.parse(url));
      player.setAudioSource(audioSource, preload: true);
```

This is how I play the audio
```
   player.play();
```

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

It is hard to get minimal project since I am relying on Firebase Storage. However, the description above should be very clear and descriptive of the problem.

**To Reproduce (i.e. user steps, not code)**

Everything was described above

**Error messages**

```
Cannot Open
AudioPlayer._load (package:just_audio/just_audio.dart:875:9)
<asynchronous suspension>
  AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1501:28)
<asynchronous suspension>
```

**Expected behavior**

When hitting the play button using iOS device, I expect the audio file to be loaded and played.  However, that does not happen. This was described above

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - OS: iOS17.5.1

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)            
[✓] Network resources
```

**Additional context**

**Comment by ablbol** [comment] 2024-07-18 15:00
While don't more testing I found out the problem to be in the following code:

```
      final audioSource = LockCachingAudioSource(Uri.parse(url));
      player.setAudioSource(audioSource, preload: false);
```

For some reason, "LockCachingAudioSource" does not work.  If I replace this code like this, I am able to load and play the audio files again.

```
        player.setUrl(url);
```

**Comment by ryanheise** [comment] 2024-07-18 15:14
Ah, that is an issue I'm familiar with, although I haven't gotten to the bottom of it as of yet. (You might like to search for other issues concerning this. If an issue already exists, you can close this one.)

**Comment by VanDuyN** [comment] 2024-07-22 04:09
I also have the same problem but I can't seturl even setAudioSource is there any way to fix it
I will create a UriAudioSource

`UriAudioSource _createAudioSource(SongModel song) {

    debugPrint(url + song.song);
    return ProgressiveAudioSource(Uri.parse(url + song.song));

  }`

then take it out and use

`final audioSource = _createAudioSource(song);
  await audioPlayer.setAudioSource(audioSource);`

At first this method worked, but then the data on my server increased so much that it could no longer be used

**Comment by ryanheise** [comment] 2024-07-22 04:18
@VanDuyN if you have the same issue AND an additional issue (with setUrl), then please submit an additional issue.

Since this issue doesn't provide a reproduction case, and it is likely a duplicate, I will close it.

**Closed as completed by ryanheise** 2024-07-22 04:18 UTC
Labels: bug, 1 backlog

**Comment by VanDuyN** [comment] 2024-07-22 04:26
@ryanheise 

I switched to setUrl as follows and this Url can run normally on my web

`      await audioPlayer.setUrl("http://192.168.1.3:3000/uploads/songs/1721116840818.mp3");
`
But it still shows error

flutter: http://192.168.1.3:3000/uploads/songs/1721116840818.mp3

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-11800) The operation could not be completed
#0      AudioPlayer._load (package:just_audio/just_audio.dart:875:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1501:28)
<asynchronous suspension>

**Comment by ryanheise** [comment] 2024-07-22 04:28
Issue locked. Please submit a new issue as instructed rather than commenting on a closed issue. When you submit a new issue, it will guide you through the instructions for each section of the bug report that you need to complete.
