### ISSUE TITLE
audio background not working with example

### ISSUE THREAD

**Issue by sigjak** [ryanheise/just_audio#502] opened 2021-09-04 19:42 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio_background 0.0.1-beta.1 is not working with Example (modified as per instructions). The app stops and the just_audio_background does not keep it running. The culprit seems to be **didChangeAppLifecycleState** ,; With **didChangeAppLifecycleState** commented out the app runs as expected.

**Minimal reproduction project**
Provide a link here using one of two options:
https://github.com/sigjak/Heise_backgr

**To Reproduce (i.e. user steps, not code)**
Run app with background and didChangeAppLifecycleState

**Error messages**

```
NA
```

**Expected behavior**
Expected to run with just_audio_background,not closing

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
MOTO G8

**Flutter SDK version**
2.2.3
insert output of "flutter doctor" here
NA

**Additional context**

**Comment by ryanheise** [comment] 2021-09-05 01:43
> **To Reproduce (i.e. user steps, not code)**
> Steps to reproduce the behavior:
> Run app with background and didChangeAppLifecycleState

Can you please fill in this section as per the instructions? `didChangeAppLifecycleState` is code, not user steps.

User steps:

1. Click on what?
2. Then what?

i.e. What does the "user" of the app need to do and in what order?

**Comment by sigjak** [comment] 2021-09-05 05:23
Case 1 (with didChangeAppLifecycleState)
Step 1. Click on play to start playing. Audio plays.
Step 2. After a while audio stops and does not play in background.

Case 2 (without didChangeAppLifecycleState)
Step 1. Click on play to start playing. Audio plays normally until  end.

**Comment by ryanheise** [comment] 2021-09-05 05:53
Isn't it just stopping because you called `stop`? That seems expected behaviour to me. Or are you implying that the plugin itself called `stop` when it shouldn't have? If so, which API is not behaving as documented, and how did it misbehave? i.e. I need to understand if this is a bug in the plugin or whether this is just a bug in your app.

**Comment by sigjak** [comment] 2021-09-05 08:44
The app is your Example downloaded from github and modified to use Just_audio_background as per instructions. Stop is not called. If I run the app and press play it starts playing but stops when the phone "goes to sleep". ie. it is not running in the background and the background interface does not show.

If I comment out didChangeAppLifeCycle.... it does not stop, the background interface shows and it continues until the end of the audiosource.

It seems to me that it is the didChangeApp... method that calls  the stop. The code is  on https://github.com/sigjak/Heise_backgr

**Comment by ryanheise** [comment] 2021-09-05 08:55
You just confirmed everything I suspected which makes it clear that it is not a bug in the plugin.

You are calling `stop` yourself in `didChangeAppLifeCycle`, it wasn't this plugin that did it. So if you don't want it to stop, then the solution is easy: don't call `stop()`.

Closing as not a bug.

**Closed by ryanheise** 2021-09-05 08:55 UTC
Labels: bug, 1 backlog

**Comment by sigjak** [comment] 2021-09-05 09:15
I guess i did not understand the purpose of the didChange... method in your example, and still don´t. It seems that AppLifecycleState is changed to pause when just_audio_background intervenes and that stops the player.
Anyway, I apologize for the misunderstanding and the trouble I have caused and I thank you for an excellent plugin.

**Comment by ryanheise** [comment] 2021-09-05 09:46
No problem, I know you meant well, but please keep in mind the instructions for bug submission which should help you to confirm that it is a bug in the plugin rather than a bug in the app.
