### ISSUE TITLE
Crash while dispose

### ISSUE THREAD

**Issue by RaistlinTAO** [ryanheise/just_audio#61] opened 2020-03-24 14:59 UTC
Player was using mp4 file from network in a stateful widget, the app crashed with log below after press the back button.

**Everything in flutter doctor is OK**

Detailed steps:
1. Open the view which contains the player with _mp4 file 1_.
2. Let the file downloaded, and click the play button
3. After 1-3 seconds, press the back button.
4. Open another view which contains the player with _mp4 file 2_.
5. After 1-3 seconds, press the back button.
6. If not crash, open another view or simply redo step 1 - 5

Following the debug steps, it crashed during the dispose();

Crash Log:

> D/NetworkSecurityConfig(15198): No Network Security Config specified, using platform default
I/VideoCapabilities(15198): Unsupported profile 4 for video/mp4v-es
I/OMXClient(15198): IOmx service obtained
I/ACodec  (15198): codec does not support config priority (err -2147483648)
D/AudioTrack(15198): getTimestamp_l(27): device stall time corrected using current time 31617190413800
W/AudioTrack(15198): getTimestamp_l(27): retrograde timestamp time corrected, 31617208557400 < 31617212458600
I/ExoPlayerImpl(15198): Release 806d62c [ExoPlayerLib/2.11.1] [generic_x86_arm, sdk_gphone_x86, Google, 29] [goog.exo.core]
I/ExoPlayerImpl(15198): Init 840da8c [ExoPlayerLib/2.11.1] [generic_x86_arm, sdk_gphone_x86, Google, 29]
I/OMXClient(15198): IOmx service obtained
I/ACodec  (15198): codec does not support config priority (err -2147483648)
I/ACodec  (15198): codec does not support config operating rate (err -2147483648)
D/AudioTrack(15198): getTimestamp_l(28): device stall time corrected using current time 31622562992700
I/ExoPlayerImpl(15198): Release 840da8c [ExoPlayerLib/2.11.1] [generic_x86_arm, sdk_gphone_x86, Google, 29] [goog.exo.core]
D/AndroidRuntime(15198): Shutting down VM
E/AndroidRuntime(15198): FATAL EXCEPTION: main
E/AndroidRuntime(15198): Process: com.cook.maker, PID: 15198
E/AndroidRuntime(15198): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(15198): 	at com.ryanheise.just_audio.AudioPlayer.broadcastPlaybackEvent(AudioPlayer.java:229)
E/AndroidRuntime(15198): 	at com.ryanheise.just_audio.AudioPlayer.access$300(AudioPlayer.java:32)
E/AndroidRuntime(15198): 	at com.ryanheise.just_audio.AudioPlayer$1.run(AudioPlayer.java:65)
E/AndroidRuntime(15198): 	at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime(15198): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15198): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(15198): 	at android.app.ActivityThread.main(ActivityThread.java:7506)
E/AndroidRuntime(15198): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15198): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(15198): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
I/Process (15198): Sending signal. PID: 15198 SIG: 9

**Comment by chadthecoder** [comment] 2020-04-03 18:03
`I/ACodec  ( 9358): codec does not support config priority (err -2147483648)` seems to be coming from something in the setUrl() function.

from:
```
    print('am here');
    await _player.setUrl('https://mcadamschad.com/assets/bible/Psalm3-1.mp3');
    print('middle time');
    _player.play();
    print('now here');
```

got:
```
I/flutter ( 9358): am here
W/XingSeeker( 9358): XING data size mismatch: 366794, 366666
I/OMXClient( 9358): IOmx service obtained
I/ACodec  ( 9358): codec does not support config priority (err -2147483648)
I/flutter ( 9358): middle time
I/flutter ( 9358): now here
```

**Comment by chadthecoder** [comment] 2020-04-03 18:04
`I/ACodec  ( 9358): codec does not support config priority (err -2147483648)` seems to be coming from something in the setUrl() function.

from:
```
    print('am here');
    await _player.setUrl(url);
    print('middle time');
    _player.play();
    print('now here');
```

got:
```
I/flutter ( 9358): am here
W/XingSeeker( 9358): XING data size mismatch: 366794, 366666
I/OMXClient( 9358): IOmx service obtained
I/ACodec  ( 9358): codec does not support config priority (err -2147483648)
I/flutter ( 9358): middle time
I/flutter ( 9358): now here
```

**Comment by ryanheise** [comment] 2020-04-04 01:42
@RaistlinTAO can you confirm that you are using the latest release of the plugin?

**Comment by duncan-iaria** [comment] 2020-04-04 03:38
I'm seeing the same behavior on the latest version of the plugin. Works fine on iOS, setUrl on android gives me the error and for me it results in a hard crash.

**Comment by ryanheise** [comment] 2020-04-04 06:41
I believe this is a Duplicate of #57 . Please try the suggestion in that issue and let me know if it corrects the issue for you. If so, I will include the fix in the next release.

**Closed by ryanheise** 2020-04-04 06:41 UTC

**Comment by duncan-iaria** [comment] 2020-04-04 14:57
> I believe this is a Duplicate of #57 . Please try the suggestion in that issue and let me know if it corrects the issue for you. If so, I will include the fix in the next release.

This seems to have resolved the issue for me. Thank you! Btw that other issue mentions using audio_service as well - in my case I was only using just_audio, not sure if that is helpful information or not but I thought I'd throw it out there.
