### ISSUE TITLE
Space in asset names causes error

### ISSUE THREAD

**Issue by sigjak** [ryanheise/just_audio#325] opened 2021-02-28 09:29 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
The documentation suggests that I can load an asset from any valid asset path, but it gives an error if the asset path contains a space. The documentation does not say say anything about spaces not being allowed. It seems the space is converted to %20 which may be causing the issue.
**Minimal reproduction project**

https://github.com/sigjak/music_player
**To Reproduce (i.e. user steps, not code)**

 AudioSource.uri(Uri.parse("asset:///audio/book/John William.mp3")),
**Error messages**

```
 An error occured Unable to load asset: audio/book/John%20William.mp3
```

**Expected behavior**
Expected to accept white space in asset names

**Screenshots**
NA

**Desktop (please complete the following information):**
Android
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
NA

**Flutter SDK version**
Flutter 1.22.6
insert output of "flutter doctor" here
```

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment] 2021-02-28 09:35
Hi @sigjak 

> **Minimal reproduction project**
> 
> The example

The example works perfectly and does not exhibit the error. While I could create my own minimal reproduction project, that would take more time and I am quite busy at the moment managing the migration to null safety and other critical bugs. If you can provide a minimal reproduction project, I will be able to tend to this more quickly, otherwise it will have to wait until after I complete the null safety migration.

I also note that you didn't bother filling in a lot of the other information that was requested. Can you please do this? You can edit your issue via the menu.

**Comment by sigjak** [comment] 2021-02-28 11:44
Hi and thanks for the reply.

 

The Example works fine and  there should not have been a reference to in the bug report. I will correct that and edit the report to include more info.

I have created a github with two branches, one working and the other one not working.

https://github.com/sigjak/music_player

The only difference is that the none working branch has a blank space in the asset name.

 

All the best

 

Sig

**Comment by ryanheise** [comment] 2021-02-28 12:57
This should be fixed in the latest commit to `master` - please let me know how it goes.

**Comment by ryanheise** [comment] 2021-03-01 04:25
Will release once you confirm it working.

**Comment by sigjak** [comment] 2021-03-01 09:15
How can I test it?

**Comment by ryanheise** [comment] 2021-03-01 09:22
You could either git clone this repository and temporarily point your just_audio dependency to this in your pubspec, or since pubspec supports git references, you could try this dependency:

```yaml
just_audio: 
    git:
      url: git://github.com/ryanheise/just_audio.git
      path: just_audio
```

The `path` is required since the `just_audio` plugin is a subdirectory within the repository. Once the next version is released, you can (should) change your dependency back to the hosted release.

**Comment by sigjak** [comment] 2021-03-01 09:43
Works fine!  Empty space no longer a problem.

 

Thank you!

**Comment by sigjak** [comment] 2021-03-02 09:20
fixed

**Closed** 2021-03-02 09:20 UTC
Labels: 3 testing, bug
