### ISSUE TITLE
Assetimages not working with just_audio_background notification.

### ISSUE THREAD

**Issue by Jens05** [ryanheise/just_audio#769] opened 2022-07-05 12:56 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Just_audio_background (possilby)

**Minimal reproduction project**
Provide a link here using one of two options:
1. Create an Audiosource with assetimage

**To Reproduce (i.e. user steps, not code)**
1. Create an Audiosource.uri()
2. Add the required elements
3. In the MediaItem tag, change arturi to Uri.parse(asset:///(asset image here))

**Error messages**

```
The following assertion was thrown resolving an image codec:
Unable to load asset: asset:///assets/gradient.png

When the exception was thrown, this was the stack: 
Issue when i put Uri.parse(asset:///assets/(image here)) directly in artUri
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:658:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "asset:///assets/gradient.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#e8b17(), name: "asset:///assets/gradient.png", scale: 1.0)

Issue when i put assets/(image here) in my artUri field: 
Error loading artUri: Invalid argument(s): No host specified in URI assets/images/bloemen_tuin.jpeg
I/flutter (22419): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:9)
I/flutter (22419): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2591:7)
I/flutter (22419): #2      IOClient.send (package:http/src/io_client.dart:35:38)
I/flutter (22419): #3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:35:44)
I/flutter (22419): #4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:121:24)
I/flutter (22419): #5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:103:28)
I/flutter (22419): <asynchronous suspension>
I/flutter (22419): #6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:71:7)
I/flutter (22419): <asynchronous suspension>

```

**Expected behavior**
I expect that i can add assetimage in my MediaItem's artUri as follows: Uri.parse(asset:///assets/(image here)) AND that the image shows in my notification centre of my phone.

**Screenshots**
NaN

**Desktop (please complete the following information):**
 - OS: [Windows, 11]
 - Browser [Not applicable]

**Smartphone (please complete the following information):**
 - Device: [Samsung S20 FE 5G & Iphone X]
 - OS: [Android 12, IOS 15.x]

**Flutter SDK version**
">=2.17.1 <3.0.0"

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22000.739], locale nl-NL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

**Additional context**

**Comment by ryanheise** [comment] 2022-07-05 13:09
Closing as an invalid bug report, it does not follow the instructions. However, this is NOT a bug anyway because this feature isn't claimed to be supported. If you want that feature, you need to suggest it as an improvement.

**Closed as completed by ryanheise** 2022-07-05 13:09 UTC
Labels: bug, 1 backlog
