### ISSUE TITLE
`stop` should allow to not seek to the beginning

### ISSUE THREAD

**Issue by nt4f04uNd** [ryanheise/just_audio#366] opened 2021-04-03 16:36 UTC
**Is your feature request related to a problem? Please describe.**
i want to stop the player, but keep in my ui the current position. for some reason stop seeks to the beginning of the audio and there's no way to change this

**Describe the solution you'd like**
allow to not seek at the beginning and probably make this default

**Describe alternatives you've considered**
i will use `pause` for now, but this, as far as i can understand, will keep some resourses intact, which i would like to release

**Additional context**
no

**Comment by ryanheise** [comment] 2021-04-04 01:55
I think when I implemented 0.6.x, which changes the semantics of `stop` to release resources, my goal was to make it work as you described (so it would remember the current position) but I didn't quite achieve that. There is code there to try to remember the position but it needs more work.

By the way, `stop` is completely invented by just_audio and has now exact counterpart in the native libraries. I'm not sure if there is an expected behaviour for it, but in practice I think it's more useful to remember the current position. If people want different behaviours, we may need an optional argument to `stop()` to control that behaviour.

**Comment by yringler** [comment] 2021-07-06 00:57
I see an inconsistent behaviour, replicated in the just_audio example (I changed the pause button to call stop instead).
1. play
2. seek to middle
3. listen for a second
4. stop
5. play again
6. Note that it continues from where you left off, but the position slider is at start and isn't updating
7. stop and play again
8. Note that now it isn't continuing, it's restarting from start of audio

It's not a bad bug as far as bugs go - there's an easy workaround to keep track of position (which I'm doing anyway) and explicitly seek (hopefully it'll be that simple), but probably something that should be ironed out.
Maybe by me. I should really try hacking at it a little bit, at least on the android side. But...

**Comment by ryanheise** [comment] 2021-07-23 07:53
Sorry for the delay on this one, I've now fixed this on the `fix/stop_position` branch and have so far tested it on Android, iOS and macOS. It will now preserve the position after stop/play which was the intended behaviour initially.

I still need to test web, and I also want to ensure the current index is preserved.

**Comment by ryanheise** [comment] 2021-07-24 14:06
The latest commits should now fix this on all platforms (although I've broken the unit tests for now - will have to fix that when I get a chance.)

**Comment by ryanheise** [comment] 2021-07-28 02:41
Unit tests should be fixed, although I had to touch the tricky code in `_setPlatformActive` which I dread doing (definitely should rework this to be less tricky at some point), so there's a risk of some new bugs cropping up, but at least all unit tests are now passing.

**Comment by ryanheise** [comment] 2021-07-28 05:36
The fix is now published in 0.9.4. Till the next time we meet, `_setPlatformActive`...

**Closed by ryanheise** 2021-07-28 05:36 UTC
Labels: 3 testing, enhancement
