### ISSUE TITLE
Listen for each audio item end event of a playlist

### ISSUE THREAD

**Issue by marcqtan** [ryanheise/just_audio#475] opened 2021-08-04 09:51 UTC
**To which pages does your suggestion apply?**
[https://github.com/ryanheise/just_audio/blob/master/just_audio/README.md](https://github.com/ryanheise/just_audio/blob/master/just_audio/README.md
)
**Quote the sentences(s) from the documentation to be improved (if any)**

> Insert here. (Skip if you are proposing an entirely new section.)

**Describe your suggestion**

I was reading the readMe documentation and I can't seem to find a way on how to listen for playback end of an audio item of a playlist. 

I've tried the `player.playerStateStream` and `ProcessingState.completed` but it will only fire when the last audio item of a playlist finished playing.

For example:
I have 3 audio items and I'm using ConcatenatingAudioSource to create 1 playlist which contains this 3 audio items.
I want to know/listen when the audio item ends. (e.g. Audio 1 completes, Audio2 completes etc.). 

Right now, ProcessingState.completed of playerStateStream will only fire when Audio 3 completes.. Is there a stream that can handle this? Thanks!

The reason is, I want to do something with the current track when it ends, before playing the next track.

**Comment by ryanheise** [comment] 2021-08-04 12:51
Duplicate of #174

**Closed by ryanheise** 2021-08-04 12:51 UTC
Labels: 1 backlog, documentation
