### ISSUE TITLE
Using JustAudio in a PageViewer

### ISSUE THREAD

**Issue by meghead** [ryanheise/just_audio#423] opened 2021-06-11 09:48 UTC
**Which API doesn't behave as documented, and how does it misbehave?**

When using Just Audio in a PageViewer, each player behaves as if it were the same player instead of separate players. IE: After play is finished and when swiping to the next file, the cursor of the next and all subsequently swiped players is in the same position. At that point, all instances remain in pause mode and cannot be restarted. Or if you partially play the file, pause, then swipe, the cursor of the next player is in the same position as the first. 

**Minimal reproduction project**

The example

**To Reproduce (i.e. user steps, not code)**

Create a `PageViewer` with a list of URLs containing `JustPlayer(url: kUrl)))` in a container. 
Build the PageViewer.
Play the first instance to the end. 
Swipe to the next page.

**Error messages**

No error messages. But the cursor and state of the next and all subsequent players are the same as the very first.

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.

N/A


**Expected behavior**

I expected that when I swiped to a new page, the cursor of the next player would be at the start point.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

 - Android studio on Windows 10

**Smartphone (please complete the following information):**

 - Device: Android 11 on Pixel 2 XL

**Flutter SDK version**

C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 2.2.0, on Microsoft Windows [Version 10.0.19042.1052], locale en-GB)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Pixel 2 XL (mobile) • 711KPAE0893480 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!
`

**Additional context**
I'm using a PreloadPageView.builder

**Comment by ryanheise** [comment] 2021-06-11 12:39
This is likely a bug in your app rather than a bug in the plugin, but if you have narrowed it down to this plugin, you will need to provide a reproduction project and reproduction steps (user steps NOT code).

**Comment by meghead** [comment] 2021-06-11 19:35
I was trying to use Just Audio as a drop-in replacement to the `Audioplayers` plugin - which was working correctly. When you say "reproduction project" do you mean I should fork the project and then set up a PageViewer with JustAudio in it?

**Comment by ryanheise** [comment] 2021-06-12 01:04
Have you read CONTRIBUTING.md? It uses fairly ubiquitous terminology in software development, but let me know if you disagree and I'll consider improving it.

**Comment by meghead** [comment] 2021-06-12 06:51
OK. I've forked your repository and here's the example PageViewer where JustPlayer does not scroll;

https://github.com/meghead/just_audio/blob/master/just_audio/example/lib/main.dart

**Comment by ryanheise** [comment] 2021-06-12 06:57
Does it compile? Looks like it probably won't.

**Comment by meghead** [comment] 2021-06-12 20:33
It compiles ok within the context of my program. The first page in the Pageviewer plays ok. It's just when you swipe that JustPlayer acts up on subsequent pages.  Why do you think there'd be trouble compiling?

**Comment by ryanheise** [comment] 2021-06-13 00:45
Have you actually verified that this project compiles before asking me to try it?

**Comment by ryanheise** [comment] 2021-06-13 01:13
I have a time window to test this now. Will let you know how I go. (Hopefully it compiles after my note above.)

**Comment by ryanheise** [comment] 2021-06-13 01:17
I guess even after asking you to check that it compiles, you still gave me something that doesn't compile:

```
$ flutter analyze
Analyzing example...                                                    

  error • Target of URI doesn't exist: '../builders/JustPlayer.dart' • lib/main.dart:3:8 • uri_does_not_exist
   info • Private field could be final • lib/main.dart:13:18 • prefer_final_fields
  error • The argument type 'dynamic' can't be assigned to the parameter type 'Widget?' • lib/main.dart:33:17 •
         argument_type_not_assignable
  error • The method 'JustPlayer' isn't defined for the type '_PageViewDemoState' • lib/main.dart:33:24 • undefined_method
  error • The argument type 'dynamic' can't be assigned to the parameter type 'Widget?' • lib/main.dart:41:17 •
         argument_type_not_assignable
  error • The method 'JustPlayer' isn't defined for the type '_PageViewDemoState' • lib/main.dart:41:24 • undefined_method
  error • The argument type 'dynamic' can't be assigned to the parameter type 'Widget?' • lib/main.dart:49:17 •
         argument_type_not_assignable
  error • The method 'JustPlayer' isn't defined for the type '_PageViewDemoState' • lib/main.dart:49:24 • undefined_method
   info • Unused import: 'package:just_audio_example/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The argument type 'dynamic' can't be assigned to the parameter type 'Widget' • test/widget_test.dart:16:29 •
         argument_type_not_assignable
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

11 issues found. (ran in 1.6s)
```

I will close this issue, I have limited time to investigate a large number of submitted issues and although I go to great lengths to write up formal contribution and bug submission instructions designed to make this feat possible, when people don't equally put in the effort to follow those instructions I don't feel inclined to spend time on that.

I have many other issues that _have_ been properly submitted and my priority will be with those.

**Closed by ryanheise** 2021-06-13 01:17 UTC
Labels: 1 backlog, bug

**Comment by ryanheise** [comment] 2021-06-18 01:06
Hi @meghead I saw your question on StackOverflow. You said in StackOverflow that you were confused about what I meant when I asked you if your project compiled, but let's say that should be understood as a prerequisite for submitting a bug report. If you write code under the section that says "NOT code", and then you later supply a project that doesn't compile (and therefore I can't even run and test), you probably need to think more about these things before submitting another bug report. If you can submit a valid bug report, then yes by all means please do. Make sure that you answer each question in the bug report correctly according to its instructions. If you find a problem with the instructions, please make a suggestion via a documentation request instead of a bug report so that I can improve the instructions.
