### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by KristijanZic** [ryanheise/just_audio#1165] opened 2024-01-12 14:04 UTC
**Is your feature request related to a problem? Please describe.**
The package doesn't have Linux support.

**Describe the solution you'd like**
For a package to support Linux.

**Describe alternatives you've considered**
audioplayers - good but lacks features of just_audio

**Additional context**
It would be amazing if this package offered Linux support as rn I have to use a different dependency for Linux that doesn't offer the same feature set.

**Comment by ryanheise** [comment] 2024-01-12 14:16
Duplicate of #1164

**Closed as completed by ryanheise** 2024-01-12 14:16 UTC
Labels: enhancement, 1 backlog
