### ISSUE TITLE
IOS Open errors (file path) wont play mp3,wav,m4a... Works on Android

### ISSUE THREAD

**Issue by cyberpwnn** [ryanheise/just_audio#287] opened 2021-01-21 21:36 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Playing Audio

**Minimal reproduction project**
I do not have a min reproducible project to provide, however I will test that... though with the same platform issues on both projects I doubt anything will come of it.

**To Reproduce (i.e. user steps, not code)**
1. Play Audio
2. Observe it not working on ios

**Error messages**

```
021-01-21 15:59:33.668542-0500 Runner[392:12915] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: (-11828) Cannot Open
#0      AudioPlayer._load (package:just_audio/just_audio.dart:654)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.<anonymous closure> (package:just_audio/just_audio.dart:1023)
<asynchronous suspension>
```

**Expected behavior**
Audio playing on ios

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Tested on IOS devices
* Iphone 12 Mini (latest IOS)
* IPad / IPod Touch (random versions of ios, all above ios 10)
* Mac Mini (M1 simulated IOS)

**Flutter SDK version**
```
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (7 days ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
cyberpwn@Daniels-Mac-mini ios % flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Users/cyberpwn/Documents/development/flutter
    • Framework revision 5d36f2e7f5 (7 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cyberpwn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • cyberpwn’s iPhone (mobile) • 00008101-001818940228001E • ios            • iOS 14.3
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

**Additional context**
I'm not sure what codecs IOS supports, but I've tried mp3 and wav. Was pretty sure mp3 was supported. Is there a list of supported formats? Android is working fine (as most audio plugins do)

But my guess is IOS is having trouble opening files? I am using playFilePath, not URLs. I will test with urls instead. 

 Thanks!

**Comment by ryanheise** [comment] 2021-01-21 23:53
> I do not have a min reproducible project ... I doubt anything will come of it.

But nothing will come of this bug report either if I can't reproduce it.

**Comment by cyberpwnn** [comment] 2021-01-22 02:48
I'll work on getting a min repro up, but if It ends up working, would you have any idea of why this is happening? Why the same file plays on android but not IOS? It's an mp3.

**Comment by ryanheise** [comment] 2021-01-22 02:50
I have no idea. I can start getting some idea of it once I can reproduce it, so let's focus on that first.

**Comment by cyberpwnn** [comment] 2021-01-22 03:01
I have a project, testing it on ios (android worked as assumed).

**Comment by cyberpwnn** [comment] 2021-01-22 03:12
Ok yeah, Still fails with 
```
2021-01-21 22:10:18.817842-0500 Runner[673:94829] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: (-11828) Cannot Open
#0      AudioPlayer._load (package:just_audio/just_audio.dart:654:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.<anonymous closure> (package:just_audio/just_audio.dart:1023:28)
<asynchronous suspension>
```

https://github.com/cyberpwnn/justaudiobrokenonios

This works on Android, Fails to play on ios. I'm using a URL (in source) which is simply an mp3 file. I will test files too, but I imagine the same exact thing will happen.

**Comment by ryanheise** [comment] 2021-01-22 03:22
Thanks for providing that, I will check after lunch. iOS has some requirements for server headers but the fact that it gives the same error for local files suggests that iOS doesn't like the file contents itself, whereas it does like the file contents in my example, which I assume works for you.

**Comment by cyberpwnn** [comment] 2021-01-22 03:23
I did not get a chance to test those. And I can add the local-file test into the example if you like.

**Comment by ryanheise** [comment] 2021-01-22 03:35
You did tell me that it was the same for files, right? If that information was incorrect, then it might actually be a server headers problem. The only weird thing about the headers that I can see is the content type is `octet-stream` which should be `audio/....`.

**Comment by cyberpwnn** [comment] 2021-01-22 06:50
That file is hosted, but the same file is local, and still fails to play. I.E. in my real project, I download it (cache) as a file and play from the local file, still has the same problem. Even if the url has bad headers, it should not be the problem. By downloading that file and simply renaming it to an mp3 file, it plays just fine. But again even with downloading the file, it wont play same exact error.

https://icarus-cdn.nyc3.cdn.digitaloceanspaces.com/resources/_6/7b/e2EC/D9C94F85aca9bce1/A75e2CfBd5D7/48B53b83de64/9FB07A4b936a69f4/de6Fab25/e01a1388FC970Ac7

I will update the example so that it downloads the file, then plays the file instead.

**Comment by cyberpwnn** [comment] 2021-01-22 07:15
Ok, I have updated the example app. You can now test both playing from the same url above, or test playing the file (simply downloads the file once, then plays the file locally). As all the previous tests, It works like a charm on android, but has the same error on IOS, no dice.

**Comment by ryanheise** [comment] 2021-01-22 08:23
In the case of the file, it works after giving the filename a `.mp3` extension. I assume that the URL will also work after you configure your server to produce the correct content-type header.

**Comment by cyberpwnn** [comment] 2021-01-22 20:17
Is there any way around that? I.e. such that it works like android does? And if for example it was another format, I assume it needs to be that format's extension also?

**Comment by cyberpwnn** [comment] 2021-01-22 21:33
I came up with a solution for now, using flutter_ffmpeg to determine the format (and i can convert wav files into mp3 for ios too)

**Comment by ryanheise** [comment] 2021-01-24 01:49
Good to know you worked out some solution. I'll close this issue, but have opened #289 to add this to the documentation.

**Closed by ryanheise** 2021-01-24 01:49 UTC
Labels: 1 backlog, bug

**Comment by gangadharashettypj** [comment] 2021-05-31 09:34
Hi,
can i know how to fix this error?
