### ISSUE TITLE
Queue management in just_audio

### ISSUE THREAD

**Issue by rohansohonee** [ryanheise/just_audio#36] opened 2020-02-05 13:15 UTC
Hi @ryanheise 

We must rely on using [Playlists](https://exoplayer.dev/playlists.html) (``ExoPlayer Android``) and [AVQueuePlayer](https://developer.apple.com/documentation/avfoundation/avqueueplayer) (``AVPlayer iOS``).

Migrating to this approach will enable easy and straightforward approach for users to handle queue. It will also enable audio looping/repeat mode to get implemented with ease.

And lastly, it should make it way more easier to handle all the exception cases (``bufferring/connecting states``).

What are your thought's?

**Comment by ryanheise** [comment] 2020-02-05 13:34
Sounds good, and I'd like to eventually support this under a broader `setMediaSource` API similar to ExoPlayer. It is not right now the highest priority for me though as I need to fix #21 and then for another project I will be working on #15 .

**Comment by ryanheise** [comment] 2020-07-27 18:47
This is now implemented on the media-source branch. See #131 for details.

I will close this as a duplicate.

**Comment by ryanheise** [comment] 2020-07-27 18:48
Duplicate of #131

**Closed by ryanheise** 2020-07-27 18:48 UTC
Labels: 1 backlog, 2 fixing, enhancement
