### ISSUE TITLE
FormatException: Invalid HTTP header

### ISSUE THREAD

**Issue by waplay** [ryanheise/just_audio#765] opened 2022-06-25 08:34 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio: ^0.9.25

Stations using special characters in their headers throw an unhandled exception. This happens when there is a user agent. If you remove the user agent everything works as expected.

**Minimal reproduction project**
[Modified example_radio.dart](https://github.com/waplay/just_audio/blob/minor/just_audio/example/lib/example_radio.dart)

**To Reproduce (i.e. user steps, not code)**
1. Run code
2. See error

**Error messages**

```
E/flutter (24601): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Invalid HTTP header field value: "Le son club des annÃ©es 80" (at character 20)
E/flutter (24601): Le son club des annÃ©es 80
E/flutter (24601):                    ^
E/flutter (24601):
E/flutter (24601): #0      _HttpHeaders._validateValue (dart:_http/http_headers.dart:664:9)
E/flutter (24601): #1      _HttpHeaders._addAll (dart:_http/http_headers.dart:71:20)
E/flutter (24601): #2      _HttpHeaders.set (dart:_http/http_headers.dart:92:5)
E/flutter (24601): #3      _proxyHandlerForUri.handler.<anonymous closure> package:just_audio/just_audio.dart:3096
E/flutter (24601): #4      _HttpHeaders.forEach.<anonymous closure> (dart:_http/http_headers.dart:122:13)
E/flutter (24601): #5      _HashMap.forEach (dart:collection-patch/collection_patch.dart:164:15)
E/flutter (24601): #6      _HttpHeaders.forEach (dart:_http/http_headers.dart:120:14)
E/flutter (24601): #7      _proxyHandlerForUri.handler package:just_audio/just_audio.dart:3095
```

**Expected behavior**
Radio stream should play

**Screenshots**
No screenshots needed

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 5.4.0-120-generic
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: Android 12

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.0.0, on Linux Mint 20.2 5.4.0-120-generic, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Additional context**
-/-

**Comment by ryanheise** [comment] 2022-06-25 09:46
Thanks @waplay , I can reproduce it with your project and will investigate.

**Comment by ryanheise** [comment] 2022-06-25 10:30
It turns out that servers should not be placing non-ASCII characters in headers, and Dart goes one step further by not allowing it in the dart:io library. See:

https://github.com/dart-lang/http/issues/227

I feel Dart's taken a stance that's rather strict, but at the same time, I think it would be fairly difficult to write code to correctly guess which character encoding the `icy-description` header is in.

One simple thing I could do is to filter out any non-ascii character that appears in any header that passes through the proxy which would get rid of the error, but would also mean that if your app uses the `icy-description` header, it will be missing information. Another simple thing I could do is detect when any non-ascii character appears in a header and then re-encode that header using RFC 2047 as suggested [here](https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header) however that standard is actually not used by anyone in practice. So another simple alternative is if when such an invalid header appears, I can just re-encode it in hex with some identifiable prefix that clients will recognise and then decode. The last option which is a bit more difficult is for me to bypass Dart's HTTP implementation altogether and use socket communication directly.

But then your app will still need to make assumptions about what character encoding was used, if you try to use that header.

Do you have any thoughts on which solution you would prefer?

**Comment by waplay** [comment] 2022-06-25 10:46
@ryanheise I think now the solution would be №1 (to filter out any non-ascii character). My app does not use `icy-description`, and if someone needs it, he will still face this problem.
Thank you!

**Comment by ryanheise** [comment] 2022-06-25 10:46
Reading the ExoPlayer code, it looks like it ignores the `icy-description` header anyway, so perhaps it would be harmless if I just filtered out invalid characters.

**Comment by waplay** [comment] 2022-06-25 10:47
yes, I agree with you

**Comment by ryanheise** [comment] 2022-06-25 14:01
I have pushed a fix to the `fix/bad_headers` branch if you would like to test it.

**Comment by waplay** [comment] 2022-06-25 14:46
I just tested. Everything works as expected. Thank you for your hard work!

**Comment by ryanheise** [comment] 2022-06-26 07:38
Thanks for reporting! The fix has now been released on pub.dev so I'll close.

**Closed as completed by ryanheise** 2022-06-26 07:38 UTC
Labels: bug, 1 backlog
