### ISSUE TITLE
After dispose(), the audioSource is always null

### ISSUE THREAD

**Issue by gOzaru** [ryanheise/just_audio#491] opened 2021-08-24 10:55 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio: 0.9.5 and probably audio_service: ^0.18.0-beta.0

For example, I have 2 pages. 
One is the main page, and the other is detailSong page in full screen mode with close button. The main page has a playlist of music. If one of them is clicked, it will go to songDetail page, created AudioPlayer() instance and the previous list will be exported into ConcatenatingAudioSource(). 

The `AudioPlayer.play()` will directly play the current index on songDetail page. When user click the next song in playback control, it plays very well. If user closes the songDetail page, it will call the `player.dispose()` method and switch back to main page. The problem is when user want to click the song in the main page again. It will direct to songDetail page, but it cannot play the current song as I figured out that the : `player.audioSource == null` 

The `AudioProcessingState.idle` is active.  

**Minimal reproduction project**
I don't know how to create a minimal reproduction project, but I will share the code snapshot. 
```
  Future<void> playSong() async {
    if (mediaItems.length > 0) {
      print("Page Manager => Current song: ${mediaItems[0].title}");
      await audioHandler.playMediaItem(mediaItems[0]);
      await audioHandler.play();
    }
  }
```
I overrided the play() function to figure out what is going on inside the AudioPlayer() after having `player.dispose()`. The code below is from document songDetail page.  
```
  @override
  Future<void> play() async {
    if (player.currentIndex == null) {
      print("AudioHandler => Index of current item is null");
    } else {
      if (player.audioSource != null) {
        try {
          player.play();
        } on PlayerInterruptedException catch (e) {
          print("Audio Handler => Error in player.play(): $e");
        }
      } else if (player.audioSource == null) {
        print("AudioHandler => The audioSource is null");
      }
    }
  }
```
This is the dispose() inside songDetail page:
```
  @override
  Future customAction(String name, [Map<String, dynamic>? extras]) async {
    if (name == "dispose") {
      print("AudioHandler => dispose()");
      await player.dispose();
      super.stop();
    }
  }
```
I declared the lazy singleton of page manager in initState() and dispose() inside songDetail page. I use GetIt package for this. 
```
  @override
  void initState() {
    super.initState();
    getIt<PageManager>().init();
  }

  @override
  void dispose() {
    getIt<PageManager>().dispose();
    super.dispose();
  }
```
**To Reproduce (i.e. user steps, not code)**
1. Click a song in music playlist in main page
2. Song is automatically played in next page (songDetail page)
3. If songDetail page is closed, the player() is disposed and goes to main page
4. Click the same song again in main page
5. The same song cannot be played

**Error messages**
The audioSource is null.

**Expected behavior**
When clicking the same song after exit from songDetail page, it should be played inside the songDetail page as all the instances are being recreated. Instead, it says that the audioSource is null. This is a very illogical thing. I check the current audioSource inside queue.value and it does exist. How come this happen? This is very confusing. Please, help. This maybe a bug. 
Thank you.   

**Desktop:**
 - OS: Windows 10 

**Smartphone:**
 - Device: Redmi 6A
 - OS: Android 9.0

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.59.1)    
[√] Connected device (3 available)
```

**Comment by ryanheise** [comment] 2021-08-24 11:43
In section 1 you are asked to explain how this is not behaving as documented, but in the documentation it says that you should only invoke `dispose()` once you are done with the player. Therefore, after calling `dispose()` you should not expect anything from the player. It should not be used anymore. As such, I am closing this as not a bug.

**Closed** 2021-08-24 11:43 UTC
Labels: bug, 1 backlog

**Comment by gOzaru** [comment] 2021-08-24 13:50
I see.. I just knew what that means. 
So we can only invoke dispose() once we want to quit the player. 
Okay, I understand now. 
Thank you very much for answering this. 
God bless you.
