### ISSUE TITLE
For IOS - resources are not being released for network play

### ISSUE THREAD

**Issue by fuzing** [ryanheise/just_audio#236] opened 2020-11-06 15:40 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
The dispose method for the audio player does not seem to be releasing resources on the native side.    Specifically, playing network based audio files results in buffers that do not seem to be being released/freed.

This results in a catastrophic memory leak that is causing IOS devices to crash, and for our apps to be rejected from the App Store.

Our audios are streamed from the internet and are between 20MB and 30MB in length (30 minute audios).   Users can select various audio stories and they tend to click between them to find stories that they like (hence we're consuming 20-30MB of memory on each user click).

Users (and now the app store) is complaining that they experience IOS crashes due to memory exhaustion.

**Minimal reproduction project**
https://github.com/fuzing/jaissue.git

**To Reproduce (i.e. user steps, not code)**
Run the app from xcode on a VM while looking at memory.   Click the '+' button to start the first file playing, then click '+' to move to subsequent files.   Memory will be consumed at a rate of about 20MB per play (the size of each file - they are all identical).

**Error messages**

```
App crashes as memory is exhausted.   For larger devices, memory is consumed at approximately a 1:1 ratio for the size of the network stream being ingested.   This memory is never released.
```

**Expected behavior**
Disposing a player should dispose of all resources.   From the dart code, it does look like efforts to clean up AudioSource is made from the player, however this does not appear to be being translated on the native side in IOS.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad Air (gen 1 and gen 2).... all VM's we have tried (numerous)
 - OS: IOS multiple/all versions

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

```

**Additional context**
N/A

**Comment by ryanheise** [comment] 2020-11-06 16:48
> App crashes as memory is exhausted.   For larger devices, memory is consumed at approximately a 1:1 ratio for the size of the network stream being ingested.   This memory is never released.

Thanks for reporting this and providing an easy way to reproduce it (this is also an unusually specific and helpful error message).

> **Expected behavior**
> Disposing a player should dispose of all resources. From the dart code, it does look like efforts to clean up AudioSource is made from the player, however this does not appear to be being translated on the native side in IOS.

Note that you don't need to dispose the player, you should be able to just load a new audio source into the existing player (or at least that's the intention). If this works as intended, it should also alleviate your memory issue.

Looking at the dispose code, I see some things I can try to force it to release the memory, so I'll do some experimentation.

**Comment by fuzing** [comment] 2020-11-06 18:45
No worries - and thanks Ryan

FYI - I did try using the strategy of holding a single player and then reusing without disposing because I figured that maybe a re .load may help   ....... alas - no joy!

I also tested over a range of VMs and a couple of devices - consistent.

Let me know when you see something so I can patch.

Be well, and thanks for your efforts.

**Comment by fuzing** [comment] 2020-11-06 19:12
Once this is sorted out, I don't whether it might be worth exposing a public .dispose() method on AudioSource objects.   It may be more trouble than it's worth (in terms of people inadvertently .disposing() while in use and those side-effects etc.), but perhaps something to think about.

Let me know if you'd like assistance with this (my Obj-C and/or Swift coding expertise is at the level of an infant [probably worse], but happy to do whatever I can).

**Comment by ryanheise** [comment] 2020-11-07 07:40
Hi @fuzing , can you try the latest version on git master? I haven't fully tested it, so I'll want to do some testing in conjunction with audio_service (modifying the memory management code always has the risk of introducing another bug).

> Once this is sorted out, I don't whether it might be worth exposing a public .dispose() method on AudioSource objects.

This is an area of the code I certainly should review at some point. There is currently a difference between the iOS and Android implementations where Android will cache the audio source instances indexed by an ID so that Dart code is able to identify a particular instance of an audio source and perhaps reuse it in two different places (within the same player), while iOS pretty much ignores this ID and will create a new audio source in each place it is used. The iOS implementation is actually simpler and I don't personally have a use case for reusing an audio source instance, but it's something I'll need to look at again down the road.

**Comment by fuzing** [comment] 2020-11-07 11:07
@ryanheise - we've done some testing - so far, so good.   We've put it through the paces on some VM's and several physical devices.   A little later we'll flog harder - but memory is definitely being released.

I can't thank you enough for getting onto this so quickly - it really means a lot.  Thank you!

Peter B

**Comment by fuzing** [comment] 2020-11-07 13:51
@ryanheise - we've hit it pretty hard and for our use case things look great (again - thank you).   One last favor - because I'm going to remain pointed at 'master'...... would you mind letting me know here just before you commit a new version so I can switch to it instead of remaining on 'master'.    Also, is there anything in development that's on master right now that you'd consider unstable/new/etc (aside from this fix) that would prevent me from considering 'master' the latest production build?

Thank you!

**Comment by ryanheise** [comment] 2020-11-07 14:21
No problem! I appreciate equally that you discovered and reported the issue, and tested the fix.

The only other change since the last release was to change the default parameter value for `useLazyPreparation` from false to true (this affects only Android, and only if you're using `ConcatenatingAudioSource`). So I wouldn't expect that to cause any issues, however, if you do point to `master` it would be best to point to this specific commit hash in case I add some unstable code after this.

I will let you know here once this fix is included in the next release. You may also be interested in subscribing to this [Atom feed](https://github.com/ryanheise/just_audio/releases.atom)) to be notified when new releases appear. My workflow isn't automated so there may be a delay of a minute or two after the GitHub release before I actually upload it to pub.dev.

**Comment by fuzing** [comment] 2020-11-07 14:34
Perfect - thank you.  And I'll subscribe to the feed.   I don't use Concat's (I do use looping though).    Everything seems to work fine...... I'm dying for you to implement true seamless/gapless on IOS (<---- I know..... how terrible of me - what a nag!)

**Comment by ryanheise** [comment] 2020-11-08 10:29
FYI, version 0.5.6 has now been released including this fix.

(Regarding the gapless feature on iOS for repeat mode, this is a bit tricky to implement, although possible. So it's not something I can do quickly, unfortunately.)

**Closed by ryanheise** 2020-11-08 10:29 UTC
Labels: 3 testing, bug
