### ISSUE TITLE
Source error: Loading finished before preparation is complete

### ISSUE THREAD

**Issue by taichanvn** [ryanheise/just_audio#92] opened 2020-05-12 10:40 UTC
These errors occur when playing [this audio](https://ia802702.us.archive.org/33/items/prideandprejudice_1005_librivox/prideandprejudice_01_austen.ogg):

```
E/ExoPlayerImplInternal(24663): Source error
E/ExoPlayerImplInternal(24663):   com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
E/ExoPlayerImplInternal(24663):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:236)
E/ExoPlayerImplInternal(24663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:619)
E/ExoPlayerImplInternal(24663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
E/ExoPlayerImplInternal(24663):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(24663):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(24663):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/AudioPlayer(24663): TYPE_SOURCE: Loading finished before preparation is complete.
I/flutter (24663): com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
```

This error can be reproduced using the example project, just change the audio url to the link above.

**Comment by ryanheise** [comment] 2020-05-25 02:16
There is an open issue with ExoPlayer regarding this: https://github.com/google/ExoPlayer/issues/7230

**Comment by chitgoks** [comment] 2020-12-18 12:25
im guessing this is out now?

**Comment by ryanheise** [comment] 2020-12-18 13:21
@chitgoks there's a good chance this is fixed in 0.6.0. If you test it, please let me know how it goes.

**Comment by chitgoks** [comment] 2020-12-18 15:32
sorry my bad. im in the wrong page. i was looking for the error message specifically but its from a different lib.

**Comment by ryanheise** [comment] 2020-12-19 02:29
No worries @chitgoks .Something good came of it.

@taichanvn I just tested this issue with the latest version of just_audio, and the issue is now fixed! Hence, I'll close the issue ;-)

**Closed by ryanheise** 2020-12-19 02:29 UTC
Labels: 1 backlog, bug
