### ISSUE TITLE
Support HLS on web

### ISSUE THREAD

**Issue by almogdadjabir** [ryanheise/just_audio#1250] opened 2024-05-30 07:29 UTC
**Is your feature request related to a problem? Please describe.**
I have a Flutter app that works fine on all platforms except for the web. The HLS streaming is not working.

**Describe the solution you'd like**

I would like the HLS streaming to function correctly on the web platform in my Flutter app. Specifically, I need a solution that ensures seamless streaming across all supported platforms, including the web.

**Describe alternatives you've considered**

I have considered using different streaming protocols or third-party libraries to handle HLS streaming on the web. However, these alternatives may introduce compatibility issues or additional complexity.

**Additional context**

My app streams HLS content without issues on mobile and desktop platforms, but the web implementation fails to play the streams. Any guidance on resolving this issue or recommended libraries for web compatibility would be helpful.

**Comment by ryanheise** [comment] 2024-05-30 07:32
Duplicate of #242

**Closed as completed by ryanheise** 2024-05-30 07:32 UTC
Labels: enhancement, 1 backlog
