### ISSUE TITLE
With Header weird behavior

### ISSUE THREAD

**Issue by naguchennai** [ryanheise/just_audio#114] opened 2020-06-18 11:59 UTC
**Describe the bug**
I have two shoutcast server: shout1 and shout2
i used with custum useragent

`   Map<String,String> header = {'user-agent' : 'test'};
   await _audioPlayer.setUrl(mediaItem.id, headers: header);`

When start play in shout1 server its showing 3 playing instance in my single ip..
then i go ti next song its from shout2.. now here also showing 3 playing instance in the same ip..
weird thing is now i check old shout1 ( still playing from shout2 only) here also still showing that 3 playing instant in the same ip .. its not stopped old server
totally 6 playing instance.. but i heard one song from second shout2 only

Every thing working fine if i remove header

**Minimal reproduction project**
n/a

**To Reproduce**

**Error messages**

**Expected behavior**
If i change song in queue, previous audio server must disconnect. without "header" its working fine

**Screenshots**
server1
![1](https://user-images.githubusercontent.com/1379778/85198318-6772b300-b305-11ea-900e-89fc3ddc81f5.png)
server2
![2](https://user-images.githubusercontent.com/1379778/85198320-693c7680-b305-11ea-8ae9-5fd5611ce713.png)
server3
![3](https://user-images.githubusercontent.com/1379778/85198323-6b063a00-b305-11ea-8b3a-17cffc039c9b.png)

**Desktop (please complete the following information):**
 - OS: windows

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: v10

 **Flutter SDK version**

`	Flutter 1.20.0-0.0.pre • channel dev • https://github.com/flutter/flutter.git
	Framework • revision d9653445f4 (10 days ago) • 2020-06-09 18:43:03 -0400
	Engine • revision e8c13aa012
	Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)`

insert output of "flutter doctor" here
     `	[√] Flutter (Channel dev, 1.20.0-0.0.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)

	[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
	[√] Android Studio (version 4.0)
	[√] Connected device (1 available)
	• No issues found!`
**Additional context**

**Comment by ryanheise** [comment] 2020-06-18 16:48
Hi @naguchennai , I would like to investigate this bug, but please complete all sections of the bug report template as per the instructions (I understand that English is not your first language, although I would suggest using Google Translate to help you to follow the instructions).

**Comment by naguchennai** [comment] 2020-06-19 18:22
any update? i think proxy not stoped when changing next url list..

**Comment by ryanheise** [comment] 2020-06-20 02:13
You haven't completed the bug report as I instructed, so no update until you do that. When you filed your bug report, you deleted all of the sections I need even though the instructions said please do not delete those sections. Until you provide the needed information, unfortunately I can't process your bug report.

**Comment by naguchennai** [comment] 2020-06-20 05:29
i edited something ... i dont know how can i explain ... i thing u understand

**Comment by ryanheise** [comment] 2020-06-20 06:35
@naguchennai I'm sorry but you are still missing critical sections of the bug report.

Please go to the original issue template and copy everything back into your issue, or if you find that too difficult, you may instead close this issue and start a new issue where you will be able to see the instructions and all of the required sections still intact (but please don't delete them this time, and make sure you follow the instructions). Thanks.

**Comment by naguchennai** [comment] 2020-06-20 13:47
now its  updated.. pls try to pix it

**Comment by ryanheise** [comment] 2020-06-20 14:37
> **Minimal reproduction project**
> n/a
> 
> **To Reproduce**
> 

I can't reproduce the bug without a reproduction project and steps to reproduce.

This is the 5th time I've asked, and I do not intend going for a 6th, so please help me to help you.

**Comment by naguchennai** [comment] 2020-06-21 07:33
lol..... still u not understand? you know what u did? i dont want speak more here  contact me live4uin@gmail.com.  Just watch this video .. dont skip..  contact me i will write what already happening..  because of your code dont skip
https://www.youtube.com/watch?v=tp_4VY3LC5E&feature=youtu.be

**dont skip**

**Comment by naguchennai** [comment] 2020-06-21 07:36
delete above comments after you reed.. you don good job .... thank you.. i am also try to using your code...

**Comment by ryanheise** [comment] 2020-06-21 08:01
> lol..... still u not understand? you know what u did? i dont want speak more here contact me [live4uin@gmail.com](mailto:live4uin@gmail.com). Just watch this video .. dont skip.. contact me i will write what already happening.. because of your code dont skip
> https://www.youtube.com/watch?v=tp_4VY3LC5E&feature=youtu.be
> 
> **dont skip**

@naguchennai I'm sorry but I have given you my instructions from the start, and they were quite clear:

```
        PLEASE READ CAREFULLY!





        FOR YOUR BUG REPORT TO BE PROCESSED, YOU WILL NEED
        TO FILL IN ALL SECTIONS BELOW. DON'T DELETE THE HEADINGS.
```

It was not a great start that you deleted all sections of the bug report and left out virtually all of the information I need to proceed. In total, you have been asked 5 times to please complete the bug report, but you seem to be uninterested in cooperating.

Please understand that this is an open source project and it is made possible only by volunteer efforts and cooperation of the community. It is NOT an arrangement where you just expect that I fix your bug and expect me to do all of the work for you. If you are unwilling to help make it easier for me to investigate the bug by providing the reproduction project, then I am not motivated to help you. Open source does not happen without cooperation.

I do not have time to watch your video if it isn't accompanied by a reproduction project and I do not have time to continue repeatedly asking you for a valid bug report. Therefore, I will close and lock this issue.

My hope is that someone else encounters the same bug, and that they are a little more cooperative than you have been, and actually help me to investigate it rather than expect me to fix it with my hands tied.

**Closed by ryanheise** 2020-06-21 08:01 UTC
Labels: 1 backlog, bug
