### ISSUE TITLE
SHOUTcast Stream

### ISSUE THREAD

**Issue by eduardocm2002** [ryanheise/just_audio#67] opened 2020-04-05 05:34 UTC
Hello, there is no support for SHOUTcast Stream
for example http://192.99.0.170:5162/stream

**Comment by ryanheise** [comment] 2020-04-05 08:28
Looks like there is an extension for it:

https://github.com/slowtick/exoplayer-shoutcast

Will need to investigate the best way to go about adding on the various ExoPlayer extensions, since there are several of these that we want to support.

**Comment by Jei** [comment] 2020-04-21 08:44
The Android version already reproduces Shoutcast streams, since ExoPlayer recently added support for them without having to add an extension. I'm developing [an application](https://github.com/Jei/tormentedplayer/tree/develop) that plays the stream provided by https://tormentedradio.com/, but I've just used it to listen to the stream mentioned by @eduardocm2002 and it seems to be working.

**Comment by ryanheise** [comment] 2020-04-21 12:44
@Jei do you mean this works for you with the current version of ExoPlayer included in `just_audio` or are you suggesting it can be fixed by upgrading the dependency?

**Comment by ryanheise** [comment] 2020-04-21 12:46
Looks like #78 includes updated dependencies, so hopefully that helps this issue also.

**Comment by ryanheise** [comment] 2020-04-21 13:35
I've merged #78 and added a stub iOS implementation.

With the upgraded ExoPlayer dependencies, let me know if that also fixes this issue.

**Comment by Jei** [comment] 2020-04-21 14:33
> @Jei do you mean this works for you with the current version of ExoPlayer included in `just_audio` or are you suggesting it can be fixed by upgrading the dependency?

I've been using this plugin to play my stream before starting working on #78, which was just to retrieve the stream's metadata. I've updated the version of ExoPlayer because the new version (2.11.4) included [support for non-UTF-8 metadata](https://github.com/google/ExoPlayer/issues/6753), which seems important when working with streams with international content.
To be honest, one of the reasons I've been using just_audio for my personal project is that it could play the Shoutcast stream I mentioned earlier. 😅
I don't know about the iOS version though.

**Comment by ryanheise** [comment] 2020-04-21 15:13
Ah, I see. I'll assume this issue can be closed now, and thanks again for contributing the earlier PR.

**Closed by ryanheise** 2020-04-21 15:13 UTC
Labels: 3 testing, enhancement
