### ISSUE TITLE
iOS bug: No sound when replaying frequently and continuously.

### ISSUE THREAD

**Issue by john990** [ryanheise/just_audio#808] opened 2022-08-31 04:47 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
https://github.com/john990/just_audio

**To Reproduce (i.e. user steps, not code)**
1. Go to main page
2. Play audio every 500 milliseconds.
3. First time sound is normal, then sound is very low, even sometimes there is no sound.

**Error messages**

```
No error message
```

**Expected behavior**
Play audio normally.

**Screenshots**
Here is about change code
![image](https://user-images.githubusercontent.com/5292685/187593961-76a885ee-68f5-477e-a1b4-5eba5b28fdf6.png)

**Smartphone (please complete the following information):**
 - Device: [iPhoneX]
 - OS: [e.g. iOS 15.6]

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.66.0)
[✓] Connected device (4 available)
```

**Additional context**
We want to make an app about a clock that needs to play a tick every 200-500 seconds, and then find that it only plays normally the first time, tested fine on Android, but has this problem on iOS. 

Thank you very much.

**Comment by john990** [comment] 2022-09-07 23:10
Does anyone have any solution?

**Comment by ryanheise** [comment] 2022-09-08 01:19
I notice in your code that you execute your code every 500ms regardless of whether the previous cycle has finished. Couldn't that be the reason, and can you try doing this in an await for loop instead of a timer?

**Comment by john990** [comment] 2022-09-08 02:07
Hello, how do I start over without finishing the playback?
like this:
```dart
player.seek(Duration.zero);
player.play();
```

Because our function is that the speed of the ticking sound can be adjusted from 10 times per second to once per second. If you wait for the playback to end and start again, the sound frequency will be wrong. Do we need to prepare 10 AudioPlayer?

**Comment by john990** [comment] 2022-09-08 02:08
> I notice in your code that you execute your code every 500ms regardless of whether the previous cycle has finished. Couldn't that be the reason, and can you try doing this in an await for loop instead of a timer?

Hello, how do I start over without finishing the playback?
like this:
```dart
player.seek(Duration.zero);
player.play();
```

Because our function is that the speed of the ticking sound can be adjusted from 10 times per second to once per second. If you wait for the playback to end and start again, the sound frequency will be wrong. Do we need to prepare 10 AudioPlayer?

**Comment by ryanheise** [comment] 2022-09-08 02:13
First, can you let me know how my suggestion of the await for loop goes?

**Comment by john990** [comment] 2022-09-08 02:42
> First, can you let me know how my suggestion of the await for loop goes?

It doesn't work because our app function is to play every 100ms and the audio is longer than 100ms, so await doesn't suffice.
Here's what we do now:
```dart
Timer.periodic(const Duration(milliseconds: 100), (timer) async {
  var player = AudioPlayer();
  await player.setAsset("audio/tick.mp3");
  player.play();
});
```

But when the loop interval reaches 100ms, the application freezes. And print this error log:
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: (-11800) The operation could not be completed
#0      AudioPlayer._load (package:just_audio/just_audio.dart:840:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1421:28)
<asynchronous suspension>
flutter: A stream error occurred: PlatformException(-11819, Cannot Complete Action, null, null)
```

**Comment by ryanheise** [comment] 2022-09-08 02:52
It sounds like this is not a bug in just_audio. For it to be a bug, you must complete the first section of the bug report at least:

> **Which API doesn't behave as documented, and how does it misbehave?**
> Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

Obviously the issue you are encountering is not because of the plugin code but because your own code is interrupting its own playback.

I'll close this as it is not a bug.

**Closed as completed by ryanheise** 2022-09-08 02:52 UTC
Labels: bug, 1 backlog
