### ISSUE TITLE
Cache tracks

### ISSUE THREAD

**Issue by lain-ke** [ryanheise/just_audio#81] opened 2020-04-24 10:08 UTC
**Is your feature request related to a problem? Please describe.**
Every time the next track plays, the user has to wait for it to load, even with the ones that have already played.

**Describe the solution you'd like**
It would be nice if the next track on the queue would get cached while the previous track is playing.

**Describe alternatives you've considered**
None, I'll wait to see the response.

**Additional context**
This behavior can be seen in the https://github.com/gafsel/flutter_plugin_playlist plugin.

**Comment by ryanheise** [comment] 2020-04-24 11:16
There is no concept of a queue in `just_audio` but there is a feature request to add one in #36 including gapless playback, and your feature request would be included as part of #36 .

In the meantime, you would need to write your own queue preloading logic.

Duplicate of #36

**Closed by ryanheise** 2020-04-24 11:16 UTC
Labels: 1 backlog, enhancement
