### ISSUE TITLE
Audio stream in Chrome does not return "ready" state after "stop" and "play". Bring only "buffering"

### ISSUE THREAD

**Issue by oseiasmribeiro** [ryanheise/just_audio#648] opened 2022-02-04 13:37 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Problem: There is different behavior in returning state using Flutter Web in Chrome compared to Android and iOS. After initializing the audio it reaches the "ready" state. After "Play" and "Stop" it reaches the "idle" state. After "play" again, it goes through the "loading" state and stops at "buffering". It doesn't get to the "ready" state again.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".
Reply:
```
import 'dart:math';
import 'package:just_audio/just_audio.dart' as ja;
import 'package:audio_session/audio_session.dart';
import 'package:flutter/material.dart';

class WebRadio extends StatefulWidget {

  const WebRadio({Key? key}) : super(key: key);

  @override
  State<WebRadio> createState() => _WebRadioState();
}

class _WebRadioState extends State<WebRadio> {

  final _audioPlayer = ja.AudioPlayer(
    handleInterruptions: false,
    androidApplyAudioAttributes: false,
    handleAudioSessionActivation: false,
  );
  
  @override
  void initState() {
    init();
    super.initState();
  }

  init(){
     AudioSession.instance.then((audioSession) async {
      await audioSession.configure(const AudioSessionConfiguration.speech());
      _handleInterruptions(audioSession);
      await _audioPlayer.setUrl("https://servidor18.brlogic.com:7436/live?type=.m3u");
    });
  }

  void _handleInterruptions(AudioSession audioSession) {
   
    bool playInterrupted = false;

    audioSession.becomingNoisyEventStream.listen((_) {
      stop();
    });

    _audioPlayer.playingStream.listen((playing) {
      playInterrupted = false;
      if (playing) {
        audioSession.setActive(true);
      }
    });

    // Observe interruptions to the audio session
    audioSession.interruptionEventStream.listen((event) {
      if (event.begin) {
        switch (event.type) {
          case AudioInterruptionType.duck: // outro app inicia o audio
            if (audioSession.androidAudioAttributes!.usage == AndroidAudioUsage.game) {
              _audioPlayer.setVolume(_audioPlayer.volume / 2);
            }
            playInterrupted = false;
            break;
          case AudioInterruptionType.pause:
          case AudioInterruptionType.unknown: // outro app inicia o audio
            if (_audioPlayer.playing) {
              stop();
              playInterrupted = true;
            }
            break;
        }
      } else {
        switch (event.type) {
          case AudioInterruptionType.duck:
            _audioPlayer.setVolume(min(1.0, _audioPlayer.volume * 2));
            playInterrupted = false;
            break;
          case AudioInterruptionType.pause:
            if (playInterrupted) play();
            playInterrupted = false;
            break;
          case AudioInterruptionType.unknown:
            playInterrupted = false;
            break;
        }
      }
    });
  }

  void play() {
     _audioPlayer.play();
  }

  void stop() {
     _audioPlayer.stop();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      stop();
    }
  } 

  @override
  void dispose() {
    _audioPlayer.dispose();
    super.dispose();
  }
 
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Row(
        children: [
          Container(
            height: 200,
            width: MediaQuery.of(context).size.width,
            color: Colors.cyan,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                StreamBuilder<ja.PlayerState>(
                  stream: _audioPlayer.playerStateStream,
                  builder: (context, snapshot) {
                    final playerState = snapshot.data;
                    if (playerState?.processingState == ja.ProcessingState.ready){
                       return playerState?.playing == true ? 
                        IconButton(
                          icon: const Icon(Icons.stop),
                          iconSize: 64.0,
                          onPressed: stop,
                        ) : 
                        IconButton(
                          icon: const Icon(Icons.play_arrow),
                          iconSize: 64.0,
                          onPressed: play,
                        );
                    } else {
                        return Container(
                          margin: const EdgeInsets.all(8.0),
                          width: 64.0,
                          height: 64.0,
                          child: const CircularProgressIndicator(),
                        );
                    }
                  },
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

**To Reproduce (i.e. user steps, not code)**
Reply: No Steps.

**Error messages**

```
No error messages
```

**Expected behavior**
Reply: Bring the "ready" state back after "stop" and "play"

**Screenshots**
Reply: No screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]
Reply:
macOS Monterey Version 12.1
Versão 98.0.4758.80 (Versão oficial) (x86_64)

**Smartphone (please complete the following information):**
Reply:
Iphone 11 and Redmi Note 10
iOS 15.1 and Android 11 

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

**Additional context**
Reply: No.

**Comment by ryanheise** [comment] 2022-02-04 13:57
The bot has already closed your previous two issues, and I am closing this one manually because you did the very thing that the bot asked you to please not do, which is to leave in the section headings to fool the bot, but to not actually follow the instructions under each section heading.

**Closed by ryanheise** 2022-02-04 13:57 UTC
Labels: bug, 1 backlog

**Comment by oseiasmribeiro** [comment] 2022-02-04 14:05
Sorry. It's not my intention. I could not understand what is missing to describe the bug. It's the first time I've seen a Bot like this. I don't understand fluent english.

**Comment by ryanheise** [comment] 2022-02-04 14:06
Can you tell me which part of the bot's message is confusing? I will rephrase it.

**Comment by oseiasmribeiro** [comment] 2022-02-04 14:17
I think the Bot noticed that a link is missing. In this part I understood that I could only write the code when it says: "just write".

"Fork this repository and modify the example to reproduce the bug, then provide a link here.
If the unmodified official example already reproduces the bug, just write "The example".

Maybe using something like **Required** in items would be easier to understand.

**Comment by ryanheise** [comment] 2022-02-04 14:42
So out of curiosity, did you skip reading the first line of the instructions?

**Comment by oseiasmribeiro** [comment] 2022-02-04 15:01
The first line says: , but it doesn't say they are required. For example, when asked: "Steps to reproduce the behavior" my response was: "No steps". Although for me it means that I completed this question by answering: "No steps", it doesn't mean that I am obliged to describe the step by step, because to me the bug seems very clear. But I understand your requirement as a developer. If you can describe the flaws in describing "Ussues" I would be very grateful.

**Comment by oseiasmribeiro** [comment] 2022-02-04 15:06
Sorry, I don't mean to be rude, I'm just showing my difficulty. I saw that many "Issues" were closed for not following the rules. Maybe people didn't even see that they weren't accepted. It's a bad thing for everyone to do things anyway without properly explaining it and you're right to demand it.

**Comment by ryanheise** [comment] 2022-02-04 16:03
In case you speak Portuguese, does this auto translation help make it clearer?

> Forneça aqui uma ligação utilizando uma de duas opções:
> 1. Forçar este repositório e modificar o exemplo para reproduzir o bug, depois fornecer aqui uma ligação.
> 2. Se o exemplo oficial não modificado já reproduzir o bug, basta escrever "O exemplo".

**Comment by oseiasmribeiro** [comment] 2022-02-04 17:24
@ryanheise, So is it good?

**Which API doesn't behave as documented, and how does it misbehave?**

I am using:
- just_audio: ^0.9.18
- audio_session: ^0.1.6+1
There is different behavior in returning state using Flutter Web in Chrome compared to Android and iOS. After initializing the audio it reaches the "ready" state. After "Play" and "Stop" it reaches the "idle" state. After "play" again, it goes through the "loading" state and stops at "buffering". It doesn't get to the "ready" state again.

Code snippet where I print the state stream:
```
...
  StreamBuilder<ja.PlayerState>(
    stream: _audioPlayer.playerStateStream,
    builder: (context, snapshot) {
      final playerState = snapshot.data;
      // print log 
      print(playerState?.processingState);
      if (playerState?.processingState != ja.ProcessingState.ready  && playerState?.processingState != ja.ProcessingState.idle){
        return Container(
          margin: const EdgeInsets.all(8.0),
          width: 64.0,
          height: 64.0,
          child: const CircularProgressIndicator(),
        );
      } else {
        return playerState?.playing == true ? 
        IconButton(
          icon: const Icon(Icons.stop),
          iconSize: 64.0,
          onPressed: stop,
        ) : 
        IconButton(
          icon: const Icon(Icons.play_arrow),
          iconSize: 64.0,
          onPressed: play,
        );
      }
    },
  ),
...
```

**Minimal reproduction project**
[https://github.com/oseiasmribeiro/webradio.git](url)

**To Reproduce (i.e. user steps, not code)**
Steps to reproduce the behavior:
- Click on button Play 
- Click on button Stop
- Click on button Play Again
- After that, the state is "buffering" being described on the screen by a CircularProgressIndicator();

**Error messages**
In Chrome browser after "Play" and "Stop" and "Play" again, the state is only in "buffering"
```
I[/flutter]() ( 2554): ProcessingState.loading
I[/flutter]() ( 2554): ProcessingState.buffering
I[/flutter]() ( 2554): ProcessingState.ready
------------------------------------------------- clicked on play -----
I[/flutter]() ( 2554): ProcessingState.buffering
I[/flutter]() ( 2554): ProcessingState.ready
------------------------------------------------- clicked on stop -----
I[/flutter]() ( 2554): ProcessingState.idle
------------------------------------------------- clicked on play -----
I[/flutter]() ( 2554): ProcessingState.loading
I[/flutter]() ( 2554): ProcessingState.buffering
I[/flutter]() ( 2554): ProcessingState.buffering
```

**Expected behavior**
On Android and iOS it is behaving as expected:
```
------------------------------------------------- clicked on play -----
I[/flutter]() ( 2554): ProcessingState.idle
I[/flutter]() ( 2554): ProcessingState.loading
I[/flutter]() ( 2554): ProcessingState.ready
------------------------------------------------- clicked on stop -----
I[/flutter]() ( 2554): ProcessingState.ready
I[/flutter]() ( 2554): ProcessingState.idle
------------------------------------------------- clicked on play -----
I[/flutter]() ( 2554): ProcessingState.idle
I[/flutter]() ( 2554): ProcessingState.loading
I[/flutter]() ( 2554): ProcessingState.ready
```
What is desired is that the state does not stop "buffering" because in this way it is not possible to show the buttons correctly.

**Screenshots**
![Captura de Tela 2022-02-04 às 14 07 41](https://user-images.githubusercontent.com/36827173/152571940-95cb270c-4364-45c7-a379-bb800747d19e.png)

**Desktop (please complete the following information):**
 - macOS Monterey Version 12.1
 - Google Chrome: Versão 98.0.4758.80 (Versão oficial) (x86_64)

**Smartphone (please complete the following information):**
- Iphone 11 and Redmi Note 10
- iOS 15.1 and Android 11

**Flutter SDK version**
```
oseiasribeiro@Oseiass-MacBook-Pro webradio % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[!] Android Studio
    ✗ Android Studio not found at /path/to/android-studio/Contents
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.64.0)
```

**Additional context**
There is not.

**Comment by oseiasmribeiro** [comment] 2022-02-04 21:22
@ryanheise Please let me know if I have to open a new Issue about this issue and I apologize for my lack of attention to the rules in the description. You were right. Google translation skews a bit.

**Comment by ryanheise** [comment] 2022-02-05 07:03
Thank you, I will take a look when I get a chance.

**Comment by oseiasmribeiro** [comment] 2022-02-05 14:05
🙏🏻 Thank You

**Comment by ryanheise** [comment] 2022-02-08 03:08
I can reproduce.

**Comment by ryanheise** [comment] 2022-02-08 03:50
I've logged the javascript events as well, and got:

```
ProcessingState.loading
### loadstart (buffering)
ProcessingState.buffering
ProcessingState.ready
### canplaythrough (ready)
ProcessingState.ready
### waiting (buffering)
ProcessingState.buffering
### canplaythrough (ready)
ProcessingState.ready
ProcessingState.idle

ProcessingState.loading
### loadstart (buffering)
ProcessingState.buffering
### waiting (buffering)
ProcessingState.buffering
```

So I'm not actually receiving a canplaythrough event after stopping and starting and it never becomes ready. Not sure what javascript event I'm missing here, though.

**Comment by oseiasmribeiro** [comment] 2022-02-08 12:10
Understand. Thank's for your time. I'm looking forward to getting the problem resolved.

**Comment by ryanheise** [comment] 2022-02-08 13:30
I'm blocked for now, since I don't see any Javascript event that actually tells me when it stops buffering, and I therefore can't relay that to the app. If you have any ideas on what Javascript events might do the trick, you can share them below and I'll be able to implement that for you sooner.

**Comment by oseiasmribeiro** [comment] 2022-02-08 13:31
Okay. I'll do a search. Thanks

**Comment by oseiasmribeiro** [comment] 2022-02-08 16:37
Can you point me something the way so I can help research? The path of what is used by Just_Audio behind the plugin. Like some javascript library or something.

**Comment by ryanheise** [comment] 2022-02-09 01:37
I'm not sure about existing Javascript libraries since I just looked up the reference documentation directly. You can see in the code where I use events like `waiting` and `canplaythrough` as they are all in the same section of code. So maybe you can Google search for these event names and search for issues other programmers have run into where a live stream isn't broadcasting `canplaythrough` after `waiting`.

**Comment by oseiasmribeiro** [comment] 2022-02-09 11:47
I'll do it. Thanks
