### ISSUE TITLE
icyMetadata#info parameters are null from asset url 

### ISSUE THREAD

**Issue by takapiroid88** [ryanheise/just_audio#775] opened 2022-07-13 07:52 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
set the asset audio url and access icyMetadata.
but parameters are null.

AudioPlayer#icyMetadata#title
AudioPlayer#icyMetadata#url

I tried 
```
DefaultAssetBundle.of(context)
        .loadString('AssetManifest.json')
        .then((manifestJson) {
      List<String> images = json.decode(manifestJson).keys.where((String key) {
        return key.startsWith('assets/audios/');
      }).toList();

      Future.wait(images.map((image) async {
        final player = AudioPlayer();
        await player.setUrl("asset:$image");
        return player;
      })).then((values) {
        values.forEach((v) {
          print("v.icyMetadata?.info: ${v.icyMetadata?.info}"); // each null value
          v.icyMetadataStream.listen((event) {
            print("meta data stream: ${event?.info}"); // each null value
          });
        });
      });
    });
```

**Minimal reproduction project**
I prepare asset like below
```
project
- assets
  - audios
    - sample1.mp3
    - sample2.mp3
```

each sample.mp3 is set the title.
but cannot get it.

**To Reproduce (i.e. user steps, not code)**
setup above environment.

**Error messages**
none

**Smartphone (please complete the following information):**
 - Device: Androdi 4a / iPhoneX
 - OS: Android 11 / iOS 15.4

**Flutter SDK version**
flutter3.0.1

**Comment by ryanheise** [comment] 2022-07-13 08:02
Hmm, where is this desired behaviour documented? I thought icy is a protocol so it only comes into play when served from a server with appropriate http headers.

**Comment by takapiroid88** [comment] 2022-07-13 08:51
I see. I'm sorry.

I didnt understand icy.
I'd like to get metadata of asset audio.

Do you know how to do that?

**Comment by ryanheise** [comment] 2022-07-13 13:08
There is no just_audio API to get metadata from an asset. But since your app knows which assets are to be included in the bundle, you could just hard code the metadata you want in an array/map (or some other data structure) in your Dart code. I'll close this issue since it is not a bug.

**Closed as completed by ryanheise** 2022-07-13 13:08 UTC
Labels: bug, 1 backlog
