### ISSUE TITLE
package not working on ios

### ISSUE THREAD

**Issue by sinasf** [ryanheise/just_audio#577] opened 2021-10-31 11:49 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
SetUrl() method not working on ios devices

**Minimal reproduction project**
I am trying to run the just_audio sample project from its own repository here :
https://github.com/ryanheise/just_audio/tree/master/just_audio/example

It is working fine on android but when I clone the project using a mac and run it on the simulator it throws this error :
And this error pops up while I'm trying to call the audio URL for streaming using setUrl() method

**Error messages**

```
    [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: (-11800) The operation could not be completed 
        #0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
        <asynchronous suspension>
        #1      AudioPlayer._setPlatformActive.<anonymous closure> (package:just_audio/just_audio.dart:1346:28)
        <asynchronous suspension>
```

**Expected behavior**
It Should behave as it is on Android devices

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [safari]

**Smartphone (please complete the following information):**
 - Device: [iPhone 12]
 - OS:  [iOS 15.0]

**Flutter SDK version**
```
[✓] Flutter (Channel unknown, 2.2.3, on macOS 11.6 20G165 darwin-x64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ Could not determine java version
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
```

**Additional context**
This error is only on ios devices
I have also tried Editing Transport security as the documentation recommends
```
       <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict> 
```
I have tried all the other packages available for ios for playing and streaming audio and none of them worked

**To Reproduce (i.e. user steps, not code)**
1. play any audio on remote URL 

**Screenshots**
-

**Comment by ryanheise** [comment] 2021-11-01 03:11
May I ask what version of macOS and Xcode you are using to run the example?

**Comment by sinasf** [comment] 2021-11-01 07:11
Sure 
mac Big Sur 11.6 (it's a Mac VPS)
Xcode v13.1 (I use the Mac terminal to run the app and I do not open xcode)

**Comment by ryanheise** [comment] 2021-11-01 08:42
> Device: [iPhone 12]

So do you actually mean a simulated iPhone 12 or an actual iPhone 12?

**Comment by ryanheise** [comment] 2021-11-01 08:44
To rule out that your VPS environment is a factor, can you confirm whether other audio player plugins work in that environment?

**Comment by sinasf** [comment] 2021-11-01 08:59
It's a simulated iPhone 12 but it also does not work on an  actual iPhone 12 (I have tried both release mode and debug mode)
And none of the audio player plugins works on ios 
the problem with all of them is that they are unable to load the audio from the URL
and I don't think it would be a VPS environment issue because I have tried to run the app on another mac and it throws the same error

**Comment by sinasf** [comment] 2021-11-01 11:36
I have already tried adding 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsForMedia</key>
    <true/>
</dict>
```
to info.plist

**Comment by ryanheise** [comment] 2021-11-01 11:44
OK, it is interesting however that you're running into problems no matter what plugin you try to use, while it seems to be working fine for others. There are many potential reasons why valid plugin code might generate an error particularly when accessing network resources, but I don't think there is anything in the plugin itself that I can change.

I'll leave this on the back burner until more than one person reports the same issue.

**Comment by sinasf** [comment] 2021-11-01 11:49
Ok thanks 
Same issue here 
https://github.com/ryanheise/just_audio/issues/287
but the solution was not clear :(

**Comment by ryanheise** [comment] 2021-11-01 11:57
That is not the same issue as yours. The key is that according to your bug report, your error happens on my official example without any code modifications, by which I assume you mean `example/lib/main.dart`. This is a highly unusual error because that example and that specific URL has been well tested by many people and it is working reliably.

#287 is completely different because the person reporting the issue is not talking about my own example. They ran into the issue on their own code with a completely different URL. As you can see in the discussion in that issue, it was very important to actually see that code and that URL to understand what was going on. We don't have that same scenario in your bug report because you have reported that my own example just doesn't work as is (for you, even though it is working fine for me and others.)

**Comment by ryanheise** [comment] 2021-11-04 12:09
> **Minimal reproduction project**
> I am trying to run the just_audio sample project from its own repository here :
> https://github.com/ryanheise/just_audio/tree/master/just_audio/example

None of the official examples actually use the `setUrl` method.

> **Which API doesn't behave as documented, and how does it misbehave?**
> SetUrl() method not working on ios devices

Hmm, is your bug report actually truthful when you say that the `setUrl` method is failing? How does the minimal reproduction project manage to reproduce that problem when it doesn't even call that method?

In any case, I will close this because it's clearly not a just_audio-specific problem, and the bug report repro project doesn't actually reproduce the stated issue.

**Closed by ryanheise** 2021-11-04 12:09 UTC
Labels: bug, 1 backlog
