### ISSUE TITLE
 just_audio_background supports only a single player instance

### ISSUE THREAD

**Issue by pasrot943** [ryanheise/just_audio#626] opened 2022-01-10 12:08 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
setAudioSource failes the seconds time I'm changing the playlist when using Just Audio Background

**Minimal reproduction project**
https://github.com/pasrot943/just_audio/tree/master/just_audio_background/example/lib

**To Reproduce (i.e. user steps, not code)**
1. Listening to Playlist1 in Screen2.
2. Going back to Screen1
2. Tap on Playlist2 in Screen1
2. Enter Screen2 with Playlist2 as AudioSource.
3. Tapping play
4. error message => just_audio_background supports only a single player instance

**Error messages**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, just_audio_background supports only a single player instance, null, null)
```

**Expected behavior**
I excpect only 1 instance of AudioPlayer to handle the changes of the AudioSource

**Screenshots**
No sorry

**Desktop (please complete the following information):**
 - OS: [Win 10 ]
 - Browser [Firefox]

**Smartphone (please complete the following information):**
 - Device: [Nexus 4 API 30]
 - OS: [Android 11.0]

**Flutter SDK version**
Flutter 2.0.1 

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19044.1415], locale sv-SE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Unable to determine bundled Java version.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)
```

**Additional context**
Is it better to use Audio Service than Just Audio Background if I have multiple playlists?
I just want to be able to play pods when the screen is off and have lock screen controll?

**Comment by pasrot943** [comment] 2022-01-10 12:48
Thank you for your fast reply. I'm new here at github and not familiar with how to present a "minimal reproduction project".
But I'll try your workaround, thank you very much.

**Comment by ryanheise** [comment] 2022-01-10 12:53
To create a minimal reproduction project, click the "Fork" button at the top of this page, then edit the example in the smallest way possible so that it demonstrates the bug you are reporting. That is, add a second screen and a second playlist. Otherwise you may instead close this bug report.

**Comment by pasrot943** [comment] 2022-01-12 10:02
@ryanheise

**Comment by ryanheise** [comment] 2022-01-12 10:08
> I have now created a minimal reproduction project and updated the bug report.
> 
> Thank you for your help Ryan!

Thank you, that will be helpful.

> @ryanheise

I'm afraid this reminder/attention doesn't help me get to it any sooner. I'm sick so I can't work on it just yet, and once I start working on it, these things can either take a day or weeks to fix depending on how difficult it is. If you can't wait, you may in the meantime try to work around the bug.

**Comment by pasrot943** [comment] 2022-01-12 10:48
ok sorry for the reminder, I'll try to solve it in the meantime. I'll let you know if i'm lucky.

**Comment by lucagonzalez** [comment] 2022-01-20 12:15
Hello everyone! I'm having the same bug on just_audio. 

I have an Inherited Widget somewhere on the tree that has an instance of AudioPlayer() and when I try to instantiate AudioPlayer again, I have the same error but for just_audio

**Comment by ryanheise** [comment] 2022-01-20 12:33
@lucagonzalez that is not the same bug, and is actually not a bug. The documentation for just_audio_background states that it is designed to work with a single instance, so if you're creating a new instance you are not following the documentation. Rather, you need to redesign your code so that you do not create a new instance.

**Comment by ryanheise** [comment] 2022-01-23 03:51
Hi @pasrot943 

I have just had a chance to look at your reproduction project and it seems that you are actually instantiating more than one `AudioPlayer` because the player instance is created from within the `initState` of a page that can be visited multiple times. This is by design, and my previous comment to @lucagonzalez also applies to you. You need to create a single instance of `AudioPlayer` and retain it for future use.

**Comment by pasrot943** [comment] 2022-02-19 20:54
You are right, I had to instantiate the player as a global instance and than pass it along as an object to other screens.
It is working now.

**Comment by ryanheise** [comment] 2022-02-20 04:34
You might also consider using something like get_it to inject the instance wherever it is needed within the app. But glad to hear it is working as intended, so I'll close the issue.

**Closed by ryanheise** 2022-02-20 04:34 UTC
Labels: bug, 1 backlog
