### ISSUE TITLE
.setVolume and listener on iOS doesn't work

### ISSUE THREAD

**Issue by amedeopro** [ryanheise/just_audio#734] opened 2022-05-23 09:14 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
I have two playlists and at a certain time one of the two must lower the volume of the one that is playing the song and raise it only at the end of the second playlist, this works only on Android

**Minimal reproduction project**
Link to fork: https://github.com/yadaniyil/just_audio

Here my code:

define the playlists:

```dart
  final _braniPlayer = AudioPlayer();
  final _messaggiPlayer = AudioPlayer();
```

this is the first playlist run:

```dart
  playBrani() async{
    var playlist = await getDataFromPl();
    var brani = playlist['lista']['brano'];
    print('player');
    final externalDir = Platform.isAndroid ? await getExternalStorageDirectory() : Platform.isIOS ? await getApplicationDocumentsDirectory() : null;
    final pathPlayer = '${externalDir?.path}/PLAYER';
    late ConcatenatingAudioSource _playlist;

    List<AudioSource> braniArray = [];
    _playlist = ConcatenatingAudioSource(children: braniArray);

    for(var brano in brani){

      final localizedDt = tz.TZDateTime.from(DateTime.now(), rome);
      String formattedTime = DateFormat('HH:mm:ss').format(localizedDt);
      print(formattedTime);

      if(brano['ora'].compareTo(formattedTime) > 0){
        print('l\'ora del brano è successivo all\'orario attuale');
        print(brano['ora']);
        var branoUri = Uri.parse('$pathPlayer/${brano['md5']}.mp3');
        braniArray.add(AudioSource.uri(branoUri));
      }
    }

    await _braniPlayer.setAudioSource(_playlist);
    _braniPlayer.play();

  }
```

Here the second playlist where the listeners doesn't work on iOS (I am not even returned the prints in the log, instead on android I see them)

```dart
playMessaggi() async{
    bool canPlayMessaggi = false;
    var playlist = await getDataFromPl();
    var messaggi = playlist['messaggi']['messaggio'];
    print('player messaggi');
    final externalDir = Platform.isAndroid ? await getExternalStorageDirectory() : Platform.isIOS ? await getApplicationDocumentsDirectory() : null;
    final pathPlayer = '${externalDir?.path}/PLAYER';
    late ConcatenatingAudioSource _playlist;


    List<AudioSource> msgArray = [];
    _playlist = ConcatenatingAudioSource(children: msgArray);

    for(var msg in messaggi) {
      final localizedDt = tz.TZDateTime.from(DateTime.now(), rome);
      String formattedTime = DateFormat('HH:mm:00').format(localizedDt);

      print('msg[\'ora\']: ${msg['ora']}');
      print('formattedTime: $formattedTime');
      print(msg['ora'].compareTo(formattedTime) == 0);

      if (msg['ora'].compareTo(formattedTime) == 0) {
        canPlayMessaggi = true;
        var msgUri = Uri.parse('$pathPlayer/${msg['md5']}.mp3');
        msgArray.add(AudioSource.uri(msgUri));
      }
    }

    if(canPlayMessaggi){
      _braniPlayer.setVolume(0.2);
      _messaggiPlayer.setAudioSource(_playlist);
      _messaggiPlayer.play();
      _messaggiPlayer.playerStateStream.listen((state)  {
        print('listeners');
        if(state.processingState == ProcessingState.completed){
          print('processing state completed');
           _braniPlayer.setVolume(1);
        }
      });
    }

  }
``` 

**To Reproduce (i.e. user steps, not code)**
1. build the app on iOS
2. the listner is not considered
3. build the app in Android
4. the work correctly

**Error messages**
No error messages were found.

**Expected behavior**
I expect that as soon as playlist B is played, the volume of playlist A will be lowered but then it will be raised when the song of playlist B ends, it works only on Android

**Screenshots**
here my code
![immagine](https://user-images.githubusercontent.com/44196253/169785619-69d1f1e4-b1a3-4bd7-a2dc-178ae0e012b4.png)

I also tried this way
![immagine](https://user-images.githubusercontent.com/44196253/169785891-f86b2415-271f-478b-b433-142d576462c9.png)

**Desktop (please complete the following information):**
 - OS: iOS (all versions)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.4

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale
    it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
i read documentation, but i can't find a solution for this issue. Thank you

**Comment by ryanheise** [comment] 2022-05-23 09:28
I don't need your screenshots of code, the code is in the minimal reproduction project.

Looking at your commit, it seems the only change you made was to use a different also URL with different headers. And you're saying that that one change causes it to break while the unmodified official example works fine?

**Comment by amedeopro** [comment] 2022-05-23 09:39
Sorry, maybe I haven't been able to express myself at best with the problem I have, only and exclusively on iOS it seems that they don't care about what I write in the listener, as it should bring the volume back to 1 of another playlist that in that moment it is in the background, this on android works perfectly but iOS does not

**Comment by ryanheise** [comment] 2022-05-23 09:56
You didn't answer my question. Before continuing this discussion, please note that I don't have enough time to actually have a back and forth discussion - all I want is the minimal reproduction project, and a description of the reproduction steps.

I don't think your minimal reproduction project is actually correct because the only thing it does is change the audio source. There is nothing in your minimal reproduction project about two playlists. Please fix your bug report by providing correct details, and once you have done so comment below. If not, I won't be able to help you.

**Comment by amedeopro** [comment] 2022-05-23 10:02
ok now you have the compete code of my playlists logic

**Comment by ryanheise** [comment] 2022-05-23 10:32
1. You still didn't answer my question.
2. You still didn't provide a valid minimal reproduction project.
3. You still didn't provide valid reproduction steps for that project

I said above that I don't have enough time for a back-and-forth conversation, and that is what this is turning into, because you we keep going back and forth without you providing what was asked for in the original instructions.

Therefore, I am closing this issue.

**Closed by ryanheise** 2022-05-23 10:32 UTC
Labels: bug, 1 backlog
