### ISSUE TITLE
Implement balance control. 

### ISSUE THREAD

**Issue by chrislaurie-io** [ryanheise/just_audio#1025] opened 2023-07-15 09:25 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement balance control. Controls the relative output volume of the left and right channels.

_player.setBalance(0) // normal left & right stereo
_player.setBalance(-1.0) // play only left channel
_player.setBalance(1.0) // play only right channel
_player.setBalance(-0.75) // play left channel 100% , right channel 25%

**Describe alternatives you've considered**
Devices do not have their own balance controls.

**Additional context**
I think the details above is sufficient bit would gladly give more feedback if required.

**Comment by ryanheise** [comment] 2023-07-15 09:33
I feel like this has been asked before. Are you sure you've searched past issues?

(Searches...)

Duplicate of #126

**Closed as completed** 2023-07-15 09:33 UTC
Labels: enhancement, 1 backlog

**Comment by chrislaurie-io** [comment] 2023-07-15 09:35
My bad - I searched for the word balance.

**Comment by ryanheise** [comment] 2023-07-15 12:42
No problem.
