### ISSUE TITLE
setAsset doesn't work with .wav

### ISSUE THREAD

**Issue by ScottishRoss** [ryanheise/just_audio#455] opened 2021-07-20 16:03 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
I am using just_audio to play asset files and it appears .wav files do not work. I converted the file to .mp3 and it works fine.

**Minimal reproduction project**
I can provide a MRP if required, but all I tried to do was load a .wav through setAsset. 

**To Reproduce (i.e. user steps, not code)**
1. Attempt to use a .wav file in setAsset.
2. Attempt to play the audio file.

**Error messages**

```
PlayerException ((0) Source error)
```

**Expected behavior**
The audio file should play.

**Screenshots**
![image](https://user-images.githubusercontent.com/25175556/126357103-e9aa3014-3f28-493b-8e7b-a8473abe0c95.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10
 - Browser: N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 12

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by ryanheise** [comment] 2021-07-20 16:45
> **Minimal reproduction project**
> I can provide a MRP if required, but all I tried to do was load a .wav through setAsset.

Not all WAV files are the same, and it is possible your WAV file wasn't encoded correctly. I would check this first, since if your WAV file was generated by another plugin that itself has a bug and produces invalid WAV files, you may want to submit the bug report with that project.

Otherwise if you have narrowed down the bug to this plugin, then yes you need to provide a way to reproduce the bug as is explained in CONTRIBUTING.md.

**Comment by ScottishRoss** [comment] 2021-07-21 09:43
What encoding do I need to use for wav so I can test that first?

**Comment by ryanheise** [comment] 2021-07-21 10:17
It's not a matter of inviting, it's a matter of a file being corrupted or not. Maybe the program that generated the wav file outputted an invalid file, so you'll can try generating it with different programs.

**Comment by ryanheise** [comment] 2021-07-21 16:07
In CONTRIBUTING.MD it mentions that if it's just an issue with playing a particular file, you can just supply a URL to that file in your bug report. If you're not willing to share the file, maybe you could at least share which program encoded the file since I've mentioned that that could be the cause.

For example, are you using a flutter plugin to record the wav, and if so which one?

**Comment by ryanheise** [comment] 2022-06-25 02:30
> I have converted those files to .mp3, it is working. I guess it is related to file encryption.

OK, I'll close the issue, since it sounds like the encryption was the issue.

**Closed by ryanheise** 2022-06-25 02:30 UTC
Labels: bug, 1 backlog
