### ISSUE TITLE
not working on some devices

### ISSUE THREAD

**Issue by MahdiPishguy** [ryanheise/just_audio#7] opened 2019-12-24 09:48 UTC
this library not working on some devices such as `Huawei p30 lite`, `samsung j7`, `Galexy j3pro`, `samsung j5`, `Samsung Galaxy J1`, `Samsong g7`

and not working on Android 9

**Comment by ryanheise** [comment] 2019-12-26 12:53
@MahdiPishguy This seems to be a duplicate of an issue you posted on `audio_service` where you elaborated that you didn't have any further details to provide besides that the customer told you that it didn't work. I am not sure whether you know where the bug is, which is why you opened the same bug on both projects, however if you don't know which plugin or module is at fault, then it is even possible that the fault is elsewhere, but without providing any details of the bug itself, there is no way to follow up on that. Unfortunately, if that is the case, then the issue is unactionable.

However, please re-open this issue in the future if you are able to provide concrete details about a bug.

**Closed by ryanheise** 2019-12-26 12:53 UTC

**Comment by MickaelHrndz** [comment] 2020-01-24 00:15
Only **https** audio links are working on my client's Samsung Galaxy S8.

**Comment by ryanheise** [comment] 2020-01-24 03:56
See: https://medium.com/@imstudio/android-8-cleartext-http-traffic-not-permitted-73c1c9e3b803

**Comment by MickaelHrndz** [comment] 2020-01-25 15:56
@ryanheise Thank you, that did the trick.
