### ISSUE TITLE
Is there any roadmap for implementing clip audio for iOS ?

### ISSUE THREAD

**Issue by pureimpro** [ryanheise/just_audio#71] opened 2020-04-15 20:39 UTC
Self explanatory.
Thanks @ryanheise & contributors for your wonderful work in just_audio and audio_service packages !
Head on dudes, we believe in you 👍

**Comment by ryanheise** [comment] 2020-04-16 02:21
Thanks for your interest and support. I have some ideas on how it can be done, but it is a matter of finding the time. It would be a bit hard to make a roadmap right now, especially with the unpredictable times we are currently undergoing.

**Comment by pureimpro** [comment] 2020-05-16 23:08
Hello @ryanheise,
did you manage to find the time to implement the IOS part of ClipAudio ?
This would be great since this is a real showstopper for me.
I hope you understand. Sorry to bother you !

**Comment by ryanheise** [comment] 2020-05-20 16:18
@pureimpro I unfortunately haven't found time yet. I do have some ideas for how to go about it, but I have a lot of bugs and feature requests to work through first.

By the way, in the meantime, you can do something fairly inaccurate like this:

```dart
await player.seek(start);
player.play();
await Future.delayed(duration);
await player.pause();
```

Sorry this is not as good as what is currently supported on Android, and indeed may not be good enough for what you're trying to accomplish.

**Comment by pureimpro** [comment] 2020-05-31 13:38
Thanks for this feedback & workaround , I'll give It a try.
I understand your workload, since I'm notified of all just_audio and audio_service thread messages. Can you even find enough time to sleep ? Lol. 

If you don't mind I will ask you once again to prioritize this feature in the near future. 

In the meantime, I will definitely give a try to your workaround and give you my feedback.
My main interrogation is how to be able to cheat system notification with track duration and appropriate media controls while a portion only of a track is played.

Thanks again for your awesome work !

**Comment by ryanheise** [comment] 2020-05-31 16:13
Thanks for understanding. I would definitely like to implement this feature, but I also have to prioritise the work. If someone else is sufficiently motivated and doesn't want to wait indefinitely for me to get around to it, I would welcome a PR.

The workaround described above will have the effect of overshooting, or playing a bit more audio than desired, I'd guess up to 100-200ms beyond the precise duration you want. In some cases, this might be acceptable. I don't fully understand your use case, but it sounds like maybe this could actually be good enough for you.

**Comment by ryanheise** [comment] 2020-07-27 18:46
Hi @pureimpro 

This is now implemented on the media-source branch. See #131 for details.

I will close this issue as a duplicate of #131

**Comment by ryanheise** [comment] 2020-07-27 18:46
Duplicate of #131

**Closed by ryanheise** 2020-07-27 18:46 UTC
Labels: 1 backlog, enhancement

**Comment by pureimpro** [comment] 2020-07-28 09:37
Man, you're definitely a killer !
I've just battled a bunch of days this week, finding a workaround that did the trick, but in the meantime you managed to code this huge bundle of new features !
So yesterday, I reverted back to your code and currently testing the media-source branch.
Good news, for IOS, audio clipping is behaving as expected so far.
Great job dude :)

**Comment by ryanheise** [comment] 2020-07-28 09:39
Glad to hear it! If you find any issues, please report on the new issue which replaces this one.
