### ISSUE TITLE
"Searched too many bytes" Error when seeking

### ISSUE THREAD

**Issue by helomri** [ryanheise/just_audio#1021] opened 2023-07-12 16:07 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
When a StreamVideoSource is demanded with a range request (ex. while seeking through a track), Exoplayer gives a fatal error.

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. Read an MP3 file from a StreamAudioSource.
2. Try to seek somewhere not buffered yet to create a new range request.
3. See the error in the console.

**Error messages**

```
E/ExoPlayerImplInternal( 5554): Playback error
E/ExoPlayerImplInternal( 5554):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
E/ExoPlayerImplInternal( 5554):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5554):       at android.os.Looper.loopOnce(Looper.java:226)
E/ExoPlayerImplInternal( 5554):       at android.os.Looper.loop(Looper.java:313)
E/ExoPlayerImplInternal( 5554):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5554):   Caused by: com.google.android.exoplayer2.ParserException: Searched too many bytes.
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:387)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readInternal(Mp3Extractor.java:262)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:235)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
E/ExoPlayerImplInternal( 5554):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 5554):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/ExoPlayerImplInternal( 5554):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/ExoPlayerImplInternal( 5554):       at java.lang.Thread.run(Thread.java:1012)
```

**Expected behavior**
The player should have buffered and waited for its data

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38
 - Browser Firefox 115.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A12
 - OS: Android 12

**Flutter SDK version**
```
[✓] Flutter (Channel beta, 3.12.0, on Fedora Linux 38 (KDE Plasma) 6.3.11-200.fc38.x86_64, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Additional context**
I am decrypting a file through a stream and reading it. But when I set in my StreamAudioResponse contentLength to null, the reader buffer like normal, I just have an error and sometimes a timeout from the socket kinked to the local proxy server. The error points to the [line 3127 of just_audio.dart](https://github.com/ryanheise/just_audio/blob/minor/just_audio/lib/just_audio.dart#L3127). Also to have max success rate currently I use this strange piece of code in my range response: 
```dart
contentLength: start == null ? null : (end ?? fileByteLength) - (start ?? 0)
```
Also I found this in my research: https://exoplayer.dev/customization.html#enabling-constant-bitrate-seeking
I've tried to add it with the default factory and the same error occurs. Other people on the internet already have this issue as shown here: https://github.com/google/ExoPlayer/issues/4954
I think I will eventually find a fix but I think I need help from the original writer of the native/android part of the code because I am not familiar with the Exoplayer2 API.

**Comment by ryanheise** [comment] 2023-07-13 01:19
> **Minimal reproduction project**
> The example

I think this is false. The example does not demonstrate StreamAudioSource (which I assume you meant instead of StreamVideoSource).

The error you describe tells you that the source of the data was bad. Since your app is the source of the data, the bug is likely in your app rather than in just_audio. Feed Exoplayer correct data and it will not give that error. You mention another error in line 3127 of just_audio, but you don't provide a minimal reproduction project for that or the error message, as your bug report is a bit unfocused and difficult to act on. I'll close this, and if you have found two bugs, please submit two bug reports each with the required steps I need to reproduce in the required bug report format.

**Closed as completed by ryanheise** 2023-07-13 01:19 UTC
Labels: bug, 1 backlog
