### ISSUE TITLE
Seamless looping broken / clipping on iOS 17+

### ISSUE THREAD

**Issue by declanshine2** [ryanheise/just_audio#1138] opened 2023-12-08 06:14 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening

.Hi ryanheise, we are using just_audio to handle the audio of our flutter app.

On devices running iOS 17+ the seamless looping does not work as intended, instead there is a jarring clipping noise between each loop. This issue did not appear after an update on our end, only after an iOS update.

This is highly disturbing to our app experience, as we are looping short audio files with the effect of creating a calming, relaxing environment for our users.

All works fine on android devices and iOS devices running iOS 15.5, any help is greatly appreciated.

Below is the code responsible for playing (and looping) the audio files:

```

  @override

   playMusic() async {
      Directory appDocDir = await getApplicationDocumentsDirectory();
  
      await audioPlayer.setFilePath("${appDocDir.path}/${frequency.audio_url}");
      
       
       await audioPlayer.setLoopMode(LoopMode.one);
       await audioPlayer.play();
       await audioPlayer.setVolume(audioVolume);
    
  }

```
You may test the app yourself using the following link: https://apps.apple.com/us/app/frequencies/id1622375454

Many thanks,

Declan

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

https://apps.apple.com/us/app/frequencies/id1622375454

**To Reproduce (i.e. user steps, not code)**
1. Go to the frequencies screen
2. Click on any frequency and let it start playing
3. Witness looping issue / jarring noise on every loop

**Error messages**

```
N/A
```

**Expected behavior**
Clean and seamless looping

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17

**Flutter SDK version**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)            
[✓] Network resources

• No issues found!

**Additional context**
I appreciate your assistance on this matter.

**Comment by ryanheise** [comment] 2023-12-08 06:42
Closing as an invalid bug report. Reason: No minimal reproduction project was provided (among other reasons - if you open a new bug report, please stick to the instructions).

**Closed as completed by ryanheise** 2023-12-08 06:42 UTC
Labels: bug, 1 backlog

**Comment by declanshine2** [comment] 2023-12-08 06:52
I'm sorry, I must have misunderstood, can you help me understand what more is required for this to become valid? What do you require from me?

**Comment by ryanheise** [comment] 2023-12-08 06:59
Why don't you read the instructions sentence by sentence and then ask me when you get to a sentence that you think is unclear? Because obviously I don't have the time to explain the whole instructions again. If English is not your first language, then also use something like Google translate first.

**Comment by declanshine2** [comment] 2023-12-08 07:47
I appreciate your understanding and patience on this matter. 

English is my first language, however this is the first time that I have ever reported an issue on github. My apologies for not following the conventions. I understand that you are asking me for a minimal reproduction project, is the code I provided above not sufficient for this purpose?

My apologies if I am wasting your time or being inconvenient, I merely wish to resolve this issue.

Many thanks,

Declan

**Comment by ryanheise** [comment] 2023-12-08 08:11
I wrote instructions on exactly how to submit a minimal reproduction project with exactly two options. What don't you understand about the two options? Please quote the sentence and ask me about the sentence. Also if you are a native speaker, please first use Google to learn any words that you don't already know.

**Comment by declanshine2** [comment] 2023-12-08 08:26
Unfortunately, your instructions are unclear to the reader, perhaps this needs to be adjusted for the future, if this is a common occurrence you are facing which is causing you frustration.

Specifically, I am unable to locate "the example" in your repository that you are referring to:

Fork this repository and modify **the example** to reproduce the bug, then provide a link here.


Could you kindly adjust the bot text to include the filepath of this example that you would like me to modify? Thank you.

**Comment by ryanheise** [comment] 2023-12-08 08:28
Just to confirm, you understand what I mean by "this repository" and "fork"?

**Comment by declanshine2** [comment] 2023-12-08 08:37
Yes, I understand what you mean with these terms.

Unfortunately, it remains unclear to me what files within this forked repository I should be adjusting to reproduce this issue for you. It is also unclear to me if I should be choosing your first or second option. Where can I find the "unmodified official example" you speak of in the second option? 

In case there is a misunderstanding here, here is some more information:

I am using the just_audio package for flutter and I have not made any changes to said package. I am simply using the loop functionality of this plugin "out of the box" without any adjustments to the package itself.

I appreciate your efforts in helping me resolve this issue.

**Comment by ryanheise** [comment] 2023-12-08 12:33
I am rewriting my long explanation of how to use the Ctrl+F and instead just giving you a screenshot with purple arrows:

![image](https://github.com/ryanheise/just_audio/assets/19899190/b1b4875e-2cb2-4fc6-9d6d-c322d6a3a184)

First arrow: where's the example? Second arrow: where's the repository? Third arrow: why was your bug report closed?

You should explore everything before submitting a bug.

> if this is a common occurrence

No, you are the first person who did not find the example themselves through due diligence.

**Comment by declanshine2** [comment] 2023-12-11 10:09
Thank you for your screenshot with arrows, I appreciate this greatly. I will attempt to make a bug report the correct way, following your instructions as best as I can. Many thanks, Declan
