### ISSUE TITLE
Exception on playing lots of audio files

### ISSUE THREAD

**Issue by hesham91fci** [ryanheise/just_audio#159] opened 2020-08-24 14:53 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
setUrl, setAsset, setFilePath all of them are throwing exception for a specific file recorded from flutter_recorder, despite the same file plays normally on other media players and plays normally using "AudioPlayers" plugin, 
note1: I'm using justAudio as the resource protected by http authorization header
note2: the file is in wav extension and with sample rate 16000

**Minimal reproduction project**
Provide a link here using one of two options:
https://github.com/hesham91fci/just_audio

**To Reproduce**
1. use the file (.wav) provided in my example as an asset in pubspec.yaml
2. use `setAsset` method to set the resource that you're going to play
3. use `play()` method to play your audio file
4. See exception thrown in error mesages section

**Error messages**

```
E/ExoPlayerImplInternal(12865): Source error
E/ExoPlayerImplInternal(12865):   com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:222)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:122)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(12865):       at java.lang.Thread.run(Thread.java:764)
E/AudioPlayer(12865): TYPE_SOURCE: Expected block size: 2; got: 1
E/flutter (12865): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: (0) com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/flutter (12865): #0      AudioPlayer._load (package:just_audio/just_audio.dart:461:9)
E/flutter (12865): <asynchronous suspension>
E/flutter (12865): #1      AudioPlayer.load (package:just_audio/just_audio.dart:425:30)
E/flutter (12865): #2      AudioPlayer.setAsset (package:just_audio/just_audio.dart:411:7)
E/flutter (12865): #3      _MyHomePageState._listenToAudio (package:just_audio_example/main.dart:52:23)
E/flutter (12865): #4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12865): #5      _MyHomePageState._listenToAudio (package:just_audio_example/main.dart:50:30)
E/flutter (12865): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (12865): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (12865): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12865): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (12865): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (12865): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (12865): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (12865): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (12865): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (12865): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12865): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (12865): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (12865): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (12865): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12865): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12865): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12865): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12865): #23     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (12865): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (12865): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (12865): #26     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (12865): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Expected behavior**
Audio file should plays normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina]
 - Browser [Chrome]

**Smartphone (please complete the following information):**
 - Device: [Sony Xperia XA1 ultra]
 - OS: [android 8.0]

**Flutter SDK version**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-EG)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)
```

**Additional context**
I've modified the original pubspec.yaml since I'm using flutter 1.12.13

**Comment by ryanheise** [comment] 2020-08-24 15:09
Duplicate of #158 .

**Closed by ryanheise** 2020-08-24 15:09 UTC
Labels: 1 backlog, bug
