### ISSUE TITLE
Doesn't work when launched from the background

### ISSUE THREAD

**Issue by scullabyte** [ryanheise/just_audio#62] opened 2020-03-26 19:10 UTC
When using `flutter_background_fetch` `just_audio` doesn't play if the app isn't in the foreground. It's a pretty rare use case so just wanted to make you aware and others aware because it took me a while to figure that out. Using `audioplayers` for now.

**Comment by ryanheise** [comment] 2020-03-27 12:44
Hi @scullabyte , is this for iOS or Android or both?

**Comment by scullabyte** [comment] 2020-03-28 19:48
@ryanheise iOS, also `audioplayers` broke this after `0.13.5`

**Comment by ryanheise** [comment] 2020-03-29 00:32
Did you add the `audio` to `UIBackgroundModes` in your `Info.plist` file?

**Comment by scullabyte** [comment] 2020-03-30 19:30
@ryanheise yep

**Comment by ryanheise** [comment] 2020-03-31 00:59
Unfortunately that means it's not something that I would be able to fix in this plugin. The idea of `just_audio` is to "just" expose the audio playing APIs, and if there are any other sets of APIs that you would like to use in addition to this, they would be exposed by different plugins which you could mix and match depending on your use case. These plugins should use non-overlapping sets of APIs so that they don't step on each other's toes when they are mixed together.

I've created `audio_service` to handle creating a background audio session with background notifications and controls for media playback. I think you'd need another plugin similar to that but without setting any controls or info in the control center (should be a lot simpler). Again, note that if I added these API calls to `just_audio`, that would step on the toes of other plugins that other users might want to mix and match with, so I want to avoid any two plugins overlapping in their responsibilities.

If you know any iOS programming, you can also add the needed API calls to app's iOS code.

**Comment by ryanheise** [comment] 2020-08-12 05:18
Another reason audio may not play is due to the AVAudioSession category which you can now set via the API (mentioned in the README). I will close this for now, but if you post a new issue it will help to have a minimal reproduction project.

**Closed by ryanheise** 2020-08-12 05:18 UTC
Labels: 1 backlog, bug
