### ISSUE TITLE
Does not play recorded audio files by flutter_audio_recorder library

### ISSUE THREAD

**Issue by heknt** [ryanheise/just_audio#462] opened 2021-07-28 18:04 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio doen not recognize audio which recorded by [flutter_audio_recorder](https://pub.dev/packages/flutter_audio_recorder) (null safety version is [here](https://github.com/electriko3/flutter_audio_recorder.git), which I used in the project)
I tried AAC (.mp4, .m4a), WAV (.wav) audio formats and different sample rate.

For example, [audioplayers](https://pub.dev/packages/audioplayers) library can play recorded audio file.

**Minimal reproduction project**
https://github.com/heknt/flutter_play_recorded_audio

**To Reproduce (i.e. user steps, not code)**
- lauch app;
- grant permission to record audio;
- comment/uncomment lines in [audio_play.dart](https://github.com/heknt/flutter_play_recorded_audio/blob/main/lib/audio_play.dart). Comment one library to play audio and uncomment another;
- also you can change audio format in [audio_record.dart](https://github.com/heknt/flutter_play_recorded_audio/blob/main/lib/audio_record.dart), file extension in [main.dart](https://github.com/heknt/flutter_play_recorded_audio/blob/main/lib/main.dart).

On each library try to:
1. press button "Record" to record audio;
2. press button "Stop recording";
3. press button "Play" to play recorded audio;
4. press button "Stop playing";

**Error messages**
On just_audio library even does not recognize the recorded audio file. After first button click you can see:
```
E/flutter (26783): #0      AudioPlayer._load (package:just_audio/just_audio.dart:784:9)
E/flutter (26783): <asynchronous suspension>
E/flutter (26783): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1342:28)
```

**Expected behavior**
Recorded audio file must be playable with just_audio library, not only by [audioplayers](https://pub.dev/packages/audioplayers) library.
Which reason of non-working behavior? Maybe because of _bitrate_?

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04 
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 11

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by ryanheise** [comment] 2021-07-29 07:33
Closing as a duplicate of #158 . flutter_audio_recorder was known to be buggy and produced invalid files. Android's native MediaPlayer API is more forgiving and will actually load the invalid file. Google's ExoPlayer library (which is used by just_audio) is more strict and will not accept an invalid wav file. The solution is to not use invalid wav files in the first place.

**Closed by ryanheise** 2021-07-29 07:33 UTC
Labels: 1 backlog, bug
