### ISSUE TITLE
iOS: How to disable playback in AVQueuePlayer of just_audio

### ISSUE THREAD

**Issue by jackwill99** [ryanheise/just_audio#952] opened 2023-03-13 11:46 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to add airPlay in my project and it works. But in audio sharing airPlay has playback control. So, when I play airPlay, audio is playing like a video with playback controller. 

**Describe the solution you'd like**
I can control this in AVPlayer swift like `player?.allowsExternalPlayback = false;`. But you are using AVQueuePlayer and Objective C. 

**Describe alternatives you've considered**
How can I solve this or you can update airplay features in just_audio package.

**Additional context**
[Here](https://docs.jwplayer.com/players/docs/ios-add-an-airplay-button-to-an-app-v3) is the sample of airPlay button and it works.

**Comment by ryanheise** [comment] 2023-03-13 11:56
Although I don't personally have an Apple TV, can you tell me if you think this option should be hard coded to be `false`, or do you think it is useful to add an option to this plugin allowing you to turn it on and off?

**Comment by jackwill99** [comment] 2023-03-13 13:41
@ryanheise  I'm testing from my iPhone to Mac.

If just_audio has an option of `allowExternalPlayback` , that's enough. In a AirPlay mode , if there is playback control , audio is playing with full screen including playback and user can't do anything. It's ok when we are playing video from the airplay. So, i need just an option of playback  controller. In `AVPlayer` , it's easy to control like that
```swift
_flutterAVPlayerViewController = AVPlayerViewController()
let item = AVPlayerItem(url: URL(string: urlString as! String)!)
_flutterAVPlayerViewController.player = AVPlayer(playerItem: item)
_flutterAVPlayerViewController.player?.allowsExternalPlayback = false;
```
But I don't know there is an option like `AVPlayer` and how is `AVQueuePlayer` control that.

If there is an option, we can control airplay both audio and video. Now, I can control airplay with native code but I can't to turn off playback. It's the part of controlling player. **So, I need your help. **

**Comment by ryanheise** [comment] 2023-03-13 13:45
Both Swift and Objective C support the same iOS API, so it's certainly possible to add the option.

But my question to you was whether it will be good enough if I just hard coded this option to `false`. In your use case, you wanted it set to `false`, so that would work for you. But can you imagine any use case where somebody would want to set it to `true` given that just_audio only plays audio and not video?

This will affect the API design decision because I'm not sure yet whether people need the option to set it to `true`.

**Comment by jackwill99** [comment] 2023-03-13 14:11
@ryanheise  I means this option will be very useful for the developer who needs `AirPlay` features using just_audio. This package is for the audio player and that's right. But when we play `AirPlay` as a audio, we needs to turn off this playback. Otherwise, it's playing as a video in `AirPlay` mode. Default setting to true is ok. It needs for using airplay features. 

Here is the example, I'm using just_audio and when airplay playing, my computer can't do anything. I means this situation is good for video streaming airplay. But just_audio is playing for audio and it should playing as an audio in `AirPlay` mode. If we can't set this attributes, audio is playing as video in airplay. Please check this image.

https://drive.google.com/file/d/1M-oJmrE9aCq7fFqk4AP9FaAqaZu14Vbp/view?usp=sharing
https://drive.google.com/file/d/1vNKe5em15BvYFKUr_OT8Jn6DLpc-YpHB/view?usp=sharing

**Comment by ryanheise** [comment] 2023-03-13 14:16
I don't think you're understanding my question. I am trying to design an API for just_audio, and there are two ways I can choose between:

Option 1: I add a method to `AudioPlayer` called `setAllowsExternalPlayback` with a boolean parameter.
Option 2: I can have no additional method but just hard code this option internally to be always `false`.

The question I asked you was intended to help me make that choice.

So I'll repeat the question: Do we actually need Option 1, or will Option 2 be good enough given that this plugin is specifically an audio player and not a video player?

**Comment by jackwill99** [comment] 2023-03-13 14:22
I am really apologize. I miss understanding your question. `Option 1 is the best for us.`

Thanks @ryanheise 
JackWill

**Comment by ryanheise** [comment] 2023-03-13 14:25
Can you explain why always `false` is not enough? In what situation would you want to set it to `true` for an audio player?

**Comment by jackwill99** [comment] 2023-03-13 14:42
Default player is `true`. So, when I play `AirPlay` as a audio , there is a playback control as default. I only want to set it to `false` when I play `AirPlay` as an `audio` for an audio player. 

If it is `true`, there will be a playback control in `AirPlay` mode.

**Comment by ryanheise** [comment] 2023-03-13 14:50
> I'm trying to add airPlay in my project and it works. But in audio sharing airPlay has playback control. So, when I play airPlay, audio is playing like a video with playback controller.

If I understood you correctly, the problem was that it was showing like a video if `allowsExternalPlayback` is `true`, so that's why you want it to be `false` because you're not playing a video, you're playing audio.

I'm just going based on what you described so that's why I'm confused as to why you would ever want to be able to set it to `true` if you're playing audio and not video. just_audio only supports audio and not video, so it seems like an app developer would never want `allowsExternalPlayback` to be `true` if it causes it to show like a video.

**Comment by jackwill99** [comment] 2023-03-13 15:05
> If I understood you correctly, the problem was that it was showing like a video if `allowsExternalPlayback` is `true`, so that's why you want it to be `false` because you're not playing a video, you're playing audio.
> 

Yes, that's why I want it to be `false`. 

I think it should the boolean option because I don't know others developer may need to be `true` or not. But if the app developer needs the features of `AirPlay` in audio player, `allowsExternalPlayback` must be `false`.

**Comment by ryanheise** [comment] 2023-03-13 15:11
OK thanks, and I understand your own use case. However I will wait until I hear from anyone who needs it to be `true` or anyone who can explain why the audio player might need this to be `true`.

**Comment by jackwill99** [comment] 2023-03-13 15:22
So, will just_audio default setting be `false` ??

**Comment by ryanheise** [comment] 2023-03-13 15:34
No decision will be made on that until someone can answer my previous question.

**Comment by BraveEvidence** [comment] 2023-03-15 11:24
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA

**Comment by fmaerkl-sw** [comment] 2023-03-20 09:30
To be clearer about what we are speaking of, here are the concrete behaviors when streaming to an Apple TV or Mac:
## allowsExternalPlayback = true (default, current behavior of just_audio)

![Screen Shot 2023-03-20 at 10 01 39](https://user-images.githubusercontent.com/124357149/226296874-3bf27f85-3eb2-4291-a5f0-4249e1a4ddd4.png)
<img width="1680" alt="Bildschirm­foto 2023-03-20 um 10 08 52 (2)" src="https://user-images.githubusercontent.com/124357149/226296902-6e1e1530-7c0f-4292-9f75-fc869a6ec499.png">

Both show fullscreen playback controls. On the Apple TV, playback can be controlled with the remote, including seeking. But both devices become unusable for other tasks as the player is above everything.

## allowsExternalPlayback = false

![Screen Shot 2023-03-20 at 10 11 17](https://user-images.githubusercontent.com/124357149/226296959-3a74667c-0622-4a46-8b89-68a232bfc2b3.png)
![Bildschirm­foto 2023-03-20 um 10 17 43](https://user-images.githubusercontent.com/124357149/226297191-b11edccd-e629-4c60-b676-27f9a2fa8bd6.png)

The Apple TV shows just a notification for a brief moment when a new media item starts playing. However it seems impossible to pause/play or seek with the Apple TV remote now.
macOS adds playback controls to the menu.


Apple Podcasts and other iOS apps have the `allowsExternalPlayback = false` behavior, so it seems this is the intended setting for pure audio apps. But because the video-like behavior enables playback controls on the Apple TV, this may still be useful to some developers, even if rare.
So I would be leaning towards
> Option 1: I add a method to AudioPlayer called setAllowsExternalPlayback with a boolean parameter.

with the default value being set to false.

**Comment by snipd-mikel** [comment] 2023-10-06 08:53
I agree with @fmaerkl-sw, **Option 1** seems like the best solution. I have checked PocketCasts source code for iOS and they only set `allowsExternalPlayback` to `true` if they are playing video podcast.

**Comment by ryanheise** [comment] 2023-10-06 09:07
Thanks for the input everyone, the preference for Option 1 is unanimous so I will proceed with that approach.

**Comment by ryanheise** [comment] 2023-10-08 15:14
Update: this is implemented but it's getting late so I will push in the morning.

**Comment by ryanheise** [comment] 2023-10-09 02:22
This is now available for testing on the `feature/ios_external_playback` branch.

Note that since this involves a platform interface change, in order to test you will need to comment/uncomment the lines in pubspec so that you can test the local version of the platform interface (see below). Let me know if it works and I'll publish this in the next release.

```diff
% git diff
diff --git a/just_audio/example/pubspec.yaml b/just_audio/example/pubspec.yaml
index 0df6b07..484d082 100644
--- a/just_audio/example/pubspec.yaml
+++ b/just_audio/example/pubspec.yaml
@@ -18,11 +18,11 @@ dependencies:
     path: ../

 # Uncomment when testing platform interface changes.
-# dependency_overrides:
-#   just_audio_platform_interface:
-#     path: ../../just_audio_platform_interface
-#   just_audio_web:
-#     path: ../../just_audio_web
+dependency_overrides:
+  just_audio_platform_interface:
+    path: ../../just_audio_platform_interface
+  just_audio_web:
+    path: ../../just_audio_web

 dev_dependencies:
   # TODO: uncomment these dependencies when they have nullsafe versions.
diff --git a/just_audio/pubspec.yaml b/just_audio/pubspec.yaml
index 3465066..119ad05 100644
--- a/just_audio/pubspec.yaml
+++ b/just_audio/pubspec.yaml
@@ -14,12 +14,12 @@ environment:
   flutter: ">=3.0.0"

 dependencies:
-  just_audio_platform_interface: ^4.2.2
-  # just_audio_platform_interface:
-  #   path: ../just_audio_platform_interface
-  just_audio_web: ^0.4.8
-  # just_audio_web:
-  #   path: ../just_audio_web
+  # just_audio_platform_interface: ^4.2.2
+  just_audio_platform_interface:
+    path: ../just_audio_platform_interface
+  # just_audio_web: ^0.4.8
+  just_audio_web:
+    path: ../just_audio_web
   audio_session: ^0.1.14
   rxdart: '>=0.26.0 <0.28.0'
   path: ^1.8.0
diff --git a/just_audio_web/pubspec.yaml b/just_audio_web/pubspec.yaml
index f7e176a..69cb134 100644
--- a/just_audio_web/pubspec.yaml
+++ b/just_audio_web/pubspec.yaml
@@ -11,9 +11,9 @@ flutter:
         fileName: just_audio_web.dart

 dependencies:
-  just_audio_platform_interface: ^4.2.2
-  # just_audio_platform_interface:
-  #   path: ../just_audio_platform_interface
+  # just_audio_platform_interface: ^4.2.2
+  just_audio_platform_interface:
+    path: ../just_audio_platform_interface
   flutter:
     sdk: flutter
   flutter_web_plugins:
```

**Comment by fmaerkl-sw** [comment] 2023-10-09 06:57
Thanks, works as intended in our project (tested on iOS 17).

**Comment by jackwill99** [comment] 2023-10-10 07:41
It works on test of iOS 17 and macOS Ventura. Thanks ..

**Comment by ryanheise** [comment] 2023-10-19 02:07
Thanks everyone for testing. Since platform interface changes don't happen often, I decided to bundle another platform interface change in this release. Since this feature won't be released until the other feature is also released, can I ask that you also check out the following branch and ensure that everything is still working?

`feature/extractor_options`

You can git stash your changes to the pubspec before switching branches and then pop the stash to get it back.

The other features included are to be able to configure index-based seeking, and also an option to set headers natively rather than via the proxy.

**Comment by fmaerkl-sw** [comment] 2023-10-24 12:13
I did another round of testing. There was a type confusion issue preventing any playback at all, here is a possible fix: https://github.com/ryanheise/just_audio/pull/1102

Other than that, it generally worked but the `allowsExternalPlayback` state is not persisted when the platform player is recreated, for example by calling `stop()` followed by `start()`. Perhaps it should be passed in the load options around here, so a new platform player gets the previously set `allowsExternalPlayback`: https://github.com/ryanheise/just_audio/blob/3622d11f14d4191e4c1326c32c7a025941af40ec/just_audio/lib/just_audio.dart?_#L1820

Another aspect that is a bit inconvenient is that the default `_IdleAudioPlayer()`, which is present before e.g. the first `setAudioSource()` call when the platform player is initialized, throws an exception. But this does not seem to be a real issue if the API is used in the right order and maybe also applies to all the other options, so might be out of scope here.

**Comment by ryanheise** [comment] 2023-11-13 06:53
The fix has now been merged into the `minor` branch.

**Comment by ryanheise** [comment] 2023-11-13 09:19
This has now been published, so I'll now close. Thanks all for the testing and feedback on how the API should work.

**Closed as completed by ryanheise** 2023-11-13 09:19 UTC
Labels: enhancement, 2 fixing
