### ISSUE TITLE
Youtube Api queue problem

### ISSUE THREAD

**Issue by cometothed4rkside** [ryanheise/just_audio#818] opened 2022-09-16 13:19 UTC
**Is your feature request related to a problem? Please describe.**
Hi first of all thanks for this great library. When I create a playlist, it sends requests to all youtube links at once. And this causes the user to spend a lot of internet. I want to create a playlist and when it's time for the song, I want to send a request to the youtube api and get the url of that song. I don't want to send requests to all of them when the playlist creates. I will be grateful if you could help me.

**My youtube api code:**
Future getSongUrl(songId) async {
var yt = YoutubeExplode();
final manifest = await yt.videos.streamsClient.getManifest(songId);
return manifest.audioOnly[1].url.toString();
}

**Describe the solution you'd like**
Retrieving links from the api when the song is playing.

**Additional context**
https://pub.dev/packages/youtube_explode_dart

**Comment by ryanheise** [comment] 2022-09-16 13:23
`ConcatenatingAudioSource(useLazyPreparation: true)` is intended for this purpose although isn't implemented for iOS yet.

However, you can try the `feature/treadmill` branch to see if it improves for you. Also, `DarwinLoadControl(preferredForwardBufferDuration: ...)` should help, but reports are that this iOS option doesn't actually have any effect (unfortunately).

**Comment by ryanheise** [comment] 2022-09-16 13:24
Related to #294 .

**Comment by cometothed4rkside** [comment] 2022-09-16 13:31
I added the feature/treadmill feature, but they all send requests to the api at the same time. This is my code:

```
final _playlist = ConcatenatingAudioSource(
useLazyPreparation: true
      children: [
        getMusicVideos("LkzUf7cKLNA"),
        getMusicVideos("LkzUf7cKLNA"),
        getMusicVideos("LkzUf7cKLNA"),
        getMusicVideos("LkzUf7cKLNA"),
        getMusicVideos("LkzUf7cKLNA"),
  ]);

 getMusicVideos(songId) {
  print("dasdasdasdas");
  return AudioSource.uri(
    Uri.parse(""),
    tag: AudioMetadata(
      album: "Science Friday",
      title: "A Salute To Head-Scratching Science",
      artwork:
      "https://media.wnyc.org/i/1400/1400/l/80/1/ScienceFriday_WNYCStudios_1400.jpg",
    ),
  );
}
```

**Comment by ryanheise** [comment] 2022-09-16 13:39
I'm not sure how that is possible given that `feature/treadmill` does not even add all of the items to the playback queue. It is impossible for them to all be loaded at the same time. I am guessing that you are not actually using the branch?

**Comment by cometothed4rkside** [comment] 2022-09-16 13:45
Yes, I added that **feature/treadmill.** When I add song from my own server as a url, I see that there are 2 requests to my server. But when I want to add the url returned in the getMusicVideos function instead of a my server url, it works 5 times and output dasdasdasdas 5 times.

 ```
getMusicVideos(songId) {
  print("dasdasdasdas");
  return AudioSource.uri(
    Uri.parse(""),
    tag: AudioMetadata(
      album: "Science Friday",
      title: "A Salute To Head-Scratching Science",
      artwork:
      "https://media.wnyc.org/i/1400/1400/l/80/1/ScienceFriday_WNYCStudios_1400.jpg",
    ),
  );
}
```

**Comment by ryanheise** [comment] 2022-09-16 13:47
Do you care about how many times that message prints, or do you care about how many times a request is made to the server? The prints have nothing to do with the requests.

**Comment by cometothed4rkside** [comment] 2022-09-16 14:20
The problem is that we don't know the music links at start. While creating the list, we need to send the music link.  **Uri.parse("")**, But we don't have the link. For this, we use a function and request the link of the video from youtube. What we want to do is to get this link only when it's time for that song.

I tried the code you mentioned on iOS, but still, all elements send requests to youtube at the same time while creating a list.
We want the **getMusicVideo** function to run for each element in its turn.

Sorry maybe I am doing it wrong. The codes I use are can you check please?

```
Future<String> getMusicVideo(songId) async {
  final manifest = await yt.videos.streamsClient.getManifest(songId);
  print(manifest.muxed.last.url.toString());
  return manifest.muxed.last.url.toString();
}

UriAudioSource _createAudioSource(songId)  {
  String link = "";
  getMusicVideo(songId).then((value) {
   link = value;
  });
  return AudioSource.uri(
    Uri.parse(link),
    tag: AudioMetadata(
      album: "Science Friday",
      title: "A Salute To Head-Scratching Science",
      artwork:
      "https://media.wnyc.org/i/1400/1400/l/80/1/ScienceFriday_WNYCStudios_1400.jpg",
    ),
  );
}

  final _playlist = ConcatenatingAudioSource(
      useLazyPreparation: true,
      children: []);

  final mappingAudioSources = [
    _createAudioSource("ttPclYviWso"),
    _createAudioSource("iCDEB1NW-RY"),
    _createAudioSource("ZYYKHXqGgZg"),
  ];
  _playlist.addAll(mappingAudioSources);

```

**Comment by ryanheise** [comment] 2022-09-16 14:25
OK, I think I understand your feature request now. Is it a duplicate of #777 ?

**Comment by cometothed4rkside** [comment] 2022-09-16 14:31
Yes we need #779 feature to iOS.

**Comment by ryanheise** [comment] 2022-09-16 14:32
OK, it's a duplicate. I'll close this issue, and please follow #777 instead.

**Comment by ryanheise** [comment] 2022-09-16 14:32
Duplicate of #777

**Closed as completed by ryanheise** 2022-09-16 14:32 UTC
Labels: bug, 1 backlog
