### ISSUE TITLE
Dispose native audio player on development hot restart

### ISSUE THREAD

**Issue by lukepighetti** [ryanheise/just_audio#134] opened 2020-07-29 23:12 UTC
I noticed that if you're playing a song and you do a ~cold~ hot restart (not hot reload) during development playbackState is lost. Would be nice if it worked like it does with hot reload.

**Comment by ryanheise** [comment] 2020-07-30 04:56
Changing classification to a feature request.

**Comment by lukepighetti** [comment] 2020-07-30 13:03
An alternative is to make sure the player is disposed on cold refresh. I don't believe this is currently working when you call `AudioPlayer.dispose()`, but I could be mistaken.

**Comment by lukepighetti** [comment] 2020-07-30 13:04
Is there a way to call `AudioPlayer.dispose()` internally to the package on cold restart?

**Comment by ryanheise** [comment] 2020-07-30 16:55
Can you clarify what you mean by a "cold refresh"?

**Comment by lukepighetti** [comment] 2020-07-30 17:43
To the best of my knowledge there are three ways to refresh/reload a flutter app.

1) install the flutter app
2) perform a cold restart (i said refresh by mistake)
3) perform a hot reload

**Comment by ryanheise** [comment] 2020-07-31 02:24
Can you clarify what you mean by cold restart for both iOS and Android? And also what you mean by quit? Apologies if you have a standard definition in mind, but I can think of a few different ways to interpret this.

**Comment by lukepighetti** [comment] 2020-07-31 12:16
In VSCode with DartCode extension.

<img width="472" alt="Screen Shot 2020-07-31 at 8 15 13 AM" src="https://user-images.githubusercontent.com/666539/89034029-23140300-d306-11ea-9cd9-5b3d7b27d087.png">

**Comment by lukepighetti** [comment] 2020-07-31 12:18
Said another way, if you hit that green `restart` button the audio keeps playing and the state doesn't reflect the actual native player state. Ideally the native player state would be reset when you hit the green `restart` button.

**Comment by ryanheise** [comment] 2020-07-31 12:19
Excuse my ignorance, but what exactly do the cold restart and quit buttons do? (I'm not a VSCode user)

**Comment by lukepighetti** [comment] 2020-07-31 12:24
Here's how they map

from `flutter run`

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```

yellow lightning bolt => "hot reload"
green refresh => "hot restart"
red square => "quit"

**Comment by ryanheise** [comment] 2020-07-31 13:42
Ideally what I would like to happen on a hot restart is that the playback state is reset, and the audio resources used on the platform side are also disposed of (so that the audio stops). I'm not aware of any plugin callback that I can implement to do this, and Flutter's plugin API is still evolving and becoming more flexible over time, so one day this may be possible.

Keeping the audio playback going after a hot restart, and then trying to have the `playbackState` reflect that after a hot restart does not seem compatible with the purpose of hot restart which is to clear the app state completely.

Quit should stop the audio on Android already, but I'm not sure if there is a way to handle this on iOS yet. But if you are aware of a way to do it, let me know and I'd be happy to implement it.

**Comment by lukepighetti** [comment] 2020-07-31 15:24
Quit stops the audio on both android and iOS to the best of my knowledge.

This may be a `flutter/flutter` issue?

**Comment by ryanheise** [comment] 2020-07-31 15:27
Probably. There's a chance there is a plugin API I don't know about, but if not, then I'll need them to add a plugin lifecycle hook that allows me to cleanly dispose of platform resources on a hot restart.

**Comment by lukepighetti** [comment] 2020-07-31 16:59
`flutter/flutter` feature request has been made here https://github.com/flutter/flutter/issues/62678

**Comment by ryanheise** [comment] 2020-07-31 17:04
Thanks for posting it. Hopefully there is already an API that exists which they will point to, otherwise it will go into their back log and probably materialise by next year or later given they probably have higher priorities, but it is good to get the ball rolling.

**Comment by Skyost** [comment] 2020-08-31 20:58
I'm also interested in this as my users are complaining about the audio that never stops.

**Comment by ryanheise** [comment] 2020-09-01 04:38
@Skyost , Do your users use hot restart? I am surprised about that since hot restart is something that is only accessible in a development environment.

**Comment by Skyost** [comment] 2020-09-01 05:58
@ryanheise Nop ah ah. But I was just wondering if a fix to this issue will work for my users who are facing the problem I've described above.

**Comment by ryanheise** [comment] 2020-09-01 06:02
Since it's not the same issue, you will need to open a new issue with the details, if indeed it is a bug. A bug would be if you called `stop` or `pause` or `dispose` and the audio kept playing. If it kept playing because you didn't call one of these methods, then that is not a bug. Note that I will mark my reply and yours as off topic so as to keep this issue on topic.

**Comment by shumiyao** [comment] 2021-03-15 21:52
Any one got any luck?

I was trying to use [reassemble method](https://api.flutter.dev/flutter/widgets/State/reassemble.html)

```
Called whenever the application is reassembled during debugging, for example during hot reload.
```

But I have not been able to get it working. It would be helpful only if this method could be used to stop all the music being played at hot reload (which we use only in debugging).

**Comment by ryanheise** [comment] 2021-03-16 01:32
That's interesting. What I would need in the plugin is a platform-side solution.

This looks like it might have potential: https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html#addEngineLifecycleListener-io.flutter.embedding.engine.FlutterEngine.EngineLifecycleListener-

**Comment by ericmartineau** [comment] 2021-03-23 23:13
@ryanheise 

For the cold restart (I've always called it hot restart/hot reload), there is no way on the dart side to know when this occurs.  The native plugin code has to hold its own references and then dispose of any old resources when the plugin is initialized a second time.

The `reassemble` approach works for hot reload, and each developer could manage that on their own by keeping resources alive, or by calling `dispose` and then reinitializing.  I'm happy to implement on the Android side, and I could do it for Swift, but my Obj-C is not good enough...

**Comment by ryanheise** [comment] 2021-06-20 12:58
I've now implemented this on Android for hot restart on `dev`. Unfortunately the API I needed to do this was deprecated, but I will continue using it until it's deleted because there is no alternative, and the Flutter team is now aware of the use case via @lukepighetti 's issue (https://github.com/flutter/flutter/issues/62678 ).

Still not sure what I can do on the iOS side.

**Comment by ryanheise** [comment] 2021-10-30 02:55
Now tracking https://github.com/flutter/flutter/issues/10437

**Comment by ArkeshGKalathiya** [comment] 2022-01-25 07:48
Maybe you can use technique used by audioplayers [https://github.com/bluefireteam/audioplayers](url) plugin, they collect unique id for the audio source from the programmer and they possibly store it in the native side, and user can get previous players by calling AudioPlayer.players method ( maybe in the initState or somewhere else, depends on the use case ) and then can dispose each player.

**Comment by ryanheise** [comment] 2022-01-25 09:46
just_audio internally keeps track of all players, so something like this is in theory possible. i.e. to add an API that can be called from an app's `main` method to dispose of any existing players. I say `main` rather than in a widget because hot restart is the issue, not hot reload.

Although perhaps there is another hack that does not involve having to manually call this API. For example, reference counting the flutter engines. It would require some experimentation. In the meantime, if you use iOS and want to do a hot restart, you might just try hitting the stop button in your app's UI before triggering the hot restart.

**Comment by ArkeshGKalathiya** [comment] 2022-02-04 05:34
I think until we find the possible solution we should provide a method to user to dispose everything, so at least development can be done easily. If you can point me or guide me, I am more than happy to submit the pull request.

**Comment by ryanheise** [comment] 2022-02-04 09:41
I'd rather not add such a method to the public API if it can be done internally. I'll try to implement a better workaround.

**Comment by ryanheise** [comment] 2022-02-04 12:13
I have a workaround now that's working on iOS, but will just finish off #644 before returning to this.

**Comment by ryanheise** [comment] 2022-02-06 13:53
Can you try the 0.9.19 release which includes a workaround?

**Comment by ArkeshGKalathiya** [comment] 2022-02-07 04:07
Tested on the iOS, it works on "Hot Restart" now.

**Comment by ryanheise** [comment] 2022-02-07 04:41
Great, thanks for testing. I'll close this issue since the Android side was already implemented earlier.

**Closed by ryanheise** 2022-02-07 04:41 UTC
Labels: enhancement, 1 backlog
