### ISSUE TITLE
Save to file?

### ISSUE THREAD

**Issue by puntodamar** [ryanheise/just_audio#223] opened 2020-10-26 10:11 UTC
**Is your feature request related to a problem? Please describe.**
Basically it's like whatsapp/telegram where you stream & download the audio at the same time

**Describe the solution you'd like**
 The user wont have to stream again if it's already saved in device, just play it directly

**Describe alternatives you've considered**
-

**Additional context**
-

thank you for your response

**Comment by ryanheise** [comment] 2020-10-26 10:14
I believe this is a duplicate of another open issue #47 . I will reopen if you feel it's different.

**Closed by ryanheise** 2020-10-26 10:14 UTC
Labels: 1 backlog, enhancement
