### ISSUE TITLE
Remote m4a audio file throws exception 

### ISSUE THREAD

**Issue by alexgrusu** [ryanheise/just_audio#1145] opened 2023-12-12 19:48 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Use `example_caching.dart`

**To Reproduce (i.e. user steps, not code)**
1. The URL should not contain the file extension (e.g., remoteUrl = 'https://example.com/path/file')
2. newUrl = remoteUrl + '.m4a' (i.e., result is 'https://example.com/path/file.m4a')
3. Change `await _player.setAudioSource()` to `await _player.setUrl(newUrl);`
4. Press play 

**Error messages**

```
 Error loading audio source: (-1008) resource unavailable
```

**Expected behavior**
The issue might be related to the fact that I've set the extension manually.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.0

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.2 23B92 darwin-arm64 (Rosetta), locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

**Additional context**
I have a recorded audio with the following properties
```
 AudioEncoder encoder = AudioEncoder.aacLc,
  int bitRate = 128000,
  int sampleRate = 44100,
  int numChannels = 2,
```

The result is uploaded to the cloud.

Then, we have a service that provides a link for that audio file.

The link doesn't contain the file extension and we can't modify the link (it's not under our control).

I know on iOS the extension is important, so I thought a solution might be to add the extension manually (concatenated to the URL).

**Comment by ryanheise** [comment] 2023-12-13 01:33
It feels like you're laughing your way through the first section by not completing it, while disregarding the first instruction that you must complete it:

```
<!--    ALL SECTIONS BELOW MUST BE COMPLETED   -->
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
```

I mean, it says "All sections" must be completed, and then you skip the very first section and don't complete it.

Also, this bug report is not ready yet for me to reproduce, you didn't actually give me the example that is ready to run. 

You're not going to be one of those difficult people who is going to go back and forth with me 10 times all the while resisting what the instructions say, are you? Let me know in advance if that's the case because I don't have the physical capacity for that.

> **To Reproduce (i.e. user steps, not code)**
> Steps to reproduce the behavior:
> 1. The URL should not contain the file extension (e.g., remoteUrl = 'https://example.com/path/file')
> 2. newUrl = remoteUrl + '.m4a' (i.e., result is 'https://example.com/path/file.m4a')
> 3. Change `await _player.setAudioSource()` to `await _player.setUrl(newUrl);`

When I say "USER STEPS, NOT CODE", and you proceed to fill that section in by giving me coding steps, not user steps, again I feel you're laughing your way through this and you just don't care about or respect what I have actually asked for in the instructions. Where is the "ready to use" reproduction project? And what steps do I have to do "as a user" to cause the bug? e.g. click this button, scroll, ...

The purpose of these instructions are to make it actually possible for me to work on this project because my physical condition makes it difficult for me to work at a computer, and yet I have to waste my time explaining to you why I really need what I said I need in the instructions.

I am going to close the issue as invalid. If you decide to open another issue, please, please don't laugh your way through the instructions by skipping sections or not providing what is asked for.

**Closed as completed by ryanheise** 2023-12-13 01:33 UTC
Labels: bug, 1 backlog
