### ISSUE TITLE
seemingly valid MP3 file not being played back

### ISSUE THREAD

**Issue by tiloc** [ryanheise/just_audio#299] opened 2021-02-08 23:53 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
I am trying to play an MP3 asset back using the following line of code:
`AudioPlayer()..setAsset('assets/audio/bloodpressure.mp3')..play()
`

**Minimal reproduction project**
`AudioPlayer()..setAsset('assets/audio/bloodpressure.mp3')..play()
`

**To Reproduce (i.e. user steps, not code)**
Add just_audio and an MP3 asset to pubspec.yaml
Execute the line of code as given.

**Error messages**
```
2021-02-09 00:40:16.202 31891-31891/com.legentix.flutter_healthcare W/tter_healthcar: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
2021-02-09 00:40:16.208 31891-31891/com.legentix.flutter_healthcare I/ExoPlayerImpl: Init cef914c [ExoPlayerLib/2.12.2] [redfin, Pixel 5, Google, 30]
2021-02-09 00:40:16.332 31891-32279/com.legentix.flutter_healthcare E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1028)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-02-09 00:40:16.333 31891-31891/com.legentix.flutter_healthcare E/AudioPlayer: TYPE_SOURCE: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor) could read the stream.
2021-02-09 00:40:16.363 31891-31924/com.legentix.flutter_healthcare E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: (0) Source error
    #0      AudioPlayer._load (package:just_audio/just_audio.dart:668:9)
    <asynchronous suspension>
    #1      AudioPlayer._setPlatformActive.<anonymous closure> (package:just_audio/just_audio.dart:1039:28)
    <asynchronous suspension>
    #2      AudioPlayer.play (package:just_audio/just_audio.dart:740:28)
    <asynchronous suspension>
```

**Expected behavior**
The MP3 file is being played back. The file was generated using Amazon Polly and is being recognized by my MacOS as a 24kHz mono MP3 file.

**Screenshots**
n.a.

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11

**Flutter SDK version**
```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Mac OS X 10.13.6 17G14042 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 10.1.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

```

**Additional context**

**Comment by ryanheise** [comment] 2021-02-09 00:29
I am closing this issue for two reasons

1. You didn't provide the actual reproduction case in Section 2. The asset name `bloodpressure.mp3` is unresolvable. I cannot inspect the file to see if the file is incorrectly encoded.
2. Errors like this in any case need to be fixed upstream by submitting a bug to Google's ExoPlayer project. But keep in mind that they will also be able to do nothing for you if you don't provide them with the reproduction case.

If you don't want to provide the requested information, or provide similar information to the ExoPlayer authors, you could try to resolve the problem yourself by re-encoding your asset in different ways until you find an encoding that can be parsed by ExoPlayer.

**Closed by ryanheise** 2021-02-09 00:29 UTC
Labels: 1 backlog, bug

**Comment by tiloc** [comment] 2021-02-09 21:45
Ok, thanks for the response. I didn't know what ExoPlayer is or that it is being used by your native code until I saw your response. Maybe the README section on platform specifics could point out a short list of formats that are known to be well-supported across the platforms that your plugin is supporting? I assume I will have to pick a format that is supported by all 3 of them if I want to run on all 3. But I didn't know about ExoPlayer until yesterday, and I don't know what is being used on iOS yet, so a few pointers in the README would really help.

**Comment by ryanheise** [comment] 2021-02-10 01:58
MP3s are supported on all platforms so this issue isn't about the supported formats. The problem is that your specific MP3 file could not be played by ExoPlayer for some unknown reason that can't be investigated without the actual reproduction case. Sometimes this is because it is an invalid MP3 file. The ExoPlayer team will be able to expertly look at your particular MP3 file and figure out whether it is a problem with your MP3 file or with their extractor/decoder, and if the latter, they will be able to fix the bug.
