### ISSUE TITLE
Unable to play DRM-protected music

### ISSUE THREAD

**Issue by lain-ke** [ryanheise/just_audio#252] opened 2020-12-06 22:33 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
I fetch a song from my server which is DRM-protected except for the first 10 seconds (to load it faster), so I get the bytes of the track and create a file (as _temp.mp3_), then I play the DRM-protected file while I decrypt the file, and once decrypted I replace the asset with the new decrypted file. But instead of playing (the one with DRM-protection) it throws an exception both on iOS and Android.

**Minimal reproduction project**
```
 Directory _dir = await getTemporaryDirectory();
  
 _response = await _dio.get(_fileUrl);

 File _tempTrack = File('${_dir.path}/temp.mp3');
 await _tempTrack.writeAsBytes(utf8.encode(_response.data), flush: true);

 return _tempTrack.path;
```

And on the BackgroundService:

```
// This first line runs the function above to get the file path
await _player.setAsset(await getLink(trackMetaData.id));
await onPlay();
```

**To Reproduce (i.e. user steps, not code)**
1. Click a button that runs the above code.

**Error messages**

<details>
  <summary>iOS</summary>

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
flutter: #0      AudioPlayer._load (package:just_audio/just_audio.dart:498:9)
<asynchronous suspension>
#1      AudioPlayer.load (package:just_audio/just_audio.dart:456:30)
#2      AudioPlayer.setAsset (package:just_audio/just_audio.dart:437:7)
#3      AudioPlayerTask.getTrack (package:lainke_music/functions/music.dart:139:21)
<asynchronous suspension>
#4      AudioPlayerTask.onCustomAction (package:lainke_music/functions/music.dart:90:15)
<asynchronous suspension>
#5      AudioServiceBackground.run.<anonymous closure> (package:audio_service/audio_service.dart:1319:42)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
#8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
#9      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:58:29<…>
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(-11800, The operation could not be completed, null, null)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException((-11800) The operation could not be completed, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      AudioService.customAction (package:audio_service/audio_service.dart:1064:27)
#4      updateQueue (package:lainke_music/functions/music.dart:355:22)
#5      playTrack (package:lainke_music/functions/handlers.dart:133:9)
#6      trackHorizontalList.<anonymous closure>.<anonymous closure> (package:lainke_music/widgets/widgets.dart:134:66)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#9      BaseTapGestureRecognize<…>
```

</details>

<details>
  <summary>Android</summary>

```
I/VideoCapabilities( 6959): Unsupported profile 4 for video/mp4v-es
```
</details>

**Expected behavior**
The first 10 seconds of the DRM-protected file should play.

**Screenshots**
Not applicable.

**Desktop**
 - OS: MacOS Big Sur 11.0.1
 - Browser Safari 14.0.1

**Smartphone**
 - Device: iPhone 12 Pro Max (simulator) & Android Pixel 3A API 30 (simulator)
 - OS: iOS 14.2 & Android 11

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
    ✓ Flutter plugin installed.
    ✓ Dart plugin installed.
[!] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
    ! Error: iPhone is not paired with your computer. To use iPhone with Xcode, unlock it and choose to trust this computer when prompted. (code -9)

! Doctor found issues in 1 category.
```

**Additional context**
Putting the link directly doesn't work.

**Comment by ryanheise** [comment] 2020-12-07 02:43
I am closing this bug report because it does not follow the instructions. Please read them carefully as I will not investigate an issue that don't follow what the instructions ask you to do.

**Closed by ryanheise** 2020-12-07 02:43 UTC
Labels: 1 backlog, bug

**Comment by lain-ke** [comment] 2020-12-07 12:49
What do you mean by “it doesn’t follow the instructions”?

**Comment by ryanheise** [comment] 2020-12-07 13:48
When you submitted the bug report, there were instructions below each section explaining what information you needed to provide. You need to follow those instructions in order to submit a valid bug report as all of that information is necessary in order for me to be able to investigate the bug. The first section is required to confirm that what you are describing is really a bug in the plugin. The second and third sections are required in order for me to reproduce the bug. Since you didn't really provide what was asked for in the first section, I'm not convinced this is a bug. And even if it is a bug, you didn't provide me with what was asked for in sections 2 and 3 to allow me to reproduce the supposed bug.

I am not sure if you want me to walk you through each section one by one. Can you not just read the instructions carefully? If you feel the instructions are unclear, I would like to improve those instructions so it would be good if you could let me know in what ways I could make the language a bit clearer.
