### ISSUE TITLE
ConcatenatingAudioSource - Does not play sounds from storage

### ISSUE THREAD

**Issue by GlitchCode-ops** [ryanheise/just_audio#198] opened 2020-10-04 19:33 UTC
Thanks for the awesome plugin you have developed, it is a huge help for our community.

**Which API doesn't behave as documented, and how does it misbehave?**

I am currently using just_audio 0.5.2 and I am trying to use ConcatenatingAudioSource to load audio files that are both located in assets folder as well as audio files from storage. It seems I cannot load audio files from storage. I have tried this on Android only.

**Minimal reproduction project**
When I use the following code just to load the audio files from assets it works like a charm:

```
await _player.load(
ConcatenatingAudioSource(children: playlist.map((item) => AudioSource.uri(Uri.parse('asset:///${item.soundpath}'))).toList()));
```

However, once I try to load audio files from storage by twining the above statement to:

```
children: playlist.map((item) => AudioSource.uri(Uri.file(item.soundpath, windows: true))).toList())
```

Please check the complete code here: https://github.com/GlitchCode-ops/issue/blob/main/Just_audioExecution

**To Reproduce (i.e. user steps, not code)**
1. Use the code in the above link
2. un-comment line 41 and comment line 40
3. provide a path of a sound file on your local storage
4. observe the crash / error 

**Error messages**

```
════════ Exception caught by widgets library ═══════════════════════════════════
The getter 'currentIndex' was called on null.
Receiver: null
Tried calling: currentIndex
═══════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: The getter 'currentIndex' was called on null.
I/ExoPlayerImpl( 6671): Init df19851 [ExoPlayerLib/2.11.7] [generic_x86, Android SDK built for x86, Google, 27]
E/ExoPlayerImplInternal( 6671): Source error
E/ExoPlayerImplInternal( 6671):   com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/ExoPlayerImplInternal( 6671):       at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:222)
E/ExoPlayerImplInternal( 6671):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:122)
E/ExoPlayerImplInternal( 6671):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:988)

```

**Expected behavior**
The sound is not being reproduced and the above error is thrown.

**Screenshots**
This will not provide further information.

**Smartphone (please complete the following information):**
 - Device: Pixel_2_API_27:5554, Android Emulator

**Flutter SDK version**
```
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (9 weeks ago) • 2020-08-05 19:53:19 -0700
Tools • Dart 2.9.0
```

**Additional Information**

I would appreciate if you could provide me some guidance on how to bypass this issue. To allow me to use concatenatingAudioSource to load audio files that are located both in assets  folder or storage. Thanks for your time and assistance in advance.

**Comment by ryanheise** [comment] 2020-10-05 01:25
Hi @GlitchCode-ops , thanks for your bug report. Can you please provide a link to the minimal reproduction project?

And under the section "To Reproduce (i.e. user steps, not code)", make sure that it is user steps, not code.

**Comment by GlitchCode-ops** [comment] 2020-10-05 19:24
I apologize for the inconvenience caused. I have now added the required information.

**Comment by ryanheise** [comment] 2020-10-06 02:11
> **To Reproduce (i.e. user steps, not code)**
> Steps to reproduce the behavior:
> 
>     1. Use the code in the above link
> 
>     2. un-comment line 41 and comment line 40
> 
>     3. provide a path of a sound file on your local storage

Not code, please. If necessary, use the file_picker package to pick a file.

**Comment by ryanheise** [comment] 2020-10-08 13:48
Will close this, as it's almost certainly not a bug in this plugin and is probably a bug in your app. If you have evidence to the contrary, you will need to submit a complete bug report as per the instructions.

**Closed by ryanheise** 2020-10-08 13:48 UTC
Labels: 1 backlog, bug
