### ISSUE TITLE
Multiple logs on Android Debug

### ISSUE THREAD

**Issue by dmckminard** [ryanheise/just_audio#1050] opened 2023-09-07 08:07 UTC
**Which API doesn't behave as documented, and how does it misbehave?**
On Android in debug mode, debug lines are continuously displayed in the terminal.
This subject has already been mentioned, but in an issue of another package: https://github.com/ryanheise/audio_service/issues/267 

**Minimal reproduction project**
This can be reproduced simply by using an application that runs JustAudio on Android, when JustAudio is active (I'm using VsCode on Mac).

**To Reproduce (i.e. user steps, not code)**
Use JustAudio on Android, launch Audio.

**Error messages**
For example :
```
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
D/BufferPoolManager(21295): register existing connection 91463022639134
D/BufferPoolManager(21295): register existing connection 3665301086615
```

**Expected behavior**
Logs could be deactivated in my opinion

**Screenshots**
https://ibb.co/WKMGL1g

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4
 - VSCode 1.81.1

**Smartphone (please complete the following information):**
 - Device: Honor 8X (same on other Android phones, tested on OnePlus 6 and Huawei P30)
 - OS: Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Additional context**
N/A

**Comment by ryanheise** [comment] 2023-09-07 14:30
> This subject has already been mentioned, but in an issue of another package: [ryanheise/audio_service#267](https://github.com/ryanheise/audio_service/issues/267)

And that issue says that there is already an open issue for just_audio, so I'll close this one.

Duplicate of #429

**Closed as completed by ryanheise** 2023-09-07 14:30 UTC
Labels: bug, 1 backlog
