### ISSUE TITLE
Play some short audio files

### ISSUE THREAD

**Issue by fupingren** [ryanheise/just_audio#146] opened 2020-08-12 13:35 UTC
**Is your feature request related to a problem? Please describe.**
when i play some short audio files ,example english words files.

**Describe the solution you'd like**
maybe :  1、one file in the queue can loop some times:after the first file loop some times,then play next one  2、time interval after one file play completed

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment] 2020-08-12 15:29
Hi @fupingren , it's not clear to me how what you're describing is different from the looping features that already exist. Please comment on the alternatives and explain why they are not ideal (since you didn't fill in this section).

**Comment by fupingren** [comment] 2020-08-13 03:07
thank your reply,  1、it means that  Loop current item for special times, loop next item for same special times too  . it's also a queue loop mode ,but every item in the queue will be played special same times.  this feature can be defined by a FrequencyofEveryitemInLoopAll propery,default value=1 .    2、because of the file is very short, so add blank interval, special seconds between two items. it can be defined by PauseSecondsBetweenItemsInLoopMode,default value=0

**Comment by ryanheise** [comment] 2020-08-13 03:10
In other words, do you want a `SilenceAudioSource` which plays silence for a specified duration?

**Comment by fupingren** [comment] 2020-08-13 03:14
yeah,it can resolved the second request.PauseSecondsBetweenItemsInLoopMode

**Comment by ryanheise** [comment] 2020-08-13 03:18
Would you be satisfied with the alternative I proposed? It fits better into the composable API.

**Comment by fupingren** [comment] 2020-08-13 06:39
yes,it's fine to the second request.

**Comment by ryanheise** [comment] 2020-08-13 06:58
I don't know what you mean by the "second request", but if you mean `PauseSecondsBetweenItemsInLoopMode`, that is not the alternative I am proposing. I am proposing another type of audio source called `SilenceAudioSource` (see above). Will this be sufficient for you?

**Comment by fupingren** [comment] 2020-08-13 07:43
yes,thanks

**Comment by fupingren** [comment] 2020-09-04 08:01
i found it https://github.com/google/ExoPlayer/blob/6bfdf8f8f65a2d7a03d90e5e2e3bcdf80af31a94/library/core/src/main/java/com/google/android/exoplayer2/source/SilenceMediaSource.java
it just be my request.

**Comment by ryanheise** [comment] 2020-09-04 16:59
Yes, that's what I had in mind. Apologies for not having implemented this yet, but it may be a while before I get to this as there are several higher priority issues.

However, note that in the meantime, you can create your own "silence" audio file of the desired duration and use that for the same purpose.

**Comment by ryanheise** [comment] 2021-01-11 06:50
Note to self: Maybe this can be implemented using [AVAssetResourceLoaderDelegate](https://stackoverflow.com/questions/13741950/assigning-avasset-from-nsdata). The silent audio data would need to be encoded, so I'd need to generate appropriate silence audio bytes for a given duration in some encoding.

**Comment by ryanheise** [comment] 2021-06-07 08:42
Duplicate of #421

**Closed** 2021-06-07 08:42 UTC
Labels: 1 backlog, enhancement
